//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AMapTrackObject.h"

@class NSDictionary, NSString;

@interface AMapTrackTerminal : AMapTrackObject
{
    NSString *_tid;
    NSString *_name;
    NSString *_desc;
    long long _createTime;
    long long _locateTime;
    NSDictionary *_customProperties;
}

+ (id)ajo_mapping;
@property(retain, nonatomic) NSDictionary *customProperties; // @synthesize customProperties=_customProperties;
@property(nonatomic) long long locateTime; // @synthesize locateTime=_locateTime;
@property(nonatomic) long long createTime; // @synthesize createTime=_createTime;
@property(copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *tid; // @synthesize tid=_tid;
- (void).cxx_destruct;
- (id)description;
- (void)ajo_ignoredSetValue:(id)arg1 forUndefinedMappingKey:(id)arg2;
- (id)init;

@end

