//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AMapRESTRequestReformer.h"

@interface AMapTrackPostRESTRequestReformer : AMapRESTRequestReformer
{
}

- (void)reformParameters:(id)arg1 additionalParameters:(id)arg2 withScode:(_Bool)arg3 result:(CDUnknownBlockType)arg4;

@end

