//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BargainResponseHandler, NSString, YMMBargainSendMessageTask;

@interface BargainRequestTask : NSObject
{
    NSString *_taskIdentifier;
    YMMBargainSendMessageTask *_task;
    BargainResponseHandler *_responseHandler;
}

@property(retain, nonatomic) BargainResponseHandler *responseHandler; // @synthesize responseHandler=_responseHandler;
@property(retain, nonatomic) YMMBargainSendMessageTask *task; // @synthesize task=_task;
@property(retain, nonatomic) NSString *taskIdentifier; // @synthesize taskIdentifier=_taskIdentifier;
- (void).cxx_destruct;
- (id)initWithIdentifier:(id)arg1 task:(id)arg2 response:(id)arg3;

@end

