//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface BaseResponse : PBGeneratedMessage
{
    unsigned int hasErrCode_:1;
    unsigned int hasErrMsg_:1;
    int errCode;
    NSString *errMsg;
}

+ (id)builderWithPrototype:(id)arg1;
+ (id)builder;
+ (id)parseFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
+ (id)parseFromCodedInputStream:(id)arg1;
+ (id)parseFromInputStream:(id)arg1 extensionRegistry:(id)arg2;
+ (id)parseDelimitedFromInputStream:(id)arg1;
+ (id)parseFromInputStream:(id)arg1;
+ (id)parseFromData:(id)arg1 extensionRegistry:(id)arg2;
+ (id)parseFromData:(id)arg1;
+ (id)defaultInstance;
+ (void)initialize;
@property(retain) NSString *errMsg; // @synthesize errMsg;
@property int errCode; // @synthesize errCode;
- (id)builder;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (_Bool)isInitialized;
- (id)defaultInstance;
- (id)init;
- (void)dealloc;
- (void)setHasErrMsg:(_Bool)arg1;
- (_Bool)hasErrMsg;
- (void)setHasErrCode:(_Bool)arg1;
- (_Bool)hasErrCode;

@end

