//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BDSTTSEventManager : NSObject
{
}

+ (id)createEventManagerWithName:(id)arg1;
- (void)releaseInstance;
- (id)libver;
- (_Bool)setDelegate:(id)arg1;
- (void)sendCommand:(id)arg1 withParameters:(id)arg2;
- (void)sendCommand:(id)arg1;
- (_Bool)setParameter:(id)arg1 forKey:(id)arg2;

@end

