//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CAShapeLayer, UIColor;

@interface CornerView : UIView
{
    double _lineWidth;
    UIColor *_lineColor;
    long long _cornerPosition;
    CornerView *_relativeViewX;
    CornerView *_relativeViewY;
    CAShapeLayer *_cornerShapeLayer;
}

@property(retain, nonatomic) CAShapeLayer *cornerShapeLayer; // @synthesize cornerShapeLayer=_cornerShapeLayer;
@property(nonatomic) CornerView *relativeViewY; // @synthesize relativeViewY=_relativeViewY;
@property(nonatomic) CornerView *relativeViewX; // @synthesize relativeViewX=_relativeViewX;
@property(nonatomic) long long cornerPosition; // @synthesize cornerPosition=_cornerPosition;
@property(retain, nonatomic) UIColor *lineColor; // @synthesize lineColor=_lineColor;
@property(nonatomic) double lineWidth; // @synthesize lineWidth=_lineWidth;
- (void).cxx_destruct;
- (void)updateSizeWithWidth:(double)arg1 height:(double)arg2;
- (void)drawCornerLines;
- (id)initWithFrame:(struct CGRect)arg1 lineColor:(id)arg2 lineWidth:(double)arg3;

@end

