//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface Diff : NSObject <NSCopying>
{
    int operation;
    NSString *text;
}

+ (id)diffWithOperation:(int)arg1 andText:(id)arg2;
@property(copy, nonatomic) NSString *text; // @synthesize text;
@property(nonatomic) int operation; // @synthesize operation;
- (unsigned long long)hash;
- (_Bool)isEqualToDiff:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithOperation:(int)arg1 andText:(id)arg2;

@end

