//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonNetworkTask.h"

@interface GetUserDataSyncNoticeProtocolInfoTask : YMMCommonNetworkTask
{
    long long _pageNo;
}

@property(nonatomic) long long pageNo; // @synthesize pageNo=_pageNo;
- (Class)ymm_responseModelClass;
- (id)ymm_networkAPIPath;

@end

