//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonNetworkTask.h"

@class NSNumber;

@interface GTGetDriverPayInfoNewTask : YMMCommonNetworkTask
{
    NSNumber *_goodId;
    NSNumber *_contractId;
    NSNumber *_bargainId;
}

@property(retain, nonatomic) NSNumber *bargainId; // @synthesize bargainId=_bargainId;
@property(retain, nonatomic) NSNumber *contractId; // @synthesize contractId=_contractId;
@property(retain, nonatomic) NSNumber *goodId; // @synthesize goodId=_goodId;
- (void).cxx_destruct;
- (long long)ymm_riskStage;
- (Class)ymm_responseModelClass;
- (id)ymm_propertiesMap;
- (id)ymm_networkAPIPath;

@end

