//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class GTPayResultInsuranceInfoModel, GTPayResultWitnessInfoModel;

@interface GTNewPayResultModel : YMMCommonModel
{
    GTPayResultWitnessInfoModel *_witnessInfo;
    GTPayResultInsuranceInfoModel *_insuranceInfo;
}

@property(retain, nonatomic) GTPayResultInsuranceInfoModel *insuranceInfo; // @synthesize insuranceInfo=_insuranceInfo;
@property(retain, nonatomic) GTPayResultWitnessInfoModel *witnessInfo; // @synthesize witnessInfo=_witnessInfo;
- (void).cxx_destruct;

@end

