//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseTableViewCell.h"

#import "UITextFieldDelegate.h"

@class GTDriverFeePayInfoItemNewModel, NSNumber, NSString, UILabel, UITextField, UIView;

@interface GTNewPayAmoutInputCell : YMMBaseTableViewCell <UITextFieldDelegate>
{
    NSString *_pricePlaceholder;
    GTDriverFeePayInfoItemNewModel *_infoModel;
    NSNumber *_infoPrice;
    id <GTNewPayAmoutInputCellDelegate> _delegate;
    UIView *_inputBgView;
    UITextField *_inputTextField;
    UILabel *_depLab;
    UILabel *_symLab;
    UILabel *_backLabel;
}

+ (double)ymm_heightForCellWithItem:(id)arg1 contentWidth:(double)arg2;
+ (id)cellWithTableView:(id)arg1;
@property(retain, nonatomic) UILabel *backLabel; // @synthesize backLabel=_backLabel;
@property(retain, nonatomic) UILabel *symLab; // @synthesize symLab=_symLab;
@property(retain, nonatomic) UILabel *depLab; // @synthesize depLab=_depLab;
@property(retain, nonatomic) UITextField *inputTextField; // @synthesize inputTextField=_inputTextField;
@property(retain, nonatomic) UIView *inputBgView; // @synthesize inputBgView=_inputBgView;
@property(nonatomic) __weak id <GTNewPayAmoutInputCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSNumber *infoPrice; // @synthesize infoPrice=_infoPrice;
@property(retain, nonatomic) GTDriverFeePayInfoItemNewModel *infoModel; // @synthesize infoModel=_infoModel;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *pricePlaceholder; // @synthesize pricePlaceholder=_pricePlaceholder;
- (id)generatePricePlaceholderAttrString;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidBeginEditing:(id)arg1;
- (id)doneView;
- (void)confirm;
- (void)moneyTFDidChange:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

