//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class NSString;

@interface GTServiceConfigModel : YMMCommonModel
{
    _Bool _show;
    NSString *_cid;
    NSString *_tag;
}

@property(nonatomic) _Bool show; // @synthesize show=_show;
@property(retain, nonatomic) NSString *tag; // @synthesize tag=_tag;
@property(retain, nonatomic) NSString *cid; // @synthesize cid=_cid;
- (void).cxx_destruct;

@end

