//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSDictionary, UILabel;

@interface HCBActivityItemView : UIView
{
    UILabel *_lblActivityTitle;
    UILabel *_lblActivityDes;
    NSDictionary *_itemDic;
}

+ (id)getActivityItemView;
@property(retain, nonatomic) NSDictionary *itemDic; // @synthesize itemDic=_itemDic;
@property(nonatomic) __weak UILabel *lblActivityDes; // @synthesize lblActivityDes=_lblActivityDes;
@property(nonatomic) __weak UILabel *lblActivityTitle; // @synthesize lblActivityTitle=_lblActivityTitle;
- (void).cxx_destruct;
- (void)setupViewInfo:(id)arg1;
- (void)awakeFromNib;

@end

