//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HCBETCBaseViewController.h"

#import "ETCTimeChangeDelegate.h"
#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class ETCCreditAuthTimerManager, NSArray, NSDate, NSDictionary, NSString, NSTimer, UIButton, UILabel, UIPickerView, UITableView, UITextField, UIView;

@interface HCBChargeCardBankCardAddVC : HCBETCBaseViewController <UITableViewDataSource, UITableViewDelegate, UIPickerViewDataSource, UIPickerViewDelegate, ETCTimeChangeDelegate>
{
    NSString *_applicantId;
    CDUnknownBlockType _finishBlock;
    UITableView *_tableView;
    NSArray *_datasource;
    NSArray *_banks;
    UIPickerView *_picker;
    UITextField *_bankTF;
    UITextField *_bankCardTF;
    UITextField *_phoneTF;
    UILabel *_tableViewHeader;
    UIView *_tableViewFooter;
    UITextField *_codeTF;
    UIButton *_retryBtn;
    NSTimer *_countDownTimer;
    long long _countDown;
    NSDate *_beforeDate;
    NSString *_tradeNo;
    NSDictionary *_params;
    ETCCreditAuthTimerManager *_timer;
}

@property(retain, nonatomic) ETCCreditAuthTimerManager *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) NSDictionary *params; // @synthesize params=_params;
@property(retain, nonatomic) NSString *tradeNo; // @synthesize tradeNo=_tradeNo;
@property(retain, nonatomic) NSDate *beforeDate; // @synthesize beforeDate=_beforeDate;
@property(nonatomic) long long countDown; // @synthesize countDown=_countDown;
@property(retain, nonatomic) NSTimer *countDownTimer; // @synthesize countDownTimer=_countDownTimer;
@property(retain, nonatomic) UIButton *retryBtn; // @synthesize retryBtn=_retryBtn;
@property(retain, nonatomic) UITextField *codeTF; // @synthesize codeTF=_codeTF;
@property(retain, nonatomic) UIView *tableViewFooter; // @synthesize tableViewFooter=_tableViewFooter;
@property(retain, nonatomic) UILabel *tableViewHeader; // @synthesize tableViewHeader=_tableViewHeader;
@property(retain, nonatomic) UITextField *phoneTF; // @synthesize phoneTF=_phoneTF;
@property(retain, nonatomic) UITextField *bankCardTF; // @synthesize bankCardTF=_bankCardTF;
@property(retain, nonatomic) UITextField *bankTF; // @synthesize bankTF=_bankTF;
@property(retain, nonatomic) UIPickerView *picker; // @synthesize picker=_picker;
@property(retain, nonatomic) NSArray *banks; // @synthesize banks=_banks;
@property(retain, nonatomic) NSArray *datasource; // @synthesize datasource=_datasource;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(copy, nonatomic) CDUnknownBlockType finishBlock; // @synthesize finishBlock=_finishBlock;
@property(retain, nonatomic) NSString *applicantId; // @synthesize applicantId=_applicantId;
- (void).cxx_destruct;
- (void)loadTimer;
- (void)fetchBankList;
- (void)timerRepeat;
- (void)smsAuthApply;
- (void)textFieldDidChange:(id)arg1;
- (void)sendSMS:(id)arg1;
- (void)addBtnAction;
- (void)changedTime:(long long)arg1;
- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (id)pickerView:(id)arg1 titleForRow:(long long)arg2 forComponent:(long long)arg3;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

