//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, UILabel, UIView;

@interface HCBETCInvoiceTitleCell : UITableViewCell
{
    CDUnknownBlockType _editBtnClickBlock;
    CDUnknownBlockType _deleteBtnClickBlock;
    UILabel *_titleLabel;
    UILabel *_typeLabel;
    UILabel *_taxNumLabel;
    UIButton *_editBtn;
    UIButton *_deleteBtn;
    UILabel *_bindETCCardNumLabel;
    UIView *_line1;
}

@property(retain, nonatomic) UIView *line1; // @synthesize line1=_line1;
@property(retain, nonatomic) UILabel *bindETCCardNumLabel; // @synthesize bindETCCardNumLabel=_bindETCCardNumLabel;
@property(retain, nonatomic) UIButton *deleteBtn; // @synthesize deleteBtn=_deleteBtn;
@property(retain, nonatomic) UIButton *editBtn; // @synthesize editBtn=_editBtn;
@property(retain, nonatomic) UILabel *taxNumLabel; // @synthesize taxNumLabel=_taxNumLabel;
@property(retain, nonatomic) UILabel *typeLabel; // @synthesize typeLabel=_typeLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(copy, nonatomic) CDUnknownBlockType deleteBtnClickBlock; // @synthesize deleteBtnClickBlock=_deleteBtnClickBlock;
@property(copy, nonatomic) CDUnknownBlockType editBtnClickBlock; // @synthesize editBtnClickBlock=_editBtnClickBlock;
- (void).cxx_destruct;
- (void)loadEnterpriseInvioceMasonry;
- (void)loadPersonInvioceMasonry;
- (void)loadMasonry;
- (void)setModel:(id)arg1;
- (void)deleteBtnClick:(id)arg1;
- (void)editBtnClick:(id)arg1;
- (void)initView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

