//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HCBETCRootBaseViewController.h"

@interface HCBETCBaseViewController : HCBETCRootBaseViewController
{
    _Bool _autoHideNavigationBarWhenViewWillAppear;
}

@property(nonatomic) _Bool autoHideNavigationBarWhenViewWillAppear; // @synthesize autoHideNavigationBarWhenViewWillAppear=_autoHideNavigationBarWhenViewWillAppear;
- (void)setInteractivePopPopEnabled:(_Bool)arg1;
- (void)setupUI;
- (void)setup;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)init;

@end

