//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface HCBETCCreditCardRouter : NSObject
{
    _Bool _debugFlow;
    long long _applyStatus;
}

+ (id)router;
@property(nonatomic) _Bool debugFlow; // @synthesize debugFlow=_debugFlow;
@property(nonatomic) long long applyStatus; // @synthesize applyStatus=_applyStatus;
- (void)dispatchViewControllerWithParam:(id)arg1;

@end

