//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface HCBETCInvoiceApplyPostageModel : NSObject
{
    NSString *_address;
    NSString *_phone;
    NSString *_expressNumber;
    NSString *_expressCompany;
    NSString *_name;
    unsigned long long _postPayStatus;
    long long _postageApplyStatus;
    long long _postageAmount;
}

@property(nonatomic) long long postageAmount; // @synthesize postageAmount=_postageAmount;
@property(nonatomic) long long postageApplyStatus; // @synthesize postageApplyStatus=_postageApplyStatus;
@property(nonatomic) unsigned long long postPayStatus; // @synthesize postPayStatus=_postPayStatus;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *expressCompany; // @synthesize expressCompany=_expressCompany;
@property(retain, nonatomic) NSString *expressNumber; // @synthesize expressNumber=_expressNumber;
@property(retain, nonatomic) NSString *phone; // @synthesize phone=_phone;
@property(retain, nonatomic) NSString *address; // @synthesize address=_address;
- (void).cxx_destruct;
- (id)init;

@end

