//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "HCBETCMyInvoiceHeaderFilterBtnDelegate.h"

@class HCBETCInoviceDateFilterView, HCBETCInoviceTableViewFilterView, HCBETCMyInvoiceHeaderFilterBtn, NSArray, NSString, UILabel;

@interface HCBETCMyInvoiceTableViewHeader : UIView <HCBETCMyInvoiceHeaderFilterBtnDelegate>
{
    UIView *_containerView;
    NSArray *_carArray;
    CDUnknownBlockType _headerContext;
    CDUnknownBlockType _valueChangedBlock;
    UILabel *_titleLabel;
    HCBETCMyInvoiceHeaderFilterBtn *_plateNumBtn;
    HCBETCMyInvoiceHeaderFilterBtn *_dateBtn;
    HCBETCMyInvoiceHeaderFilterBtn *_typeBtn;
    HCBETCInoviceTableViewFilterView *_plateFilterView;
    HCBETCInoviceDateFilterView *_dateFilterView;
    HCBETCInoviceTableViewFilterView *_typeFilterView;
}

@property(retain, nonatomic) HCBETCInoviceTableViewFilterView *typeFilterView; // @synthesize typeFilterView=_typeFilterView;
@property(retain, nonatomic) HCBETCInoviceDateFilterView *dateFilterView; // @synthesize dateFilterView=_dateFilterView;
@property(retain, nonatomic) HCBETCInoviceTableViewFilterView *plateFilterView; // @synthesize plateFilterView=_plateFilterView;
@property(retain, nonatomic) HCBETCMyInvoiceHeaderFilterBtn *typeBtn; // @synthesize typeBtn=_typeBtn;
@property(retain, nonatomic) HCBETCMyInvoiceHeaderFilterBtn *dateBtn; // @synthesize dateBtn=_dateBtn;
@property(retain, nonatomic) HCBETCMyInvoiceHeaderFilterBtn *plateNumBtn; // @synthesize plateNumBtn=_plateNumBtn;
@property(nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(copy, nonatomic) CDUnknownBlockType valueChangedBlock; // @synthesize valueChangedBlock=_valueChangedBlock;
@property(copy, nonatomic) CDUnknownBlockType headerContext; // @synthesize headerContext=_headerContext;
@property(retain, nonatomic) NSArray *carArray; // @synthesize carArray=_carArray;
@property(nonatomic) __weak UIView *containerView; // @synthesize containerView=_containerView;
- (void).cxx_destruct;
- (void)removeFilterView;
- (void)resetFilterBtn;
- (void)valueChanged;
- (void)invoiceFilterBtnClick:(id)arg1;
- (void)loadMasonry;
- (void)initView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

