//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface HCBETCInvoiceMinePlateModel : NSObject
{
    _Bool _selected;
    _Bool _defaultItem;
    NSString *_plateNumber;
    NSString *_cardNumber;
}

@property(retain, nonatomic) NSString *cardNumber; // @synthesize cardNumber=_cardNumber;
@property(retain, nonatomic) NSString *plateNumber; // @synthesize plateNumber=_plateNumber;
@property(nonatomic) _Bool defaultItem; // @synthesize defaultItem=_defaultItem;
@property(nonatomic) _Bool selected; // @synthesize selected=_selected;
- (void).cxx_destruct;

@end

