//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HCBETCBaseViewController.h"

@class UIImageView;

@interface HCBETCCancelCardApplySuccessViewController : HCBETCBaseViewController
{
    UIImageView *_iconImageView;
}

@property(nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
- (void)checkCancelHistory:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;

@end

