//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class CALayer, HCBETCInvoiceCardsModel, UIButton, UIImageView, UILabel;

@interface HCBETCInvoiceHomeHeaderViewCell : UICollectionViewCell
{
    HCBETCInvoiceCardsModel *_cardsModel;
    CDUnknownBlockType _editTitleBlock;
    CDUnknownBlockType _invoiceBlock;
    CDUnknownBlockType _bindTitleBlock;
    UIImageView *_imgVBackground;
    CALayer *_layerLine;
    UILabel *_labCarNumber;
    UILabel *_labCardNumber;
    UILabel *_labPriceTips;
    UILabel *_labPriceNumber;
    UILabel *_labTitle;
    UIButton *_buttonInvoice;
    UIButton *_buttonEdit;
    UILabel *_labWarning;
}

@property(retain, nonatomic) UILabel *labWarning; // @synthesize labWarning=_labWarning;
@property(retain, nonatomic) UIButton *buttonEdit; // @synthesize buttonEdit=_buttonEdit;
@property(retain, nonatomic) UIButton *buttonInvoice; // @synthesize buttonInvoice=_buttonInvoice;
@property(retain, nonatomic) UILabel *labTitle; // @synthesize labTitle=_labTitle;
@property(retain, nonatomic) UILabel *labPriceNumber; // @synthesize labPriceNumber=_labPriceNumber;
@property(retain, nonatomic) UILabel *labPriceTips; // @synthesize labPriceTips=_labPriceTips;
@property(retain, nonatomic) UILabel *labCardNumber; // @synthesize labCardNumber=_labCardNumber;
@property(retain, nonatomic) UILabel *labCarNumber; // @synthesize labCarNumber=_labCarNumber;
@property(retain, nonatomic) CALayer *layerLine; // @synthesize layerLine=_layerLine;
@property(retain, nonatomic) UIImageView *imgVBackground; // @synthesize imgVBackground=_imgVBackground;
@property(copy, nonatomic) CDUnknownBlockType bindTitleBlock; // @synthesize bindTitleBlock=_bindTitleBlock;
@property(copy, nonatomic) CDUnknownBlockType invoiceBlock; // @synthesize invoiceBlock=_invoiceBlock;
@property(copy, nonatomic) CDUnknownBlockType editTitleBlock; // @synthesize editTitleBlock=_editTitleBlock;
@property(retain, nonatomic) HCBETCInvoiceCardsModel *cardsModel; // @synthesize cardsModel=_cardsModel;
- (void).cxx_destruct;
- (void)actionBindTitle:(id)arg1;
- (void)actionEditTitle:(id)arg1;
- (void)needHideAllSubView:(_Bool)arg1;
- (void)setupUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

