//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewHeaderFooterView.h"

@class UIButton, UILabel;

@interface HCBFreightOilCardBillHeaderView : UITableViewHeaderFooterView
{
    id <HCBFreightOilCardBillHeaderViewDelegate> _delegate;
    UILabel *_incomeLabel;
    UILabel *_expenditureLabel;
    UIButton *_dateButton;
}

@property(nonatomic) __weak UIButton *dateButton; // @synthesize dateButton=_dateButton;
@property(nonatomic) __weak UILabel *expenditureLabel; // @synthesize expenditureLabel=_expenditureLabel;
@property(nonatomic) __weak UILabel *incomeLabel; // @synthesize incomeLabel=_incomeLabel;
@property(nonatomic) __weak id <HCBFreightOilCardBillHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)configureHeaderViewWithDateText:(id)arg1 income:(id)arg2 expenditure:(id)arg3;
- (void)datePickerAction:(id)arg1;

@end

