//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HCBBaseAlertView.h"

@class UIButton, UIImageView, UILabel;

@interface HCBGasStationPayAlertView : HCBBaseAlertView
{
    long long _alertType;
    CDUnknownBlockType _confirmAction;
    CDUnknownBlockType _cancelAction;
    UIImageView *_tipImageView;
    UILabel *_titleLabel;
    UILabel *_tipsLabel;
    UILabel *_locationLabel;
    UIButton *_rightBtn;
    UIButton *_leftBtn;
}

@property(nonatomic) __weak UIButton *leftBtn; // @synthesize leftBtn=_leftBtn;
@property(nonatomic) __weak UIButton *rightBtn; // @synthesize rightBtn=_rightBtn;
@property(nonatomic) __weak UILabel *locationLabel; // @synthesize locationLabel=_locationLabel;
@property(nonatomic) __weak UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UIImageView *tipImageView; // @synthesize tipImageView=_tipImageView;
@property(copy, nonatomic) CDUnknownBlockType cancelAction; // @synthesize cancelAction=_cancelAction;
@property(copy, nonatomic) CDUnknownBlockType confirmAction; // @synthesize confirmAction=_confirmAction;
@property(nonatomic) long long alertType; // @synthesize alertType=_alertType;
- (void).cxx_destruct;
- (void)leftAction;
- (void)rightAction;
- (void)setupUI;
- (void)dismiss;
- (void)layoutSubviews;
- (id)initAlertViewWithType:(long long)arg1 title:(id)arg2 tipMsg:(id)arg3 locationMsg:(id)arg4 rightAction:(CDUnknownBlockType)arg5 leftAction:(CDUnknownBlockType)arg6;
- (void)awakeFromNib;

@end

