//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray;

@interface HCBGasStationTagView : UIView
{
    NSMutableArray *_titleLayers;
}

@property(copy, nonatomic) NSMutableArray *titleLayers; // @synthesize titleLayers=_titleLayers;
- (void).cxx_destruct;
- (struct CGSize)sizeWithFont:(id)arg1 maxSize:(struct CGSize)arg2 withString:(id)arg3;
- (double)singleModeConfigViewWithArray:(id)arg1;
- (double)configViewWithArray:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

