//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HCBLoanBaseViewModel.h"

@class HCBLoanAppliedQuickCashLoanInfo, HCBLoanDepositBankCard, HCBLoanDepositInfo, HCBLoanPageConfig, HCBLoanTermProduct, NSArray, NSDictionary, NSString;

@interface HCBLoanFillBorrowInfoVM : HCBLoanBaseViewModel
{
    _Bool _contractAgreed;
    _Bool _skipNeedAuth4ElemErrorCheck;
    _Bool _lastSelectedProductIsSelectedByUser;
    HCBLoanPageConfig *_pageConfig;
    NSDictionary *_fourElemBankInfo;
    NSString *_inputMoney;
    HCBLoanTermProduct *_selectedProduct;
    NSArray *_products;
    NSString *_selectedUseScene;
    NSString *_useSceneDesc;
    NSArray *_useSceneList;
    HCBLoanDepositInfo *_deposit;
    HCBLoanDepositBankCard *_selectedBankCard;
    NSArray *_contractList;
    NSString *_inputSMSCode;
    NSString *_inputUserName;
    NSString *_inputIdCard;
    HCBLoanAppliedQuickCashLoanInfo *_loanInfo;
    NSString *_accountType;
    NSString *_latestRefreshProductsMoney;
    long long _maxSMSCodeFailCount;
}

+ (id)viewModelWithAccountType:(id)arg1;
@property(nonatomic) long long maxSMSCodeFailCount; // @synthesize maxSMSCodeFailCount=_maxSMSCodeFailCount;
@property _Bool lastSelectedProductIsSelectedByUser; // @synthesize lastSelectedProductIsSelectedByUser=_lastSelectedProductIsSelectedByUser;
@property(copy) NSString *latestRefreshProductsMoney; // @synthesize latestRefreshProductsMoney=_latestRefreshProductsMoney;
@property(copy, nonatomic) NSString *accountType; // @synthesize accountType=_accountType;
@property(retain, nonatomic) HCBLoanAppliedQuickCashLoanInfo *loanInfo; // @synthesize loanInfo=_loanInfo;
@property(nonatomic) _Bool skipNeedAuth4ElemErrorCheck; // @synthesize skipNeedAuth4ElemErrorCheck=_skipNeedAuth4ElemErrorCheck;
@property(copy, nonatomic) NSString *inputIdCard; // @synthesize inputIdCard=_inputIdCard;
@property(copy, nonatomic) NSString *inputUserName; // @synthesize inputUserName=_inputUserName;
@property(copy, nonatomic) NSString *inputSMSCode; // @synthesize inputSMSCode=_inputSMSCode;
@property(retain, nonatomic) NSArray *contractList; // @synthesize contractList=_contractList;
@property(nonatomic) _Bool contractAgreed; // @synthesize contractAgreed=_contractAgreed;
@property(retain, nonatomic) HCBLoanDepositBankCard *selectedBankCard; // @synthesize selectedBankCard=_selectedBankCard;
@property(retain, nonatomic) HCBLoanDepositInfo *deposit; // @synthesize deposit=_deposit;
@property(retain, nonatomic) NSArray *useSceneList; // @synthesize useSceneList=_useSceneList;
@property(copy, nonatomic) NSString *useSceneDesc; // @synthesize useSceneDesc=_useSceneDesc;
@property(copy, nonatomic) NSString *selectedUseScene; // @synthesize selectedUseScene=_selectedUseScene;
@property(retain, nonatomic) NSArray *products; // @synthesize products=_products;
@property(retain, nonatomic) HCBLoanTermProduct *selectedProduct; // @synthesize selectedProduct=_selectedProduct;
@property(copy, nonatomic) NSString *inputMoney; // @synthesize inputMoney=_inputMoney;
@property(retain, nonatomic) NSDictionary *fourElemBankInfo; // @synthesize fourElemBankInfo=_fourElemBankInfo;
@property(retain, nonatomic) HCBLoanPageConfig *pageConfig; // @synthesize pageConfig=_pageConfig;
- (void).cxx_destruct;
- (void)applyLoanWithCompletion:(CDUnknownBlockType)arg1;
- (id)p_errorForCheckAllInputValues;
@property(readonly, nonatomic) _Bool needVerifyUser4ElemInfo;
- (void)sendSMSCodeCompletion:(CDUnknownBlockType)arg1;
- (void)queryContractListIfNeededWithCompletion:(CDUnknownBlockType)arg1;
- (void)p_updateDepositInfoWithNew:(id)arg1;
- (void)fetchBankCardListWithCompletion:(CDUnknownBlockType)arg1;
- (void)fetchUseSceneWithCompletion:(CDUnknownBlockType)arg1;
- (void)p_updateSelectedProduct:(id)arg1 isSelectedByUser:(_Bool)arg2;
- (void)updateUserSelectedProduct:(id)arg1;
- (void)p_updateProductsWithNewList:(id)arg1;
- (void)queryProductsWithCompletion:(CDUnknownBlockType)arg1;
- (id)p_errorForInvalidInputMoney:(id)arg1;
- (id)inputMoneyErrorForDisplayUnderTextField;
- (void)query4ElemBankInfoCompletion:(CDUnknownBlockType)arg1;
- (void)fetchPageConfigWithCompletion:(CDUnknownBlockType)arg1;
- (void)p_cleanAllSelections;
@property(readonly, copy, nonatomic) NSString *kvoPathInputSMSCode;
@property(readonly, copy, nonatomic) NSString *kvoPathInputIdCard;
@property(readonly, copy, nonatomic) NSString *kvoPathInputUserName;
@property(readonly, copy, nonatomic) NSString *kvoPathContractAgreed;
@property(readonly, copy, nonatomic) NSString *kvoPathSelectedUseScene;
@property(readonly, copy, nonatomic) NSString *kvoPathSelectedBankCard;
@property(readonly, copy, nonatomic) NSString *kvoPathSelectedProduct;
@property(readonly, copy, nonatomic) NSString *kvoPathInputMoney;
- (id)init;

@end

