//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HCBLoanBaseViewController.h"

#import "UIActionSheetDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class HCBLoanCashLoanProduct, HCBLoanCashLoanUserStatus, NSArray, NSMutableArray, NSString, UIButton, UILabel, UITableView, UITextField;

@interface HCBLoanCLNewLoanWayViewController : HCBLoanBaseViewController <UITableViewDataSource, UITableViewDelegate, UIActionSheetDelegate, UIAlertViewDelegate>
{
    _Bool _selectUseScene;
    NSString *_maxAmountStr;
    NSString *_minAmountStr;
    HCBLoanCashLoanUserStatus *_userStatus;
    UITableView *_tableView;
    UIButton *_nextButton;
    UITextField *_amountTF;
    UILabel *_useSceneLabel;
    NSMutableArray *_loanProductsArr;
    NSArray *_useSceneArr;
    NSString *_useSceneTipStr;
    HCBLoanCashLoanProduct *_selectProduct;
}

@property(nonatomic) _Bool selectUseScene; // @synthesize selectUseScene=_selectUseScene;
@property(retain, nonatomic) HCBLoanCashLoanProduct *selectProduct; // @synthesize selectProduct=_selectProduct;
@property(copy, nonatomic) NSString *useSceneTipStr; // @synthesize useSceneTipStr=_useSceneTipStr;
@property(retain, nonatomic) NSArray *useSceneArr; // @synthesize useSceneArr=_useSceneArr;
@property(retain, nonatomic) NSMutableArray *loanProductsArr; // @synthesize loanProductsArr=_loanProductsArr;
@property(nonatomic) __weak UILabel *useSceneLabel; // @synthesize useSceneLabel=_useSceneLabel;
@property(nonatomic) __weak UITextField *amountTF; // @synthesize amountTF=_amountTF;
@property(nonatomic) __weak UIButton *nextButton; // @synthesize nextButton=_nextButton;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) HCBLoanCashLoanUserStatus *userStatus; // @synthesize userStatus=_userStatus;
@property(copy, nonatomic) NSString *minAmountStr; // @synthesize minAmountStr=_minAmountStr;
@property(copy, nonatomic) NSString *maxAmountStr; // @synthesize maxAmountStr=_maxAmountStr;
- (void).cxx_destruct;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldEndEditing:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)textFieldDidChange:(id)arg1;
- (void)use:(id)arg1;
- (void)toNewUserLoanPage;
- (void)toOldUserLoanPage;
- (void)switchToNextPage;
- (void)next:(id)arg1;
- (void)useCouponTip:(id)arg1;
- (void)calculateProductAmount:(id)arg1;
- (id)calcPerDayFee:(id)arg1 loanAmount:(id)arg2;
- (id)calcPerMonthFee:(id)arg1 loanAmount:(id)arg2;
- (id)caclPerMonthRepayFee:(id)arg1 loanAmount:(id)arg2;
- (id)calcDiscountAmount:(id)arg1 loanAmount:(id)arg2;
- (id)calcFeeDesc:(id)arg1 loanAmount:(id)arg2;
- (_Bool)checkValue:(_Bool)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)configMonthCell:(id)arg1 atIndexPath:(id)arg2;
- (id)configDayCell:(id)arg1 atIndexPath:(id)arg2;
- (void)updateUI;
- (void)validatepProductWithCash;
- (void)queryLoanUseScene;
- (void)getLoanProducts;
- (void)updatePage;
- (void)setupTableView;
- (void)setupStyle;
- (void)clickBackButton:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

