//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSString;

@interface HCBLoanPPWithdrawManager : NSObject
{
    NSArray *_insuranceBillInfos;
    NSDictionary *_selectedBankCardData;
    NSArray *_contractList;
    NSString *_userInputSMSCode;
    NSDictionary *_loanResult;
    NSDictionary *_rawDrawingDetailDict;
}

@property(retain, nonatomic) NSDictionary *rawDrawingDetailDict; // @synthesize rawDrawingDetailDict=_rawDrawingDetailDict;
@property(retain, nonatomic) NSDictionary *loanResult; // @synthesize loanResult=_loanResult;
@property(copy, nonatomic) NSString *userInputSMSCode; // @synthesize userInputSMSCode=_userInputSMSCode;
@property(retain, nonatomic) NSArray *contractList; // @synthesize contractList=_contractList;
@property(retain, nonatomic) NSDictionary *selectedBankCardData; // @synthesize selectedBankCardData=_selectedBankCardData;
@property(retain, nonatomic) NSArray *insuranceBillInfos; // @synthesize insuranceBillInfos=_insuranceBillInfos;
- (void).cxx_destruct;
- (void)confirmLoanWithComplection:(CDUnknownBlockType)arg1;
- (void)_throwErrorMsg:(id)arg1 toComplection:(CDUnknownBlockType)arg2;
- (void)sendSMSCodeWithComplection:(CDUnknownBlockType)arg1;
- (void)fetchInsuranceContractListWithComplection:(CDUnknownBlockType)arg1;
- (id)_getInsuranceListParamString;
@property(readonly, nonatomic) NSArray *contractTitles;
- (void)applyTentativeCaculationForBill:(id)arg1 withTerm:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_saveSerializedBillInfos:(id)arg1;
- (void)_handleDrawingDetailDict:(id)arg1;
- (void)queryDrawingsDetailWithCompletion:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) NSArray *bankCardDicts;
@property(readonly, nonatomic) NSString *userPhone;
@property(readonly, nonatomic) NSString *loanInfoDescription;
@property(readonly, nonatomic) NSString *totalMaxLimitString;
@property(readonly, nonatomic) _Bool hasDrawingDetailData;

@end

