//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSLayoutConstraint, UILabel;

@interface HCBLoanCommonTextCell : UITableViewCell
{
    UILabel *_label;
    NSLayoutConstraint *_labelLeading;
    NSLayoutConstraint *_labelTrailing;
    NSLayoutConstraint *_labelTop;
    NSLayoutConstraint *_labelBottom;
}

@property(retain, nonatomic) NSLayoutConstraint *labelBottom; // @synthesize labelBottom=_labelBottom;
@property(retain, nonatomic) NSLayoutConstraint *labelTop; // @synthesize labelTop=_labelTop;
@property(retain, nonatomic) NSLayoutConstraint *labelTrailing; // @synthesize labelTrailing=_labelTrailing;
@property(retain, nonatomic) NSLayoutConstraint *labelLeading; // @synthesize labelLeading=_labelLeading;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)awakeFromNib;

@end

