//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray;

@interface HCBPetrolOrderPriceCellModel : NSObject
{
    double _cellHeight;
    NSArray *_payDetailItems;
    NSArray *_saveDetailItems;
    NSMutableArray *_priceArray;
}

@property(retain, nonatomic) NSMutableArray *priceArray; // @synthesize priceArray=_priceArray;
@property(retain, nonatomic) NSArray *saveDetailItems; // @synthesize saveDetailItems=_saveDetailItems;
@property(retain, nonatomic) NSArray *payDetailItems; // @synthesize payDetailItems=_payDetailItems;
@property(nonatomic) double cellHeight; // @synthesize cellHeight=_cellHeight;
- (void).cxx_destruct;

@end

