//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class HCBUMCEntranceBar, NSMutableArray;

@interface HCBPerolHomeHeaderView : UIView
{
    HCBUMCEntranceBar *_memberBar;
    CDUnknownBlockType _actionPetrolHomeHeaderViewClicked;
    NSMutableArray *_headerItemArray;
}

@property(retain, nonatomic) NSMutableArray *headerItemArray; // @synthesize headerItemArray=_headerItemArray;
@property(copy, nonatomic) CDUnknownBlockType actionPetrolHomeHeaderViewClicked; // @synthesize actionPetrolHomeHeaderViewClicked=_actionPetrolHomeHeaderViewClicked;
@property(retain, nonatomic) HCBUMCEntranceBar *memberBar; // @synthesize memberBar=_memberBar;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setupRedPointWithItemType:(long long)arg1 msg:(id)arg2;
- (id)setupData;
- (void)setupUIPosition;
- (void)setupUIItem;
- (void)removeMemberCenterBar;
- (void)setupMemberCenterBar;
- (void)setupUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

