//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class HCBPetrolOrderStationCellModel, UIImageView, UILabel, UIView;

@interface HCBPetrolOrderStationCell : UITableViewCell
{
    HCBPetrolOrderStationCellModel *_cellModel;
    UIView *_backView;
    UILabel *_nameLabel;
    UIImageView *_nextImage;
}

@property(retain, nonatomic) UIImageView *nextImage; // @synthesize nextImage=_nextImage;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIView *backView; // @synthesize backView=_backView;
@property(retain, nonatomic) HCBPetrolOrderStationCellModel *cellModel; // @synthesize cellModel=_cellModel;
- (void).cxx_destruct;
- (void)updateUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;

@end

