//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface HCBPetrolPayMethod : NSObject
{
    _Bool _isEnable;
    _Bool _isDefault;
    NSString *_accountId;
    NSString *_desc;
    NSString *_payMethodName;
    NSString *_subtitle;
    long long _balance;
    long long _type;
    long long _showGunIndex;
    long long _showOilCodeIndex;
    NSArray *_oilList;
}

+ (id)modelContainerPropertyGenericClass;
@property(retain, nonatomic) NSArray *oilList; // @synthesize oilList=_oilList;
@property(nonatomic) _Bool isDefault; // @synthesize isDefault=_isDefault;
@property(nonatomic) _Bool isEnable; // @synthesize isEnable=_isEnable;
@property(nonatomic) long long showOilCodeIndex; // @synthesize showOilCodeIndex=_showOilCodeIndex;
@property(nonatomic) long long showGunIndex; // @synthesize showGunIndex=_showGunIndex;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) long long balance; // @synthesize balance=_balance;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(copy, nonatomic) NSString *payMethodName; // @synthesize payMethodName=_payMethodName;
@property(copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(copy, nonatomic) NSString *accountId; // @synthesize accountId=_accountId;
- (void).cxx_destruct;
- (_Bool)modelCustomTransformFromDictionary:(id)arg1;

@end

