//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HCBPetrolBaseViewController.h"

@class NSArray, NSString, PayOilFeeSelectOilView, UIButton, UIColor, UIImage, UINavigationController;

@interface HCBPetrolSelectOilVC : HCBPetrolBaseViewController
{
    NSArray *_oilList;
    NSString *_selectedOilCode;
    NSString *_selectedGunNo;
    CDUnknownBlockType _selectResult;
    PayOilFeeSelectOilView *_seletcOilView;
    UIButton *_confirmBtn;
    UINavigationController *_nav;
    UIColor *_originNavBarTintColor;
    UIImage *_originNavBarBackgroundImage;
}

@property(retain, nonatomic) UIImage *originNavBarBackgroundImage; // @synthesize originNavBarBackgroundImage=_originNavBarBackgroundImage;
@property(retain, nonatomic) UIColor *originNavBarTintColor; // @synthesize originNavBarTintColor=_originNavBarTintColor;
@property(nonatomic) __weak UINavigationController *nav; // @synthesize nav=_nav;
@property(retain, nonatomic) UIButton *confirmBtn; // @synthesize confirmBtn=_confirmBtn;
@property(retain, nonatomic) PayOilFeeSelectOilView *seletcOilView; // @synthesize seletcOilView=_seletcOilView;
@property(copy, nonatomic) CDUnknownBlockType selectResult; // @synthesize selectResult=_selectResult;
@property(copy, nonatomic) NSString *selectedGunNo; // @synthesize selectedGunNo=_selectedGunNo;
@property(copy, nonatomic) NSString *selectedOilCode; // @synthesize selectedOilCode=_selectedOilCode;
@property(retain, nonatomic) NSArray *oilList; // @synthesize oilList=_oilList;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (_Bool)isSelectOilAndGun:(id)arg1 gunNo:(id)arg2;
- (void)confirmSelect:(id)arg1;
- (void)setupSelectView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

