//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HCBPetrolBaseViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class HCBPetrolOrderListVCViewModel, HCBPetrolOrderModel, HCBPetrolStationOrderListHearder, HCBTopTabBar, NSMutableArray, NSString, UIColor, UIImage, UINavigationController;

@interface HCBPetrolOrderListVC : HCBPetrolBaseViewController <UITableViewDelegate, UITableViewDataSource>
{
    HCBPetrolOrderListVCViewModel *_viewModel;
    NSMutableArray *_tableViewArrs;
    HCBTopTabBar *_topTabBar;
    HCBPetrolStationOrderListHearder *_nodataView;
    UINavigationController *_nav;
    UIColor *_originNavBarTintColor;
    UIImage *_originNavBarBackgroundImage;
    HCBPetrolOrderModel *_currentPayOrder;
    long long _currentIndex;
}

@property(nonatomic) long long currentIndex; // @synthesize currentIndex=_currentIndex;
@property(retain, nonatomic) HCBPetrolOrderModel *currentPayOrder; // @synthesize currentPayOrder=_currentPayOrder;
@property(retain, nonatomic) UIImage *originNavBarBackgroundImage; // @synthesize originNavBarBackgroundImage=_originNavBarBackgroundImage;
@property(retain, nonatomic) UIColor *originNavBarTintColor; // @synthesize originNavBarTintColor=_originNavBarTintColor;
@property(nonatomic) __weak UINavigationController *nav; // @synthesize nav=_nav;
@property(retain, nonatomic) HCBPetrolStationOrderListHearder *nodataView; // @synthesize nodataView=_nodataView;
@property(retain, nonatomic) HCBTopTabBar *topTabBar; // @synthesize topTabBar=_topTabBar;
@property(retain, nonatomic) NSMutableArray *tableViewArrs; // @synthesize tableViewArrs=_tableViewArrs;
@property(retain, nonatomic) HCBPetrolOrderListVCViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (id)setupPVCurrentPageName;
- (void)toBankWait;
- (void)payFailedWithPaymentURL:(id)arg1;
- (void)handleWalletPaymentResultWithContext:(id)arg1 paymentURL:(id)arg2;
- (void)paymentWithNavigatorURL:(id)arg1;
- (void)gotoPay:(id)arg1 payChannel:(long long)arg2;
- (void)pushOrderDetailVC:(id)arg1;
- (void)btnAciton:(unsigned long long)arg1 orderModel:(id)arg2;
- (void)fetchMoreDataWithIndex:(long long)arg1;
- (void)fetchDataWithIndex:(long long)arg1;
- (id)orderStatusWithTopBarSelectedIndex:(unsigned long long)arg1;
- (void)refreshRedDot;
- (void)setupRefreshView:(id)arg1;
- (void)setupNavViewWillAppear;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)setupNavViewWillDisappear;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

