//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class NSArray, NSString, NSTimer, UICollectionView, UICollectionViewFlowLayout, UIColor, UIControl, UIFont, UIImage, UIImageView;

@interface HCBPetrolCycleScrollView : UIView <UICollectionViewDataSource, UICollectionViewDelegate>
{
    _Bool _isInvalideTimer;
    _Bool _infiniteLoop;
    _Bool _autoScroll;
    _Bool _showPageControl;
    _Bool _hidesForSinglePage;
    _Bool _onlyDisplayText;
    NSArray *_imageURLStringsGroup;
    NSArray *_titlesGroup;
    NSArray *_localizationImageNamesGroup;
    NSArray *_imageURLStringAndDurationGroup;
    double _autoScrollTimeInterval;
    long long _scrollDirection;
    id <HCBCycleScrollViewDelegate> _delegate;
    CDUnknownBlockType _clickItemOperationBlock;
    CDUnknownBlockType _itemDidScrollOperationBlock;
    unsigned long long _bannerMode;
    long long _bannerImageViewContentMode;
    UIImage *_placeholderImage;
    unsigned long long _pageControlStyle;
    unsigned long long _pageControlAliment;
    double _pageControlBottomOffset;
    double _pageControlRightOffset;
    UIColor *_currentPageDotColor;
    UIColor *_pageDotColor;
    UIColor *_titleLabelTextColor;
    UIFont *_titleLabelTextFont;
    UIColor *_titleLabelBackgroundColor;
    double _titleLabelHeight;
    UICollectionView *_contentView;
    UICollectionViewFlowLayout *_flowLayout;
    NSArray *_imagePathsGroup;
    NSArray *_imageDurationGroup;
    NSTimer *_timer;
    long long _totalItemsCount;
    UIControl *_pageControl;
    long long _timeIntervalCount;
    UIImageView *_backgroundImageView;
    struct CGSize _pageControlDotSize;
}

+ (void)clearImagesCache;
+ (id)cycleScrollViewWithFrame:(struct CGRect)arg1 delegate:(id)arg2 placeholderImage:(id)arg3;
+ (id)cycleScrollViewWithFrame:(struct CGRect)arg1 imageURLStringsGroup:(id)arg2;
+ (id)cycleScrollViewWithFrame:(struct CGRect)arg1 shouldInfiniteLoop:(_Bool)arg2 imageNamesGroup:(id)arg3;
+ (id)cycleScrollViewWithFrame:(struct CGRect)arg1 imageNamesGroup:(id)arg2;
@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(nonatomic) long long timeIntervalCount; // @synthesize timeIntervalCount=_timeIntervalCount;
@property(nonatomic) __weak UIControl *pageControl; // @synthesize pageControl=_pageControl;
@property(nonatomic) long long totalItemsCount; // @synthesize totalItemsCount=_totalItemsCount;
@property(nonatomic) __weak NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) NSArray *imageDurationGroup; // @synthesize imageDurationGroup=_imageDurationGroup;
@property(retain, nonatomic) NSArray *imagePathsGroup; // @synthesize imagePathsGroup=_imagePathsGroup;
@property(nonatomic) __weak UICollectionViewFlowLayout *flowLayout; // @synthesize flowLayout=_flowLayout;
@property(nonatomic) __weak UICollectionView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) double titleLabelHeight; // @synthesize titleLabelHeight=_titleLabelHeight;
@property(retain, nonatomic) UIColor *titleLabelBackgroundColor; // @synthesize titleLabelBackgroundColor=_titleLabelBackgroundColor;
@property(retain, nonatomic) UIFont *titleLabelTextFont; // @synthesize titleLabelTextFont=_titleLabelTextFont;
@property(retain, nonatomic) UIColor *titleLabelTextColor; // @synthesize titleLabelTextColor=_titleLabelTextColor;
@property(retain, nonatomic) UIColor *pageDotColor; // @synthesize pageDotColor=_pageDotColor;
@property(retain, nonatomic) UIColor *currentPageDotColor; // @synthesize currentPageDotColor=_currentPageDotColor;
@property(nonatomic) struct CGSize pageControlDotSize; // @synthesize pageControlDotSize=_pageControlDotSize;
@property(nonatomic) double pageControlRightOffset; // @synthesize pageControlRightOffset=_pageControlRightOffset;
@property(nonatomic) double pageControlBottomOffset; // @synthesize pageControlBottomOffset=_pageControlBottomOffset;
@property(nonatomic) unsigned long long pageControlAliment; // @synthesize pageControlAliment=_pageControlAliment;
@property(nonatomic) unsigned long long pageControlStyle; // @synthesize pageControlStyle=_pageControlStyle;
@property(nonatomic) _Bool onlyDisplayText; // @synthesize onlyDisplayText=_onlyDisplayText;
@property(nonatomic) _Bool hidesForSinglePage; // @synthesize hidesForSinglePage=_hidesForSinglePage;
@property(nonatomic) _Bool showPageControl; // @synthesize showPageControl=_showPageControl;
@property(retain, nonatomic) UIImage *placeholderImage; // @synthesize placeholderImage=_placeholderImage;
@property(nonatomic) long long bannerImageViewContentMode; // @synthesize bannerImageViewContentMode=_bannerImageViewContentMode;
@property(nonatomic) unsigned long long bannerMode; // @synthesize bannerMode=_bannerMode;
@property(copy, nonatomic) CDUnknownBlockType itemDidScrollOperationBlock; // @synthesize itemDidScrollOperationBlock=_itemDidScrollOperationBlock;
@property(copy, nonatomic) CDUnknownBlockType clickItemOperationBlock; // @synthesize clickItemOperationBlock=_clickItemOperationBlock;
@property(nonatomic) __weak id <HCBCycleScrollViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long scrollDirection; // @synthesize scrollDirection=_scrollDirection;
@property(nonatomic) _Bool autoScroll; // @synthesize autoScroll=_autoScroll;
@property(nonatomic) _Bool infiniteLoop; // @synthesize infiniteLoop=_infiniteLoop;
@property(nonatomic) double autoScrollTimeInterval; // @synthesize autoScrollTimeInterval=_autoScrollTimeInterval;
@property(nonatomic) _Bool isInvalideTimer; // @synthesize isInvalideTimer=_isInvalideTimer;
@property(retain, nonatomic) NSArray *imageURLStringAndDurationGroup; // @synthesize imageURLStringAndDurationGroup=_imageURLStringAndDurationGroup;
@property(retain, nonatomic) NSArray *localizationImageNamesGroup; // @synthesize localizationImageNamesGroup=_localizationImageNamesGroup;
@property(retain, nonatomic) NSArray *titlesGroup; // @synthesize titlesGroup=_titlesGroup;
@property(retain, nonatomic) NSArray *imageURLStringsGroup; // @synthesize imageURLStringsGroup=_imageURLStringsGroup;
- (void).cxx_destruct;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)adjustWhenControllerViewWillAppera;
- (void)dealloc;
- (void)willMoveToSuperview:(id)arg1;
- (void)layoutSubviews;
- (void)clearCache;
- (int)pageControlIndexWithCurrentCellIndex:(long long)arg1;
- (int)currentIndex;
- (void)scrollToIndex:(int)arg1;
- (void)scrollToNext;
- (void)setupPageControl;
- (void)invalidateTimer;
- (void)setupTimer;
- (void)setupMainView;
- (void)initialization;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

