//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface HCBPetrolOrderDetailModel : NSObject
{
    _Bool _invoicing;
    _Bool _contractSigned;
    NSArray *_payDetailItems;
    NSArray *_saveDetailItems;
    NSArray *_labelList;
    long long _orderStatus;
    long long _payChannel;
    long long _gasStationId;
    NSString *_gasStationName;
    NSString *_orderNo;
    NSString *_orderStatusDes;
    NSString *_createTime;
    NSString *_actualPay;
    NSString *_savePrice;
    NSString *_savePriceShow;
    long long _intervalSeconds;
    NSString *_receiptDes;
    long long _evaluateStatus;
    NSString *_comments;
    NSString *_noPassComments;
    NSString *_refundUrl;
    NSString *_orderStatusHint;
}

+ (id)modelContainerPropertyGenericClass;
@property(copy, nonatomic) NSString *orderStatusHint; // @synthesize orderStatusHint=_orderStatusHint;
@property(nonatomic) _Bool contractSigned; // @synthesize contractSigned=_contractSigned;
@property(copy, nonatomic) NSString *refundUrl; // @synthesize refundUrl=_refundUrl;
@property(copy, nonatomic) NSString *noPassComments; // @synthesize noPassComments=_noPassComments;
@property(copy, nonatomic) NSString *comments; // @synthesize comments=_comments;
@property(nonatomic) long long evaluateStatus; // @synthesize evaluateStatus=_evaluateStatus;
@property(copy, nonatomic) NSString *receiptDes; // @synthesize receiptDes=_receiptDes;
@property(nonatomic) long long intervalSeconds; // @synthesize intervalSeconds=_intervalSeconds;
@property(nonatomic) _Bool invoicing; // @synthesize invoicing=_invoicing;
@property(copy, nonatomic) NSString *savePriceShow; // @synthesize savePriceShow=_savePriceShow;
@property(copy, nonatomic) NSString *savePrice; // @synthesize savePrice=_savePrice;
@property(copy, nonatomic) NSString *actualPay; // @synthesize actualPay=_actualPay;
@property(copy, nonatomic) NSString *createTime; // @synthesize createTime=_createTime;
@property(copy, nonatomic) NSString *orderStatusDes; // @synthesize orderStatusDes=_orderStatusDes;
@property(copy, nonatomic) NSString *orderNo; // @synthesize orderNo=_orderNo;
@property(copy, nonatomic) NSString *gasStationName; // @synthesize gasStationName=_gasStationName;
@property(nonatomic) long long gasStationId; // @synthesize gasStationId=_gasStationId;
@property(nonatomic) long long payChannel; // @synthesize payChannel=_payChannel;
@property(nonatomic) long long orderStatus; // @synthesize orderStatus=_orderStatus;
@property(retain, nonatomic) NSArray *labelList; // @synthesize labelList=_labelList;
@property(retain, nonatomic) NSArray *saveDetailItems; // @synthesize saveDetailItems=_saveDetailItems;
@property(retain, nonatomic) NSArray *payDetailItems; // @synthesize payDetailItems=_payDetailItems;
- (void).cxx_destruct;

@end

