//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface HCBQRCodeTool : NSObject
{
}

+ (id)resizeCodeImage:(id)arg1 withSize:(struct CGSize)arg2;
+ (void)createBarCodeWithImageView:(id)arg1 content:(id)arg2;
+ (id)createNonInterpolatedUIImageFormCIImage:(id)arg1 withSize:(double)arg2;
+ (id)createQRCodeWithImageView:(id)arg1 content:(id)arg2;

@end

