//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface HCBRouteDetailInfoModel : NSObject
{
    long long _routeID;
    long long _routeTime;
    long long _routeLength;
    long long _routeTrafficLightCount;
    long long _routeTollCost;
    NSString *_strategyTitle;
}

@property(copy, nonatomic) NSString *strategyTitle; // @synthesize strategyTitle=_strategyTitle;
@property(nonatomic) long long routeTollCost; // @synthesize routeTollCost=_routeTollCost;
@property(nonatomic) long long routeTrafficLightCount; // @synthesize routeTrafficLightCount=_routeTrafficLightCount;
@property(nonatomic) long long routeLength; // @synthesize routeLength=_routeLength;
@property(nonatomic) long long routeTime; // @synthesize routeTime=_routeTime;
@property(nonatomic) long long routeID; // @synthesize routeID=_routeID;
- (void).cxx_destruct;

@end

