//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HCBMapWarningZoneModel, HCBRoutePeccancyAnnotationView;

@protocol HCBRoutePeccancyAnnotationViewDelegate <NSObject>

@optional
- (void)showCalloutView:(HCBRoutePeccancyAnnotationView *)arg1;
- (void)deSelectedAnnotationView:(HCBRoutePeccancyAnnotationView *)arg1;
- (void)peccancyAnnotationView:(HCBRoutePeccancyAnnotationView *)arg1 selected:(_Bool)arg2 animated:(_Bool)arg3 model:(HCBMapWarningZoneModel *)arg4;
@end

