//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HCBBaseActivityCell.h"

@class HCBSecondActivityTemplateOneView;

@interface HCBSecondActivityTemplateThreeCell : HCBBaseActivityCell
{
    HCBSecondActivityTemplateOneView *_viewFirstSecondActivity;
    HCBSecondActivityTemplateOneView *_viewSecondSecondActivity;
    HCBSecondActivityTemplateOneView *_viewThirdSecondActivity;
}

@property(nonatomic) __weak HCBSecondActivityTemplateOneView *viewThirdSecondActivity; // @synthesize viewThirdSecondActivity=_viewThirdSecondActivity;
@property(nonatomic) __weak HCBSecondActivityTemplateOneView *viewSecondSecondActivity; // @synthesize viewSecondSecondActivity=_viewSecondSecondActivity;
@property(nonatomic) __weak HCBSecondActivityTemplateOneView *viewFirstSecondActivity; // @synthesize viewFirstSecondActivity=_viewFirstSecondActivity;
- (void).cxx_destruct;
- (void)setupCellInfo:(id)arg1;
- (void)setupCellView;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

