//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface HCBSecretTool : NSObject
{
}

+ (id)doDecryptWithData:(id)arg1 withKey:(id)arg2;
+ (id)doDecryptWithText:(id)arg1 withKey:(id)arg2;
+ (id)doEncryptWithData:(id)arg1 withKey:(id)arg2;
+ (id)doEncryptWithText:(id)arg1 withKey:(id)arg2;

@end

