//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AMapSearchDelegate.h"

@class AMapDistanceSearchRequest, AMapSearchAPI, NSString;

@interface HCBTruckNaviTools : NSObject <AMapSearchDelegate>
{
    CDUnknownBlockType _calculateDistanceBlock;
    AMapDistanceSearchRequest *_distanceSearchRequest;
    long long _calculateDistance;
    AMapSearchAPI *_search;
}

+ (long long)ymmUID;
+ (void)releaseTruckNaviVCWith:(Class)arg1;
+ (void)releaseTruckNaviVC;
+ (_Bool)releaseSourceVC:(id)arg1;
+ (id)transformNumToStr:(long long)arg1;
+ (id)durationFormate:(long long)arg1;
+ (_Bool)isHCBDriver;
+ (_Bool)isHCBConsignor;
+ (id)getApplicationName;
+ (void)startNaivWithDesctinationCoor:(struct CLLocationCoordinate2D)arg1 toName:(id)arg2;
+ (id)distanceFormatFloat:(float)arg1;
+ (double)distanceWithToLocation:(struct CLLocationCoordinate2D)arg1;
@property(retain, nonatomic) AMapSearchAPI *search; // @synthesize search=_search;
@property(nonatomic) long long calculateDistance; // @synthesize calculateDistance=_calculateDistance;
@property(retain, nonatomic) AMapDistanceSearchRequest *distanceSearchRequest; // @synthesize distanceSearchRequest=_distanceSearchRequest;
@property(copy, nonatomic) CDUnknownBlockType calculateDistanceBlock; // @synthesize calculateDistanceBlock=_calculateDistanceBlock;
- (void).cxx_destruct;
- (void)onDistanceSearchDone:(id)arg1 response:(id)arg2;
- (void)AMapSearchRequest:(id)arg1 didFailWithError:(id)arg2;
- (void)calculateDistanceWithPoints:(id)arg1 type:(long long)arg2 completedBlock:(CDUnknownBlockType)arg3;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

