//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HCBUStationBaseModel.h"

@class NSString;

@interface HCBUStationDetailInfoGsLabelModel : HCBUStationBaseModel
{
    NSString *_labelName;
    NSString *_fontColor;
    NSString *_bgColor;
    long long _labelCode;
}

@property(nonatomic) long long labelCode; // @synthesize labelCode=_labelCode;
@property(copy, nonatomic) NSString *bgColor; // @synthesize bgColor=_bgColor;
@property(copy, nonatomic) NSString *fontColor; // @synthesize fontColor=_fontColor;
@property(copy, nonatomic) NSString *labelName; // @synthesize labelName=_labelName;
- (void).cxx_destruct;

@end

