//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class HCBUStationDetailInfoModel, NSMutableArray, UIButton, UIImageView, UILabel;

@interface HCBUStationHomeDetailCell : UIView
{
    _Bool _expand;
    HCBUStationDetailInfoModel *_model;
    UIButton *_expandButton;
    UIButton *_navButton;
    UIImageView *_navIcon;
    UILabel *_navMainLabel;
    UILabel *_navSubLabel;
    UIView *_separator;
    UIImageView *_serviceIcon;
    NSMutableArray *_serviceLabels;
}

@property(retain, nonatomic) NSMutableArray *serviceLabels; // @synthesize serviceLabels=_serviceLabels;
@property(retain, nonatomic) UIImageView *serviceIcon; // @synthesize serviceIcon=_serviceIcon;
@property(retain, nonatomic) UIView *separator; // @synthesize separator=_separator;
@property(retain, nonatomic) UILabel *navSubLabel; // @synthesize navSubLabel=_navSubLabel;
@property(retain, nonatomic) UILabel *navMainLabel; // @synthesize navMainLabel=_navMainLabel;
@property(retain, nonatomic) UIImageView *navIcon; // @synthesize navIcon=_navIcon;
@property(retain, nonatomic) UIButton *navButton; // @synthesize navButton=_navButton;
@property(retain, nonatomic) UIButton *expandButton; // @synthesize expandButton=_expandButton;
@property(nonatomic) _Bool expand; // @synthesize expand=_expand;
@property(retain, nonatomic) HCBUStationDetailInfoModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setupUI;
- (id)init;

@end

