//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HCBUMCBaseRequest.h"

@class NSArray;

@interface HCBUMCReqConfig : HCBUMCBaseRequest
{
    NSArray *_configTypeKeys;
}

+ (id)requestForCheckInResultConfig;
@property(retain, nonatomic) NSArray *configTypeKeys; // @synthesize configTypeKeys=_configTypeKeys;
- (void).cxx_destruct;
- (id)processResponseDictionary:(id)arg1;
- (id)buildParams;
- (id)apiPath;

@end

