//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UILabel;

@interface HCBUStationPopularityTag : UIView
{
    long long _level;
    UILabel *_tagLabel;
    UIImageView *_tagImage;
}

@property(retain, nonatomic) UIImageView *tagImage; // @synthesize tagImage=_tagImage;
@property(retain, nonatomic) UILabel *tagLabel; // @synthesize tagLabel=_tagLabel;
@property(nonatomic) long long level; // @synthesize level=_level;
- (void).cxx_destruct;
- (void)sizeToFit;
- (void)layoutSubviews;
- (id)init;

@end

