//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HCBUStationBaseModel.h"

@class NSString;

@interface HCBUStationTagModel : HCBUStationBaseModel
{
    _Bool _negetive;
    NSString *_title;
    NSString *_count;
}

@property(nonatomic, getter=isNegative) _Bool negetive; // @synthesize negetive=_negetive;
@property(retain, nonatomic) NSString *count; // @synthesize count=_count;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;

@end

