//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HCBUStationBaseRequest.h"

@class NSString;

@interface HCBUReqGetConfigInfo : HCBUStationBaseRequest
{
    NSString *_gasStationId;
    NSString *_key;
}

@property(nonatomic) NSString *key; // @synthesize key=_key;
@property(retain, nonatomic) NSString *gasStationId; // @synthesize gasStationId=_gasStationId;
- (void).cxx_destruct;
- (id)processResponseDictionary:(id)arg1;
- (id)buildParams;
- (id)apiPath;

@end

