//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CBCentralManagerDelegate.h"
#import "JLBleMonitorDelegate.h"

@class CBCentralManager, JLTimer, NSArray, NSString;

@interface JLBleBlueToothBase : NSObject <CBCentralManagerDelegate, JLBleMonitorDelegate>
{
    _Bool _initSuccess;
    CBCentralManager *_central;
    JLTimer *_timer;
    CDUnknownBlockType _callBack;
    NSArray *_identiferFlags;
    NSArray *_nameFlags;
}

+ (id)jlGetInstance;
@property(retain, nonatomic) NSArray *nameFlags; // @synthesize nameFlags=_nameFlags;
@property(retain, nonatomic) NSArray *identiferFlags; // @synthesize identiferFlags=_identiferFlags;
@property(copy, nonatomic) CDUnknownBlockType callBack; // @synthesize callBack=_callBack;
@property(retain, nonatomic) JLTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) CBCentralManager *central; // @synthesize central=_central;
@property(nonatomic) _Bool initSuccess; // @synthesize initSuccess=_initSuccess;
- (void).cxx_destruct;
- (void)centralManager:(id)arg1 didDisconnectPeripheral:(id)arg2 error:(id)arg3;
- (void)centralManager:(id)arg1 didFailToConnectPeripheral:(id)arg2 error:(id)arg3;
- (void)centralManager:(id)arg1 didDiscoverPeripheral:(id)arg2 advertisementData:(id)arg3 RSSI:(id)arg4;
- (void)centralManagerDidUpdateState:(id)arg1;
- (int)jlFilterDeviceIdentifier:(id)arg1;
- (int)jlFilterDeviceName:(id)arg1 advData:(id)arg2;
- (id)jlFindDeviceName:(id)arg1 advertisementData:(id)arg2;
- (void)jlWorkEndWithCode:(int)arg1 result:(id)arg2 message:(id)arg3;
- (void)jlInvokeTimer;
- (void)jlcreateTimeWithTimeOut:(double)arg1 beatCount:(int)arg2 onceAction:(CDUnknownBlockType)arg3 timeOutAction:(CDUnknownBlockType)arg4;
- (_Bool)jlCheckBlueToothEnable;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

