//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSMutableArray;

@interface JLPack24Buffer : NSObject
{
    int _perLength;
    NSMutableArray *_dataShouldSend;
    NSData *_workCtlData;
}

+ (id)jlShare;
@property(retain, nonatomic) NSData *workCtlData; // @synthesize workCtlData=_workCtlData;
@property(retain, nonatomic) NSMutableArray *dataShouldSend; // @synthesize dataShouldSend=_dataShouldSend;
@property(nonatomic) int perLength; // @synthesize perLength=_perLength;
- (void).cxx_destruct;
- (id)jlgetWorkCtl;
- (int)jlGetOneSendData:(id *)arg1;
- (id)packDataWithType:(int)arg1 WithContent:(id)arg2 withAuthType:(int)arg3;
- (id)packDataWithType:(int)arg1 WithContent:(id)arg2;
- (id)jlSetEveryBlockDataWith24HeaderForData:(id)arg1 withCount:(unsigned char)arg2 withType:(int)arg3 withPackNum:(unsigned char)arg4 withWorkCtl:(unsigned char)arg5 withAuthType:(int)arg6;
- (id)jlSetEveryBlockDataWith24HeaderForData:(id)arg1 withCount:(unsigned char)arg2 withType:(int)arg3 withPackNum:(unsigned char)arg4 withWorkCtl:(unsigned char)arg5;

@end

