//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JLTrasferLoadService : NSObject
{
}

+ (void)jlLoadCreditCardWithProtocolSDK:(id)arg1 dateMAC2:(id)arg2 callBack:(CDUnknownBlockType)arg3 writeData:(id)arg4;
+ (void)jlWriteToCardWithProtocolSDK:(id)arg1 dateMAC2:(id)arg2 callBack:(CDUnknownBlockType)arg3;
+ (void)jlTrasferLoadServiceWithProtocolSDK:(id)arg1 dateMAC2:(id)arg2 callBack:(CDUnknownBlockType)arg3;

@end

