//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JLUUIDFile : NSObject
{
}

+ (id)uuidPath;
+ (id)filePath;
+ (_Bool)jl_WriteToFile:(id)arg1;
+ (_Bool)jl_FileExist:(id)arg1;
+ (_Bool)jl_CreateDir;
+ (_Bool)jl_IsEqualUUID:(id)arg1;
+ (_Bool)jl_RemoveUUID;
+ (id)jl_GetUUID;
+ (_Bool)jl_WriteUUID:(id)arg1;

@end

