//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MAParticleColorGenerate.h"

@class NSString;

@interface MAParticleRandomColorGenerate : NSObject <MAParticleColorGenerate>
{
    struct RandomColorBetWeenTwoConstants *_randomColor;
}

- (float *)getColor;
- (void)dealloc;
- (id)initWithBoundaryColorR1:(float)arg1 G1:(float)arg2 B1:(float)arg3 A1:(float)arg4 R2:(float)arg5 G2:(float)arg6 B2:(float)arg7 A2:(float)arg8;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

