//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface MAPointsReduceCacheItem : NSObject
{
    NSArray *_indexArr;
    id _userData;
}

@property(retain, nonatomic) id userData; // @synthesize userData=_userData;
@property(retain, nonatomic) NSArray *indexArr; // @synthesize indexArr=_indexArr;
- (void).cxx_destruct;
- (void)dealloc;

@end

