//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonNetworkTask.h"

@interface MBCommonDataRequestTask : YMMCommonNetworkTask
{
}

- (id)ymm_selfDefinedSessionConfiguration;
- (_Bool)ymm_needsOutputLog4Debug;
- (id)ymm_handleResponseObject:(id)arg1;
- (struct NSString *)ymm_contentType;
- (struct NSString *)ymm_httpMethod;
- (Class)ymm_responseModelClass;
- (double)ymm_timeoutInterval;
- (id)ymm_userAgent;
- (id)ymm_requestIgnoreProperties;
- (id)ymm_propertiesMap;
- (id)ymm_requestBody;
- (id)ymm_requestHeader;
- (id)ymm_networkAPIPathExtension;
- (id)ymm_networkAPIPath;
- (id)ymm_networkAPIDomain;
- (id)ymm_riskInfoParam;
- (long long)ymm_riskStage;
- (_Bool)ymm_needActionResponse;
- (_Bool)ymm_supportDataZip;
- (_Bool)ymm_needEncryption;
- (id)ymm_errorMapping;

@end

