//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseModel.h"

@class NSAttributedString, NSString;

@interface MBCTagAlertModel : YMMBaseModel
{
    NSString *_title;
    NSString *_message;
    NSAttributedString *_messageAttr;
    NSString *_leftButton;
    NSString *_rightButton;
    NSString *_router;
}

@property(copy, nonatomic) NSString *router; // @synthesize router=_router;
@property(copy, nonatomic) NSString *rightButton; // @synthesize rightButton=_rightButton;
@property(copy, nonatomic) NSString *leftButton; // @synthesize leftButton=_leftButton;
@property(retain, nonatomic) NSAttributedString *messageAttr; // @synthesize messageAttr=_messageAttr;
@property(copy, nonatomic) NSString *message; // @synthesize message=_message;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;

@end

