//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MBDataObserver.h"
#import "UIScrollViewDelegate.h"

@class NSArray, NSMutableArray, NSMutableDictionary, NSString, UIScrollView;

@interface MBScrollDirector : NSObject <UIScrollViewDelegate, MBDataObserver>
{
    _Bool _useRefresh;
    _Bool _useGetMore;
    NSMutableArray *_dataSourceArray;
    NSArray *_localListJson;
    UIScrollView *_innerScrollView;
    double _refreshTime;
    double _lastRefreshDataSourceItemTime;
    NSMutableArray *_arrViewModels;
    NSMutableDictionary *_componentViewModelMaps;
}

@property(retain, nonatomic) NSMutableDictionary *componentViewModelMaps; // @synthesize componentViewModelMaps=_componentViewModelMaps;
@property(retain, nonatomic) NSMutableArray *arrViewModels; // @synthesize arrViewModels=_arrViewModels;
@property(nonatomic) double lastRefreshDataSourceItemTime; // @synthesize lastRefreshDataSourceItemTime=_lastRefreshDataSourceItemTime;
@property(nonatomic) double refreshTime; // @synthesize refreshTime=_refreshTime;
@property(retain, nonatomic) UIScrollView *innerScrollView; // @synthesize innerScrollView=_innerScrollView;
@property(retain, nonatomic) NSArray *localListJson; // @synthesize localListJson=_localListJson;
@property(readonly, nonatomic) NSMutableArray *dataSourceArray; // @synthesize dataSourceArray=_dataSourceArray;
@property(nonatomic) _Bool useGetMore; // @synthesize useGetMore=_useGetMore;
@property(nonatomic) _Bool useRefresh; // @synthesize useRefresh=_useRefresh;
- (void).cxx_destruct;
- (void)requestFailedForTask:(id)arg1 withError:(id)arg2;
- (void)requestSuccessForTask:(id)arg1;
- (void)becomeActiveNotification:(id)arg1;
- (id)visibleContainerViews;
- (void)sendAllTasks:(id)arg1;
- (void)sendTask:(id)arg1;
- (id)getDataSourceItemForSection:(long long)arg1;
- (id)getJsonForSection:(long long)arg1;
- (long long)sectionIndexForDataSourceItem:(id)arg1;
- (void)addGetMoreTaskForSourceItem:(id)arg1;
- (void)addDataSource:(id)arg1;
- (void)mapComponentIdWithViewModelInstance:(id)arg1;
- (void)refreshViewModels;
- (void)refreshAllData;
- (void)refreshView;
- (void)refreshSection:(long long)arg1;
- (void)refreshAtIndexPath:(id)arg1;
- (void)refreshMoreDataStatus;
- (void)setDataSourceArray:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

