//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel;

@interface RelateInfoCellTitle : UITableViewCell
{
    UILabel *_leftTitleLab;
    UILabel *_rightDescLab;
    UIImageView *_bottomLine;
}

@property(retain, nonatomic) UIImageView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain, nonatomic) UILabel *rightDescLab; // @synthesize rightDescLab=_rightDescLab;
@property(retain, nonatomic) UILabel *leftTitleLab; // @synthesize leftTitleLab=_leftTitleLab;
- (void).cxx_destruct;
- (void)reloadCellData:(id)arg1 rightDesc:(id)arg2;
- (void)addConstraint;
- (void)dealloc;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

