//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "YMMSchemeBaseProtocol.h"

@class NSDictionary, NSNumber, NSString;

@interface Target_cargo : NSObject <YMMSchemeBaseProtocol>
{
    NSNumber *_cargoId;
    NSDictionary *_params;
}

@property(copy, nonatomic) NSDictionary *params; // @synthesize params=_params;
@property(retain, nonatomic) NSNumber *cargoId; // @synthesize cargoId=_cargoId;
- (void).cxx_destruct;
- (void)dealloc;
- (void)pushToAnimatedViewController:(id)arg1;
- (void)fecthCargoScheme;
- (id)Action_view:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

