//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel, UITextField, UIView;

@interface TrunkRoutePlanTableViewCell : UITableViewCell
{
    UILabel *_titleLabel;
    UITextField *_textFiled;
    UILabel *_errorLabel;
    UIView *_bgView;
    UIImageView *_arrorImageV;
}

@property(nonatomic) __weak UIImageView *arrorImageV; // @synthesize arrorImageV=_arrorImageV;
@property(nonatomic) __weak UIView *bgView; // @synthesize bgView=_bgView;
@property(nonatomic) __weak UILabel *errorLabel; // @synthesize errorLabel=_errorLabel;
@property(nonatomic) __weak UITextField *textFiled; // @synthesize textFiled=_textFiled;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)updateCellWithDic:(id)arg1 errorMsg:(id)arg2;
- (void)awakeFromNib;

@end

