//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (Petrol)
+ (id)stretchImage:(id)arg1 resizingMode:(long long)arg2 insets:(struct UIEdgeInsets)arg3;
+ (id)stretchBtnImage:(id)arg1 resizingMode:(long long)arg2;
+ (id)imageWithColor:(id)arg1;
+ (id)imageNamed_Petrol:(id)arg1;
- (id)imageWithTintColor:(id)arg1 blendMode:(int)arg2;
- (id)scaledToSize:(struct CGSize)arg1;
@end

