//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface VFJCryptoUtils : NSObject
{
}

- (id)toStringBlock:(char *)arg1 len:(int)arg2;
- (id)toStringBlock:(char *)arg1 off:(int)arg2 len:(int)arg3;
- (void)spreadShortsToBytes:(int *)arg1 inOff:(int)arg2 outBytes:(char *)arg3 outOff:(int)arg4 len:(int)arg5;
- (void)squashBytesToShorts:(char *)arg1 inOff:(int)arg2 outInts:(int *)arg3 outOff:(int)arg4 len:(int)arg5;
- (void)spreadIntsToBytes:(int *)arg1 inOff:(int)arg2 outBytes:(char *)arg3 outOff:(int)arg4 len:(int)arg5;
- (void)squashBytesToInts:(char *)arg1 inOff:(int)arg2 outInts:(int *)arg3 outOff:(int)arg4 len:(int)arg5;
- (void)fillBlock:(char *)arg1 fill:(unsigned char)arg2 len:(int)arg3;
- (void)fillBlock:(char *)arg1 blockOff:(int)arg2 fill:(unsigned char)arg3 len:(int)arg4;
- (_Bool)equalsBlock:(char *)arg1 b:(char *)arg2 len:(int)arg3;
- (_Bool)equalsBlock:(char *)arg1 aOff:(int)arg2 b:(char *)arg3 bOff:(int)arg4 len:(int)arg5;
- (void)copyBlock:(char *)arg1 dst:(char *)arg2 len:(int)arg3;
- (void)copyBlock:(char *)arg1 srcOff:(int)arg2 dst:(char *)arg3 dstOff:(int)arg4 len:(int)arg5;
- (void)xorBlock:(char *)arg1 inBytesB:(char *)arg2 dst:(char *)arg3 len:(int)arg4;
- (void)xorBlock:(char *)arg1 aOff:(int)arg2 inBytesB:(char *)arg3 bOff:(int)arg4 dst:(char *)arg5 dstOff:(int)arg6 len:(int)arg7;
- (void)randomBlock:(char *)arg1 len:(int)arg2;
- (void)randomBlock:(char *)arg1 off:(int)arg2 len:(int)arg3;
- (void)zeroBlock:(char *)arg1 len:(int)arg2;
- (void)zeroBlock:(char *)arg1 off:(int)arg2 len:(int)arg3;

@end

