//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class NSLayoutConstraint, UIButton, UILabel, UIView;

@interface VFSDKBaitiaoProductCell : UICollectionViewCell
{
    UIView *_containerView;
    NSLayoutConstraint *_containerTop;
    NSLayoutConstraint *_containerLeft;
    NSLayoutConstraint *_containerRight;
    NSLayoutConstraint *_containerBottom;
    UIButton *_leftTopButton;
    UILabel *_topLable;
    UILabel *_bottomLable;
    UILabel *_rightTopLable;
    struct UIEdgeInsets _contentInsets;
}

@property(retain, nonatomic) UILabel *rightTopLable; // @synthesize rightTopLable=_rightTopLable;
@property(retain, nonatomic) UILabel *bottomLable; // @synthesize bottomLable=_bottomLable;
@property(retain, nonatomic) UILabel *topLable; // @synthesize topLable=_topLable;
@property(retain, nonatomic) UIButton *leftTopButton; // @synthesize leftTopButton=_leftTopButton;
@property(retain, nonatomic) NSLayoutConstraint *containerBottom; // @synthesize containerBottom=_containerBottom;
@property(retain, nonatomic) NSLayoutConstraint *containerRight; // @synthesize containerRight=_containerRight;
@property(retain, nonatomic) NSLayoutConstraint *containerLeft; // @synthesize containerLeft=_containerLeft;
@property(retain, nonatomic) NSLayoutConstraint *containerTop; // @synthesize containerTop=_containerTop;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) struct UIEdgeInsets contentInsets; // @synthesize contentInsets=_contentInsets;
- (void).cxx_destruct;
- (void)configWith:(id)arg1 isSelected:(_Bool)arg2;
- (void)prepareForReuse;
- (void)awakeFromNib;

@end

