//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VFSDKBaseViewController.h"

#import "DZNEmptyDataSetDelegate.h"
#import "DZNEmptyDataSetSource.h"
#import "UITextFieldPasswordKeyboardDelegate.h"

@class NSDictionary, NSMutableArray, NSString, UIButton, UITableView, UITextField, VFSDKLoanProductModelV2, VFSDKPayWayModelV2;

@interface VFSDKLoanPayViewController : VFSDKBaseViewController <DZNEmptyDataSetSource, DZNEmptyDataSetDelegate, UITextFieldPasswordKeyboardDelegate>
{
    _Bool selectedAgreement;
    _Bool _isOutsideJump;
    _Bool _needPwd;
    _Bool _isRecomend;
    UIButton *markBtn;
    UIButton *payBtn;
    NSMutableArray *loanPayArr;
    NSMutableArray *loanProductsArr;
    VFSDKLoanProductModelV2 *selectProduct;
    UITextField *passwordTF;
    long long idx;
    NSString *_pageTitle;
    NSString *_payMoney;
    NSString *_actualMoney;
    NSString *_couponMoney;
    NSString *_buzCode;
    NSString *_loanName;
    VFSDKPayWayModelV2 *_payWay;
    NSDictionary *_tradeInfo;
    NSDictionary *_submitInfo;
    NSString *_limitStr;
    NSString *_couponId;
    NSString *_couponPrice;
    UITableView *_tableView;
    NSString *_password;
}

@property(copy, nonatomic) NSString *password; // @synthesize password=_password;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) _Bool isRecomend; // @synthesize isRecomend=_isRecomend;
@property(copy, nonatomic) NSString *couponPrice; // @synthesize couponPrice=_couponPrice;
@property(copy, nonatomic) NSString *couponId; // @synthesize couponId=_couponId;
@property(copy, nonatomic) NSString *limitStr; // @synthesize limitStr=_limitStr;
@property(retain, nonatomic) NSDictionary *submitInfo; // @synthesize submitInfo=_submitInfo;
@property(nonatomic) _Bool needPwd; // @synthesize needPwd=_needPwd;
@property(nonatomic) _Bool isOutsideJump; // @synthesize isOutsideJump=_isOutsideJump;
@property(retain, nonatomic) NSDictionary *tradeInfo; // @synthesize tradeInfo=_tradeInfo;
@property(retain, nonatomic) VFSDKPayWayModelV2 *payWay; // @synthesize payWay=_payWay;
@property(copy, nonatomic) NSString *loanName; // @synthesize loanName=_loanName;
@property(copy, nonatomic) NSString *buzCode; // @synthesize buzCode=_buzCode;
@property(copy, nonatomic) NSString *couponMoney; // @synthesize couponMoney=_couponMoney;
@property(copy, nonatomic) NSString *actualMoney; // @synthesize actualMoney=_actualMoney;
@property(copy, nonatomic) NSString *payMoney; // @synthesize payMoney=_payMoney;
@property(copy, nonatomic) NSString *pageTitle; // @synthesize pageTitle=_pageTitle;
@property(nonatomic) long long idx; // @synthesize idx;
@property(retain, nonatomic) UITextField *passwordTF; // @synthesize passwordTF;
@property(retain, nonatomic) VFSDKLoanProductModelV2 *selectProduct; // @synthesize selectProduct;
@property(retain, nonatomic) NSMutableArray *loanProductsArr; // @synthesize loanProductsArr;
@property(retain, nonatomic) NSMutableArray *loanPayArr; // @synthesize loanPayArr;
@property(nonatomic) _Bool selectedAgreement; // @synthesize selectedAgreement;
@property(retain, nonatomic) UIButton *payBtn; // @synthesize payBtn;
@property(retain, nonatomic) UIButton *markBtn; // @synthesize markBtn;
- (void).cxx_destruct;
- (id)configLoanPayParams;
- (void)textFieldPasswordKeyboardClose;
- (void)textFieldPasswordKeyboardDidFinshed:(id)arg1;
- (void)retryPay;
- (void)hideShadow;
- (void)showShadow;
- (void)pay;
- (void)pay:(id)arg1;
- (void)toSignView:(id)arg1;
- (void)toUserAgreement;
- (void)markBtnTouch:(id)arg1;
- (_Bool)emptyDataSetShouldAllowScroll:(id)arg1;
- (id)descriptionForEmptyDataSet:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)setupInitData;
- (void)sendSmsCaptcha;
- (void)getLoanProducts;
- (void)updateUI;
- (void)setupPasswordTF;
- (void)setupLoanPayArrary;
- (id)addTableFooter;
- (struct CGSize)couponLabelSize:(id)arg1;
- (struct CGSize)actualLabelSize:(id)arg1;
- (id)addTableHeader;
- (void)setupTableView;
- (void)setupStyle;
- (void)clickBackButton:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

