//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VFSDKBaseViewController.h"

@class UIButton;

@interface VFSDKWalletRechargeResultViewController : VFSDKBaseViewController
{
    CDUnknownBlockType _buttonPressed;
    UIButton *_doneBtn;
}

@property(nonatomic) __weak UIButton *doneBtn; // @synthesize doneBtn=_doneBtn;
@property(copy, nonatomic) CDUnknownBlockType buttonPressed; // @synthesize buttonPressed=_buttonPressed;
- (void).cxx_destruct;
- (void)done:(id)arg1;
- (void)clickBackButton:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

