//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VFSDKBaseViewController.h"

@class NSArray, UIButton;

@interface VFSDKTestCashierViewController : VFSDKBaseViewController
{
    NSArray *_fields;
    UIButton *_button;
}

@property(retain, nonatomic) UIButton *button; // @synthesize button=_button;
@property(retain, nonatomic) NSArray *fields; // @synthesize fields=_fields;
- (void).cxx_destruct;
- (id)_vf_stringWithURLEncoding:(id)arg1;
- (void)_btnAction:(id)arg1;
- (void)viewDidLoad;

@end

