//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VFSDKBaseViewController.h"

#import "UITextFieldDelegate.h"

@class NSString, UIButton, UILabel, UITextField, UIView, UIViewController, VFSDKEncryptResult, VFSDKPassWordView;

@interface VFSDKSetPasswordViewController : VFSDKBaseViewController <UITextFieldDelegate>
{
    long long _currentstatus;
    long long _setPassWordType;
    UIViewController *_jumpViewController;
    UILabel *_titleLabel;
    UIView *_passwordBGView;
    UIButton *_nextButton;
    UITextField *_passwordTF;
    UILabel *_tipsLabel;
    VFSDKPassWordView *_passwordView;
    VFSDKEncryptResult *_mEncryptPassWord;
    NSString *_payPassword;
    NSString *_confirmPayPassword;
    NSString *_verifyPassword;
}

@property(copy, nonatomic) NSString *verifyPassword; // @synthesize verifyPassword=_verifyPassword;
@property(copy, nonatomic) NSString *confirmPayPassword; // @synthesize confirmPayPassword=_confirmPayPassword;
@property(copy, nonatomic) NSString *payPassword; // @synthesize payPassword=_payPassword;
@property(retain, nonatomic) VFSDKEncryptResult *mEncryptPassWord; // @synthesize mEncryptPassWord=_mEncryptPassWord;
@property(retain, nonatomic) VFSDKPassWordView *passwordView; // @synthesize passwordView=_passwordView;
@property(nonatomic) __weak UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
@property(nonatomic) __weak UITextField *passwordTF; // @synthesize passwordTF=_passwordTF;
@property(nonatomic) __weak UIButton *nextButton; // @synthesize nextButton=_nextButton;
@property(nonatomic) __weak UIView *passwordBGView; // @synthesize passwordBGView=_passwordBGView;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UIViewController *jumpViewController; // @synthesize jumpViewController=_jumpViewController;
@property(nonatomic) long long setPassWordType; // @synthesize setPassWordType=_setPassWordType;
@property(nonatomic) long long currentstatus; // @synthesize currentstatus=_currentstatus;
- (void).cxx_destruct;
- (void)p_textFieldDidChange:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)p_handleError:(id)arg1;
- (void)p_handleResult:(id)arg1;
- (void)setPayPassWordReuqest;
- (void)applyPayPwdRequest;
- (void)manageResult:(id)arg1;
- (void)nextAction:(id)arg1;
- (void)handlePassWord;
- (void)p_veryfyPassword;
- (long long)setUpPayPassword:(id)arg1;
- (void)p_showPasswordKeyBorad;
- (void)p_setupUI;
- (id)trackablePVPageId;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidFirstAppear;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

