//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface VVConfig : NSObject
{
    _Bool _alwaysRefresh;
    double _pointRatio;
}

+ (void)setAlwaysRefresh:(_Bool)arg1;
+ (_Bool)alwaysRefresh;
+ (void)setPointRatio:(double)arg1;
+ (double)pointRatio;
+ (id)sharedConfig;
@property(nonatomic) _Bool alwaysRefresh; // @synthesize alwaysRefresh=_alwaysRefresh;
@property(nonatomic) double pointRatio; // @synthesize pointRatio=_pointRatio;
- (id)init;

@end

