//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMPopupMaskView.h"

#import "UIScrollViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, UIButton, UIScrollView, UIView, YmmAddressTabbar;

@interface YmmAddressSelecttionView : YMMPopupMaskView <UITableViewDataSource, UITableViewDelegate, UIScrollViewDelegate>
{
    _Bool _hasSelectedRegion;
    CDUnknownBlockType _selectedRegionsBlock;
    long long _provinceCode;
    long long _cityCode;
    long long _areaCode;
    YmmAddressTabbar *_topTabbar;
    UIScrollView *_contentScrollView;
    UIView *_underLine;
    UIButton *_selectedBtn;
    UIView *_containerView;
    NSMutableArray *_dataSouce;
    NSMutableArray *_cityDataSouce;
    NSMutableArray *_districtDataSouce;
    NSMutableArray *_tableViews;
    NSMutableArray *_topTabbarItems;
}

@property(retain, nonatomic) NSMutableArray *topTabbarItems; // @synthesize topTabbarItems=_topTabbarItems;
@property(retain, nonatomic) NSMutableArray *tableViews; // @synthesize tableViews=_tableViews;
@property(retain, nonatomic) NSMutableArray *districtDataSouce; // @synthesize districtDataSouce=_districtDataSouce;
@property(retain, nonatomic) NSMutableArray *cityDataSouce; // @synthesize cityDataSouce=_cityDataSouce;
@property(retain, nonatomic) NSMutableArray *dataSouce; // @synthesize dataSouce=_dataSouce;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak UIButton *selectedBtn; // @synthesize selectedBtn=_selectedBtn;
@property(nonatomic) __weak UIView *underLine; // @synthesize underLine=_underLine;
@property(nonatomic) __weak UIScrollView *contentScrollView; // @synthesize contentScrollView=_contentScrollView;
@property(nonatomic) __weak YmmAddressTabbar *topTabbar; // @synthesize topTabbar=_topTabbar;
@property(nonatomic) _Bool hasSelectedRegion; // @synthesize hasSelectedRegion=_hasSelectedRegion;
@property(nonatomic) long long areaCode; // @synthesize areaCode=_areaCode;
@property(nonatomic) long long cityCode; // @synthesize cityCode=_cityCode;
@property(nonatomic) long long provinceCode; // @synthesize provinceCode=_provinceCode;
@property(copy, nonatomic) CDUnknownBlockType selectedRegionsBlock; // @synthesize selectedRegionsBlock=_selectedRegionsBlock;
- (void).cxx_destruct;
- (void)clearRegionsSelectedStatus:(id)arg1;
- (id)separateLine;
- (void)show;
- (_Bool)isValidRegionCodeWithProvince:(id)arg1 city:(id)arg2 area:(id)arg3;
- (void)scrollToNextItem:(id)arg1;
- (void)removeLastItem;
- (id)addressStringValue:(id)arg1 topRegion:(id)arg2;
- (void)finishSelectAddress:(id)arg1;
- (void)changeUnderLineFrame:(id)arg1;
- (void)topBarItemClick:(id)arg1;
- (void)closeViewAction:(id)arg1;
- (void)reloadLastTableView;
- (id)nodeRegions:(id)arg1;
- (void)setupWithSelectedRegions;
- (void)addTopBarItem;
- (void)addTableView;
- (id)setupSelectionView;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)heightOfContent;
- (id)contentView;
- (id)initWithProvinceCode:(long long)arg1 cityCode:(long long)arg2 areaCode:(long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

