//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YMMAssetModel : NSObject
{
    _Bool _isSelected;
    id <DownscalingProtocol> _asset;
    unsigned long long _type;
}

+ (id)modelWithAsset:(id)arg1 type:(unsigned long long)arg2;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(retain, nonatomic) id <DownscalingProtocol> asset; // @synthesize asset=_asset;
- (void).cxx_destruct;

@end

