//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class NSString;

@interface YMMBaseDataModel : YMMCommonModel
{
    NSString *_curAppTypeName;
    long long _curAppTypeCode;
    NSString *_currentVersion;
}

@property(retain, nonatomic) NSString *currentVersion; // @synthesize currentVersion=_currentVersion;
@property(nonatomic) long long curAppTypeCode; // @synthesize curAppTypeCode=_curAppTypeCode;
@property(retain, nonatomic) NSString *curAppTypeName; // @synthesize curAppTypeName=_curAppTypeName;
- (void).cxx_destruct;

@end

