//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YMMChangeTelNetWorkService : NSObject
{
}

- (void)netWorkTaskForChangeTelSubmit:(id)arg1 requestCallBack:(CDUnknownBlockType)arg2;
- (void)networkTaskForVerifyCode:(id)arg1 requestCallBack:(CDUnknownBlockType)arg2;
- (void)netWorkTaskForVerifyUserInfo:(id)arg1 requestCallBack:(CDUnknownBlockType)arg2;

@end

