//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseMessageCell.h"

@interface YMMCustomMessageCell : YMMBaseMessageCell
{
}

+ (double)cellHeightWithModel:(id)arg1;
+ (id)cellIdentifierWithModel:(id)arg1;
+ (void)initialize;
- (void)updateCustomBubbleViewMargin:(struct UIEdgeInsets)arg1 model:(id)arg2;
- (void)setCustomBubbleView:(id)arg1;
- (void)setCustomModel:(id)arg1;
- (_Bool)isCustomBubbleView:(id)arg1;

@end

