//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class NSNumber, NSString;

@interface YMMChatTopBarBtn : YMMCommonModel
{
    NSString *_type;
    NSString *_content;
    NSString *_url;
    NSNumber *_importance;
}

@property(retain, nonatomic) NSNumber *importance; // @synthesize importance=_importance;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;

@end

