//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YMMConfigureMgr : NSObject
{
    long long _appType;
}

+ (id)sharedYMMConfigureMgr;
+ (id)allocWithZone:(struct _NSZone *)arg1;
@property(nonatomic) long long appType; // @synthesize appType=_appType;
- (id)init;

@end

