//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YMMCloudRenderNetworkService : NSObject
{
}

- (void)networkTaskForDownloadTemplate:(id)arg1 outputUrl:(id)arg2 requestCallBack:(CDUnknownBlockType)arg3;
- (void)networkTaskForAllTemplatesInfo:(id)arg1 requestCallBack:(CDUnknownBlockType)arg2;
- (void)networkTaskForUpdateTemplateInfo:(id)arg1 requestCallBack:(CDUnknownBlockType)arg2;

@end

