//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIImageView, UILabel;

@interface YMMCargoPoolGuideView : UIView
{
    NSString *_title;
    UIImageView *_guideIconView;
    UILabel *_guideLb;
}

+ (double)ymm_heightForCellWithItem:(id)arg1 contentWidth:(double)arg2;
@property(retain, nonatomic) UILabel *guideLb; // @synthesize guideLb=_guideLb;
@property(retain, nonatomic) UIImageView *guideIconView; // @synthesize guideIconView=_guideIconView;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)dealloc;
- (void)initViews;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

