//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableDictionary;

@interface YMMCargoCommentLogic : NSObject
{
    NSMutableDictionary *_commentDict;
    NSArray *_currentGoodTags;
    NSArray *_currentMediumTags;
    NSArray *_currentBadTags;
}

+ (id)sharedCommentLogic;
@property(retain, nonatomic) NSArray *currentBadTags; // @synthesize currentBadTags=_currentBadTags;
@property(retain, nonatomic) NSArray *currentMediumTags; // @synthesize currentMediumTags=_currentMediumTags;
@property(retain, nonatomic) NSArray *currentGoodTags; // @synthesize currentGoodTags=_currentGoodTags;
@property(retain, nonatomic) NSMutableDictionary *commentDict; // @synthesize commentDict=_commentDict;
- (void).cxx_destruct;
- (void)requestPopupComment:(CDUnknownBlockType)arg1;
- (void)requestCommentTags;
- (id)badTags;
- (id)mediumTags;
- (id)goodTags;
- (void)clearData;
- (void)handleTags:(id)arg1;
- (id)convertDictToModel:(id)arg1;
- (_Bool)saveCommentTagsToDisk:(id)arg1;
- (_Bool)isFileExists;
- (id)tagsFilePath;

@end

