//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCargoCommonNetworkTask.h"

@class NSString;

@interface YMMCargoNearbyCountTask : YMMCargoCommonNetworkTask
{
    NSString *_startList;
    NSString *_endList;
    NSString *_truckLengthList;
    NSString *_truckTypeList;
    NSString *_truckLengthInterval;
}

@property(copy, nonatomic) NSString *truckLengthInterval; // @synthesize truckLengthInterval=_truckLengthInterval;
@property(retain, nonatomic) NSString *truckTypeList; // @synthesize truckTypeList=_truckTypeList;
@property(retain, nonatomic) NSString *truckLengthList; // @synthesize truckLengthList=_truckLengthList;
@property(retain, nonatomic) NSString *endList; // @synthesize endList=_endList;
@property(retain, nonatomic) NSString *startList; // @synthesize startList=_startList;
- (void).cxx_destruct;
- (Class)ymm_responseModelClass;
- (id)ymm_networkAPIPath;
- (id)ymm_networkAPIDomain;

@end

