//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "YMMControllerProtocol.h"

@class NSString, NSTimer, UIButton, UITableView, UIView, YMMChangeTelPresenter;

@interface YMMChangeTelStepTwoViewController : YMMBaseViewController <UITableViewDataSource, UITableViewDelegate, YMMControllerProtocol>
{
    NSTimer *_timer;
    NSString *_oldTelephone;
    NSString *_identityCode;
    NSString *_userName;
    UITableView *_tableView;
    UIView *_headerView;
    UIView *_footerView;
    UIView *_bottomLineView;
    UIButton *_changeButton;
    UIButton *_codeButton;
    YMMChangeTelPresenter *_presenter;
    long long _capchaTimeIndex;
}

@property(nonatomic) long long capchaTimeIndex; // @synthesize capchaTimeIndex=_capchaTimeIndex;
@property(retain, nonatomic) YMMChangeTelPresenter *presenter; // @synthesize presenter=_presenter;
@property(retain, nonatomic) UIButton *codeButton; // @synthesize codeButton=_codeButton;
@property(retain, nonatomic) UIButton *changeButton; // @synthesize changeButton=_changeButton;
@property(retain, nonatomic) UIView *bottomLineView; // @synthesize bottomLineView=_bottomLineView;
@property(retain, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(copy, nonatomic) NSString *identityCode; // @synthesize identityCode=_identityCode;
@property(copy, nonatomic) NSString *oldTelephone; // @synthesize oldTelephone=_oldTelephone;
- (void).cxx_destruct;
- (void)pushToNextViewController;
- (void)showSyncUpdateAlertView;
- (void)stopCountDown;
- (void)startCountDown;
- (void)reloadSection:(long long)arg1 row:(long long)arg2;
- (void)stopLoading;
- (void)startLoading;
- (void)commitBtnAction:(id)arg1;
- (void)configUserInputs;
- (void)dissmissKeyboard:(id)arg1;
- (void)addGesture;
- (void)addSubviews;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)ymm_pageName;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

