//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MBBaseModuleViewModel.h"

@class NSString;

@interface YMMDepositTextDisplayViewModel : MBBaseModuleViewModel
{
    NSString *_title;
    NSString *_descValue;
    NSString *_carNumber;
    NSString *_driverName;
}

@property(copy, nonatomic) NSString *driverName; // @synthesize driverName=_driverName;
@property(copy, nonatomic) NSString *carNumber; // @synthesize carNumber=_carNumber;
@property(copy, nonatomic) NSString *descValue; // @synthesize descValue=_descValue;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;

@end

