//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, YMMAppInfoModel, YMMUserInfo;

@interface YMMDataCenter : NSObject
{
    YMMAppInfoModel *_appInfoModel;
    YMMUserInfo *_userInfo;
    long long _networkType;
    NSArray *_appModules;
}

+ (id)sharedYMMDataCenter;
+ (id)allocWithZone:(struct _NSZone *)arg1;
@property(retain, nonatomic) NSArray *appModules; // @synthesize appModules=_appModules;
@property(nonatomic) long long networkType; // @synthesize networkType=_networkType;
@property(retain, nonatomic) YMMUserInfo *userInfo; // @synthesize userInfo=_userInfo;
@property(retain, nonatomic) YMMAppInfoModel *appInfoModel; // @synthesize appInfoModel=_appInfoModel;
- (void).cxx_destruct;
- (_Bool)isLogin;
- (void)login;
- (void)logout;
- (id)init;

@end

