//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MBBaseModuleView.h"

@class MBTextSubview, UIButton;

@interface YMMDepositSelectTextValueComponent : MBBaseModuleView
{
    _Bool _selected;
    UIButton *_checkButton;
    MBTextSubview *_titleView;
    MBTextSubview *_descView;
    UIButton *_descBtn;
}

+ (id)contentTextWithSource:(id)arg1 linkUrl:(id)arg2 linkName:(id)arg3;
+ (double)heightForViewModel:(id)arg1;
@property(nonatomic) _Bool selected; // @synthesize selected=_selected;
@property(retain, nonatomic) UIButton *descBtn; // @synthesize descBtn=_descBtn;
@property(retain, nonatomic) MBTextSubview *descView; // @synthesize descView=_descView;
@property(retain, nonatomic) MBTextSubview *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) UIButton *checkButton; // @synthesize checkButton=_checkButton;
- (void).cxx_destruct;
- (id)componentViewModel;
- (void)descButtonClick:(id)arg1;
- (void)checkButtonClick:(id)arg1;
- (void)refreshView;
- (void)setupContentView;
- (id)init;

@end

