//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DTAttributedLabel.h"

#import "DTAttributedTextContentViewDelegate.h"

@class NSString;

@interface YMMDTAttributedLabel : DTAttributedLabel <DTAttributedTextContentViewDelegate>
{
    CDUnknownBlockType _linkBlock;
}

@property(copy, nonatomic) CDUnknownBlockType linkBlock; // @synthesize linkBlock=_linkBlock;
- (void).cxx_destruct;
- (id)attributedTextContentView:(id)arg1 viewForAttachment:(id)arg2 frame:(struct CGRect)arg3;
- (id)attributedTextContentView:(id)arg1 viewForLink:(id)arg2 identifier:(id)arg3 frame:(struct CGRect)arg4;
- (struct CGSize)variableHeightWidth:(double)arg1;
- (void)linkTapEvent:(id)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)setAttributedString:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

