//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

@interface YMMFebRequestFormModel : NSObject
{
    NSNumber *_taskId;
    NSNumber *_taskType;
    NSNumber *_evaluationState;
    NSNumber *_starLevel;
    NSString *_optionIds;
    NSString *_otherProblem;
}

@property(copy, nonatomic) NSString *otherProblem; // @synthesize otherProblem=_otherProblem;
@property(copy, nonatomic) NSString *optionIds; // @synthesize optionIds=_optionIds;
@property(retain, nonatomic) NSNumber *starLevel; // @synthesize starLevel=_starLevel;
@property(retain, nonatomic) NSNumber *evaluationState; // @synthesize evaluationState=_evaluationState;
@property(retain, nonatomic) NSNumber *taskType; // @synthesize taskType=_taskType;
@property(retain, nonatomic) NSNumber *taskId; // @synthesize taskId=_taskId;
- (void).cxx_destruct;

@end

