//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseViewController.h"

#import "BMKGeoCodeSearchDelegate.h"
#import "BMKLocationServiceDelegate.h"
#import "BMKMapViewDelegate.h"
#import "BMKPoiSearchDelegate.h"
#import "BMKSuggestionSearchDelegate.h"
#import "UISearchBarDelegate.h"
#import "UISearchDisplayDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class BMKGeoCodeSearch, BMKLocationService, BMKMapView, BMKPoiSearch, BMKSuggestionSearch, NSIndexPath, NSMutableArray, NSString, UIButton, UIImageView, UISearchBar, UITableView, YMMLocSearchDisplayController, YMMSharedLocationModel;

@interface YMMIMShareLocViewController : YMMBaseViewController <BMKMapViewDelegate, BMKGeoCodeSearchDelegate, BMKLocationServiceDelegate, BMKPoiSearchDelegate, BMKSuggestionSearchDelegate, UITableViewDataSource, UITableViewDelegate, UISearchBarDelegate, UISearchDisplayDelegate>
{
    _Bool _needReverseGeo;
    CDUnknownBlockType _sharedLocationCallBack;
    BMKMapView *_mapView;
    BMKLocationService *_locService;
    BMKGeoCodeSearch *_geocodesearch;
    BMKSuggestionSearch *_suggestSearcher;
    BMKPoiSearch *_poiSearch;
    UISearchBar *_searchBar;
    UITableView *_tableView;
    NSMutableArray *_dataSource;
    YMMSharedLocationModel *_currSharedModel;
    NSString *_currentCity;
    NSIndexPath *_currIndexPath;
    UIButton *_currLocBtn;
    UIImageView *_selectView;
    YMMLocSearchDisplayController *_searchController;
    UIImageView *_centerCallOutImageView;
}

@property(retain, nonatomic) UIImageView *centerCallOutImageView; // @synthesize centerCallOutImageView=_centerCallOutImageView;
@property(retain, nonatomic) YMMLocSearchDisplayController *searchController; // @synthesize searchController=_searchController;
@property(nonatomic) _Bool needReverseGeo; // @synthesize needReverseGeo=_needReverseGeo;
@property(retain, nonatomic) UIImageView *selectView; // @synthesize selectView=_selectView;
@property(retain, nonatomic) UIButton *currLocBtn; // @synthesize currLocBtn=_currLocBtn;
@property(retain, nonatomic) NSIndexPath *currIndexPath; // @synthesize currIndexPath=_currIndexPath;
@property(retain, nonatomic) NSString *currentCity; // @synthesize currentCity=_currentCity;
@property(retain, nonatomic) YMMSharedLocationModel *currSharedModel; // @synthesize currSharedModel=_currSharedModel;
@property(retain, nonatomic) NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) BMKPoiSearch *poiSearch; // @synthesize poiSearch=_poiSearch;
@property(retain, nonatomic) BMKSuggestionSearch *suggestSearcher; // @synthesize suggestSearcher=_suggestSearcher;
@property(retain, nonatomic) BMKGeoCodeSearch *geocodesearch; // @synthesize geocodesearch=_geocodesearch;
@property(retain, nonatomic) BMKLocationService *locService; // @synthesize locService=_locService;
@property(retain, nonatomic) BMKMapView *mapView; // @synthesize mapView=_mapView;
@property(copy, nonatomic) CDUnknownBlockType sharedLocationCallBack; // @synthesize sharedLocationCallBack=_sharedLocationCallBack;
- (void).cxx_destruct;
- (void)searchDisplayControllerWillEndSearch:(id)arg1;
- (void)searchDisplayControllerWillBeginSearch:(id)arg1;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (_Bool)searchBarShouldEndEditing:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (_Bool)searchBarShouldBeginEditing:(id)arg1;
- (void)onGetPoiDetailResult:(id)arg1 result:(id)arg2 errorCode:(int)arg3;
- (void)onGetPoiResult:(id)arg1 result:(id)arg2 errorCode:(int)arg3;
- (void)onGetSuggestionResult:(id)arg1 result:(id)arg2 errorCode:(int)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)didStopLocatingUser;
- (void)didUpdateBMKUserLocation:(id)arg1;
- (void)onGetReverseGeoCodeResult:(id)arg1 result:(id)arg2 errorCode:(int)arg3;
- (void)mapView:(id)arg1 regionDidChangeAnimated:(_Bool)arg2;
- (void)mapViewDidFinishLoading:(id)arg1;
- (void)startGeocodesearchWithCoordinate:(struct CLLocationCoordinate2D)arg1;
- (void)startLocation;
- (void)configUI;
- (void)initNavBar;
- (void)doBack;
- (void)updateLocationViewDisplayParam;
- (void)sendLocation;
- (void)updateSharedLocation:(id)arg1;
- (id)BMKInfoToSharedLocation:(id)arg1;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

