//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "YMMIMExtendModel.h"

@class NSString;

@interface YMMIMChatCargoInfo : NSObject <YMMIMExtendModel>
{
    NSString *_cargoId;
    NSString *_cargoTitle;
    NSString *_cargoDetail;
    NSString *_depositStaus;
    NSString *_cargoDetailSchema;
    NSString *_commonWord;
}

@property(copy, nonatomic) NSString *commonWord; // @synthesize commonWord=_commonWord;
@property(copy, nonatomic) NSString *cargoDetailSchema; // @synthesize cargoDetailSchema=_cargoDetailSchema;
@property(copy, nonatomic) NSString *depositStaus; // @synthesize depositStaus=_depositStaus;
@property(copy, nonatomic) NSString *cargoDetail; // @synthesize cargoDetail=_cargoDetail;
@property(copy, nonatomic) NSString *cargoTitle; // @synthesize cargoTitle=_cargoTitle;
@property(copy, nonatomic) NSString *cargoId; // @synthesize cargoId=_cargoId;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

