//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMIMBaseCell.h"

@class UIButton, UILabel;

@interface YMMIMChatOrderPupupCell : YMMIMBaseCell
{
    CDUnknownBlockType _sendBlock;
    UILabel *_locationLab;
    UILabel *_statusLab;
    UILabel *_truckInfoLab;
    UILabel *_dealTimeLab;
    UIButton *_sendBtn;
}

+ (double)ymm_heightForCellWithItem:(id)arg1 contentWidth:(double)arg2;
@property(retain, nonatomic) UIButton *sendBtn; // @synthesize sendBtn=_sendBtn;
@property(retain, nonatomic) UILabel *dealTimeLab; // @synthesize dealTimeLab=_dealTimeLab;
@property(retain, nonatomic) UILabel *truckInfoLab; // @synthesize truckInfoLab=_truckInfoLab;
@property(retain, nonatomic) UILabel *statusLab; // @synthesize statusLab=_statusLab;
@property(retain, nonatomic) UILabel *locationLab; // @synthesize locationLab=_locationLab;
@property(copy, nonatomic) CDUnknownBlockType sendBlock; // @synthesize sendBlock=_sendBlock;
- (void).cxx_destruct;
- (void)didClickSend:(id)arg1;
- (void)ymm_configWithItemModel:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

