//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YMMIMUITool : NSObject
{
}

+ (double)scaleH:(double)arg1;
+ (double)scaleW:(double)arg1;
+ (double)scale:(double)arg1;
+ (void)setUITemplateSize:(struct CGSize)arg1;
+ (struct UIEdgeInsets)safeAreaInsetsForDeviceWithNotch;
+ (struct CGSize)screenSizeFor35Inch;
+ (struct CGSize)screenSizeFor40Inch;
+ (struct CGSize)screenSizeFor47Inch;
+ (struct CGSize)screenSizeFor55Inch;
+ (struct CGSize)screenSizeFor58Inch;
+ (struct CGSize)screenSizeFor61Inch;
+ (struct CGSize)screenSizeFor65Inch;
+ (_Bool)is35InchScreen;
+ (_Bool)is40InchScreen;
+ (_Bool)is47InchScreen;
+ (_Bool)is55InchScreen;
+ (_Bool)is58InchScreen;
+ (_Bool)is61InchScreen;
+ (_Bool)is65InchScreen;
+ (_Bool)isNotchedScreen;
+ (_Bool)isSimulator;
+ (id)deviceModel;

@end

