//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class YMMIMJumpCardModel;

@interface YMMIMJumpCardItem : YMMCommonModel
{
    long long _success;
    YMMIMJumpCardModel *_data;
}

@property(retain, nonatomic) YMMIMJumpCardModel *data; // @synthesize data=_data;
@property(nonatomic) long long success; // @synthesize success=_success;
- (void).cxx_destruct;
- (void)setValue:(id)arg1 forKey:(id)arg2;

@end

