//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseTableViewCell.h"

@class UIImageView, UILabel, YMMSharedLocationModel;

@interface YMMMapSearchLocationAddressCell : YMMBaseTableViewCell
{
    _Bool _isCurrentLocation;
    _Bool _disableSelect;
    _Bool _hiddenAllArrow;
    YMMSharedLocationModel *_currentLocationModel;
    UIImageView *_iconImageView;
    UILabel *_nameLabel;
    UILabel *_addressLabel;
    UIImageView *_arrowImgView;
}

+ (double)ymm_heightForCellWithItem:(id)arg1 contentWidth:(double)arg2;
+ (id)createReuseCellForTableView:(id)arg1 withCellIdentifier:(id)arg2;
@property(retain, nonatomic) UIImageView *arrowImgView; // @synthesize arrowImgView=_arrowImgView;
@property(retain, nonatomic) UILabel *addressLabel; // @synthesize addressLabel=_addressLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(nonatomic) _Bool hiddenAllArrow; // @synthesize hiddenAllArrow=_hiddenAllArrow;
@property(nonatomic) _Bool disableSelect; // @synthesize disableSelect=_disableSelect;
@property(retain, nonatomic) YMMSharedLocationModel *currentLocationModel; // @synthesize currentLocationModel=_currentLocationModel;
@property(nonatomic) _Bool isCurrentLocation; // @synthesize isCurrentLocation=_isCurrentLocation;
- (void).cxx_destruct;
- (void)ymm_configWithItemModel:(id)arg1;
- (void)initControls;
- (void)setNeedsUpdateConstraints;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

