//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@interface YMMOrderTypeFactory : YMMCommonModel
{
}

+ (unsigned long long)mapDriverOrderStatusWithSchemStatus:(unsigned long long)arg1;
+ (void)getDriverOrderViewController:(unsigned long long)arg1 orderType:(unsigned long long)arg2 callBack:(CDUnknownBlockType)arg3;
+ (unsigned long long)mapOrderStatusWithSchemStatus:(unsigned long long)arg1;
+ (id)generateSuitableOrderListView:(unsigned long long)arg1 orderType:(unsigned long long)arg2;
+ (void)getOrderViewController:(unsigned long long)arg1 orderType:(unsigned long long)arg2 callBack:(CDUnknownBlockType)arg3;

@end

