//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIButton, UILabel;

@interface YMMPincheNotificationView : UIView
{
    long long _count;
    NSString *_cargoId;
    NSString *_strategy;
    NSString *_title;
    NSString *_fromCity;
    NSString *_toCity;
    NSString *_message;
    UILabel *_tagLabel;
    UILabel *_titleLabel;
    UILabel *_messageLabel;
    UIButton *_messageCountButton;
}

@property(retain, nonatomic) UIButton *messageCountButton; // @synthesize messageCountButton=_messageCountButton;
@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UILabel *tagLabel; // @synthesize tagLabel=_tagLabel;
@property(copy, nonatomic) NSString *message; // @synthesize message=_message;
@property(copy, nonatomic) NSString *toCity; // @synthesize toCity=_toCity;
@property(copy, nonatomic) NSString *fromCity; // @synthesize fromCity=_fromCity;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)clearCarpoolMessage;
- (void)tapCarPoolView;
- (void)tapCarpoolCount;
- (void)updateConstraints;
- (void)setupWithUserInfo:(id)arg1;
- (id)initWithUserInfo:(id)arg1;

@end

