//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMPopupMaskView.h"

@class UILabel;

@interface YMMPointsToastView : YMMPopupMaskView
{
    UILabel *_titleLabel;
    UILabel *_pointLabel;
    UILabel *_otherLabel;
}

@property(retain, nonatomic) UILabel *otherLabel; // @synthesize otherLabel=_otherLabel;
@property(retain, nonatomic) UILabel *pointLabel; // @synthesize pointLabel=_pointLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)ymm_loadView;
- (id)pointLabelAttributText:(id)arg1;
- (void)setPointToastViewFrame;
- (id)initWithAttributedTitle:(id)arg1 pointText:(id)arg2 otherText:(id)arg3;
- (id)initPointsToastView:(id)arg1 pointText:(id)arg2 otherText:(id)arg3;

@end

