//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonNetworkTask.h"

@class NSNumber, NSString;

@interface YMMQuoteChangeTask : YMMCommonNetworkTask
{
    NSNumber *_bargainId;
    NSNumber *_bargainMoney;
    long long _freightCalculationUnit;
    NSNumber *_freightCalculationUnitprice;
    NSString *_freightCalculationUnitCount;
}

@property(copy, nonatomic) NSString *freightCalculationUnitCount; // @synthesize freightCalculationUnitCount=_freightCalculationUnitCount;
@property(retain, nonatomic) NSNumber *freightCalculationUnitprice; // @synthesize freightCalculationUnitprice=_freightCalculationUnitprice;
@property(nonatomic) long long freightCalculationUnit; // @synthesize freightCalculationUnit=_freightCalculationUnit;
@property(retain, nonatomic) NSNumber *bargainMoney; // @synthesize bargainMoney=_bargainMoney;
@property(retain, nonatomic) NSNumber *bargainId; // @synthesize bargainId=_bargainId;
- (void).cxx_destruct;
- (Class)ymm_responseModelClass;
- (id)ymm_networkAPIPath;

@end

