//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMPopupMaskView.h"

@class UIButton, UIImageView;

@interface YMMQuoteListGuideView : YMMPopupMaskView
{
    CDUnknownBlockType _dismissBlock;
    UIImageView *_tipsImageV;
    UIButton *_okButton;
}

@property(retain, nonatomic) UIButton *okButton; // @synthesize okButton=_okButton;
@property(retain, nonatomic) UIImageView *tipsImageV; // @synthesize tipsImageV=_tipsImageV;
@property(copy, nonatomic) CDUnknownBlockType dismissBlock; // @synthesize dismissBlock=_dismissBlock;
- (void).cxx_destruct;
- (void)ymm_loadView;
- (void)okAction;

@end

