//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray;

@interface YMMQuteRealNameAlertBottomView : UIView
{
    double _bottomViewWidth;
    CDUnknownBlockType _autoActionBlock;
    NSMutableArray *_cacheButtons;
    UIView *_topLine;
    NSMutableArray *_separateLines;
}

@property(retain, nonatomic) NSMutableArray *separateLines; // @synthesize separateLines=_separateLines;
@property(retain, nonatomic) UIView *topLine; // @synthesize topLine=_topLine;
@property(retain, nonatomic) NSMutableArray *cacheButtons; // @synthesize cacheButtons=_cacheButtons;
@property(copy, nonatomic) CDUnknownBlockType autoActionBlock; // @synthesize autoActionBlock=_autoActionBlock;
@property(nonatomic) double bottomViewWidth; // @synthesize bottomViewWidth=_bottomViewWidth;
- (void).cxx_destruct;
- (void)autoButtonClick:(id)arg1;
- (void)reloadData:(id)arg1;
- (void)drawSeparateLine:(long long)arg1;
- (void)createAutoButton:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

