//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseModel.h"

@class NSArray, NSMutableArray, NSString;

@interface YMMRegion : YMMBaseModel
{
    YMMRegion *_superior;
    NSArray *_subregions;
    _Bool _isSelected;
    float _lon;
    float _lat;
    NSString *_name;
    NSString *_fullName;
    long long _code;
    long long _superCode;
    long long _level;
    long long _status;
    NSString *_pyName;
    NSMutableArray *_hotSubDistricts;
    NSMutableArray *_hotSubCountries;
}

@property(retain, nonatomic) NSMutableArray *hotSubCountries; // @synthesize hotSubCountries=_hotSubCountries;
@property(retain, nonatomic) NSMutableArray *hotSubDistricts; // @synthesize hotSubDistricts=_hotSubDistricts;
@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(readonly, nonatomic) NSString *pyName; // @synthesize pyName=_pyName;
@property(readonly, nonatomic) float lat; // @synthesize lat=_lat;
@property(readonly, nonatomic) float lon; // @synthesize lon=_lon;
@property(retain, nonatomic) NSArray *subregions; // @synthesize subregions=_subregions;
@property(readonly, nonatomic) long long status; // @synthesize status=_status;
@property(readonly, nonatomic) long long level; // @synthesize level=_level;
@property(readonly, nonatomic) long long superCode; // @synthesize superCode=_superCode;
@property(readonly, nonatomic) long long code; // @synthesize code=_code;
@property(readonly, copy, nonatomic) NSString *fullName; // @synthesize fullName=_fullName;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)getFullRegionName;
- (id)regionName;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) YMMRegion *superior;
@property(readonly, nonatomic) NSArray *pyNames;
@property(readonly, nonatomic) struct CLLocationCoordinate2D coordinate;
@property(readonly, nonatomic) NSArray *specialRegions;
@property(readonly, nonatomic) NSArray *municipalties;
- (id)specialRegionNodeRegions;
- (id)municipaltyNodeRegions;
- (id)municipaltySecondRegions;
- (_Bool)isSpecialRegion;
- (_Bool)isMunicipality;
- (_Bool)isFinal;
- (_Bool)isCity;
- (_Bool)isCounty;
- (_Bool)isDistrict;
- (_Bool)isProvince;
- (id)init;
- (void)setValue:(id)arg1 forKey:(id)arg2;

@end

