//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonNetworkTask.h"

@class NSString;

@interface YMMScreenShotConfigTask : YMMCommonNetworkTask
{
    NSString *_userInfo;
}

@property(copy, nonatomic) NSString *userInfo; // @synthesize userInfo=_userInfo;
- (void).cxx_destruct;
- (_Bool)ymm_needEncryption;
- (Class)ymm_responseModelClass;
- (id)ymm_networkAPIPath;
- (id)ymm_networkAPIDomain;

@end

