//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class NSString;

@interface YMMShareDriverInfo : YMMCommonModel
{
    NSString *_driverName;
    NSString *_phoneNumber;
    NSString *_trunkNo;
    double _truckLength;
    long long _trunkType;
    long long _trunkAge;
    long long _orderCount;
    NSString *_favorableRate;
}

@property(copy, nonatomic) NSString *favorableRate; // @synthesize favorableRate=_favorableRate;
@property(nonatomic) long long orderCount; // @synthesize orderCount=_orderCount;
@property(nonatomic) long long trunkAge; // @synthesize trunkAge=_trunkAge;
@property(nonatomic) long long trunkType; // @synthesize trunkType=_trunkType;
@property(nonatomic) double truckLength; // @synthesize truckLength=_truckLength;
@property(copy, nonatomic) NSString *trunkNo; // @synthesize trunkNo=_trunkNo;
@property(copy, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(copy, nonatomic) NSString *driverName; // @synthesize driverName=_driverName;
- (void).cxx_destruct;
- (id)favorableRateDesc;
- (id)orderCountDesc;
- (id)truckInfo;

@end

