//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"

@class NSArray, NSString, UIButton, UIPickerView;

@interface YMMShortcutAccountView : UIView <UIPickerViewDataSource, UIPickerViewDelegate>
{
    CDUnknownBlockType _selectedAccount;
    UIView *_contentView;
    UIButton *_cancelButton;
    UIButton *_confirmButton;
    UIPickerView *_itemPickView;
    NSArray *_accounts;
    NSArray *_accountNames;
    long long _currentSelectedIndex;
}

+ (void)showWithSelectedAccount:(CDUnknownBlockType)arg1;
@property(nonatomic) long long currentSelectedIndex; // @synthesize currentSelectedIndex=_currentSelectedIndex;
@property(retain, nonatomic) NSArray *accountNames; // @synthesize accountNames=_accountNames;
@property(retain, nonatomic) NSArray *accounts; // @synthesize accounts=_accounts;
@property(retain, nonatomic) UIPickerView *itemPickView; // @synthesize itemPickView=_itemPickView;
@property(retain, nonatomic) UIButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(copy, nonatomic) CDUnknownBlockType selectedAccount; // @synthesize selectedAccount=_selectedAccount;
- (void).cxx_destruct;
- (void)dismiss;
- (void)show;
- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (id)pickerView:(id)arg1 titleForRow:(long long)arg2 forComponent:(long long)arg3;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (void)doConfirmSelected:(id)arg1;
- (void)doCancelSelected:(id)arg1;
- (void)setup;
- (void)configureData;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

