//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class NSString, UIImage;

@interface YMMShareCargoMiniAppModel : YMMCommonModel
{
    NSString *_shareTitle;
    NSString *_shareContent;
    NSString *_cargoId;
    NSString *_cargoInfo;
    NSString *_truckInfo;
    NSString *_name;
    NSString *_sharePageUrl;
    UIImage *_shareImage;
}

@property(retain, nonatomic) UIImage *shareImage; // @synthesize shareImage=_shareImage;
@property(copy, nonatomic) NSString *sharePageUrl; // @synthesize sharePageUrl=_sharePageUrl;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *truckInfo; // @synthesize truckInfo=_truckInfo;
@property(copy, nonatomic) NSString *cargoInfo; // @synthesize cargoInfo=_cargoInfo;
@property(copy, nonatomic) NSString *cargoId; // @synthesize cargoId=_cargoId;
@property(copy, nonatomic) NSString *shareContent; // @synthesize shareContent=_shareContent;
@property(copy, nonatomic) NSString *shareTitle; // @synthesize shareTitle=_shareTitle;
- (void).cxx_destruct;

@end

