//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ACKHelper, YMMBaseLongConnect;

@interface YMMSocketClient : NSObject
{
    id <LongConnectDataDelegate> _delegate;
    YMMBaseLongConnect *_connect;
    ACKHelper *_sessionHelper;
}

+ (id)shared;
@property(retain, nonatomic) ACKHelper *sessionHelper; // @synthesize sessionHelper=_sessionHelper;
@property(retain, nonatomic) YMMBaseLongConnect *connect; // @synthesize connect=_connect;
@property(nonatomic) __weak id <LongConnectDataDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)ymmBaseLongConnectReadData:(id)arg1;
- (void)receiveData:(id)arg1;
- (_Bool)isDisconnected;
@property(readonly, nonatomic) _Bool isConnected;
- (void)disconnect;
- (void)send:(id)arg1;
- (void)connect:(id)arg1;
- (void)dealloc;
- (id)init;

@end

