//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCargoCommonNetworkTask.h"

@class NSNumber;

@interface YMMShipperTodayCargosTask : YMMCargoCommonNetworkTask
{
    NSNumber *_before;
    NSNumber *_after;
    long long _count;
    NSNumber *_userId;
}

@property(retain, nonatomic) NSNumber *userId; // @synthesize userId=_userId;
@property(nonatomic) long long count; // @synthesize count=_count;
@property(retain, nonatomic) NSNumber *after; // @synthesize after=_after;
@property(retain, nonatomic) NSNumber *before; // @synthesize before=_before;
- (void).cxx_destruct;
- (Class)ymm_responseModelClass;
- (id)ymm_networkAPIPath;
- (id)ymm_networkAPIDomain;

@end

