//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIScrollViewDelegate.h"

@class NSArray, NSMutableSet, NSString, UIColor, UIFont, UIScrollView, UIViewController;

@interface YMMTopTabbarView : UIView <UIScrollViewDelegate>
{
    _Bool _hasLayouted;
    NSMutableSet *_apperedContentViewsIndexs;
    _Bool _showBottomLine;
    _Bool _needUpdateContentViewWhenAppear;
    unsigned long long _topBarStyle;
    id <YMMTopTabbarDelegate> _delegate;
    id <YMMTopTabbarDatasource> _dataSource;
    double _topTabbarHight;
    long long _numberOfColumns;
    double _bottomLineHeight;
    UIColor *_bottomlineColor;
    NSArray *_topBarTitles;
    UIFont *_titleFont;
    UIColor *_titleNormalColor;
    UIColor *_titleSelectedColor;
    long long _selectedColumnIndex;
    UIView *_topTabbar;
    UIScrollView *_contentScrollView;
    UIView *_scrollViewContentView;
    NSArray *_contentViewsArray;
    NSArray *_columnItemsArray;
    NSArray *_viewControllersArray;
    UIViewController *_viewController;
}

@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
@property(retain, nonatomic) NSArray *viewControllersArray; // @synthesize viewControllersArray=_viewControllersArray;
@property(retain, nonatomic) NSArray *columnItemsArray; // @synthesize columnItemsArray=_columnItemsArray;
@property(retain, nonatomic) NSArray *contentViewsArray; // @synthesize contentViewsArray=_contentViewsArray;
@property(retain, nonatomic) UIView *scrollViewContentView; // @synthesize scrollViewContentView=_scrollViewContentView;
@property(retain, nonatomic) UIScrollView *contentScrollView; // @synthesize contentScrollView=_contentScrollView;
@property(retain, nonatomic) UIView *topTabbar; // @synthesize topTabbar=_topTabbar;
@property(nonatomic) _Bool needUpdateContentViewWhenAppear; // @synthesize needUpdateContentViewWhenAppear=_needUpdateContentViewWhenAppear;
@property(nonatomic) long long selectedColumnIndex; // @synthesize selectedColumnIndex=_selectedColumnIndex;
@property(retain, nonatomic) UIColor *titleSelectedColor; // @synthesize titleSelectedColor=_titleSelectedColor;
@property(retain, nonatomic) UIColor *titleNormalColor; // @synthesize titleNormalColor=_titleNormalColor;
@property(retain, nonatomic) UIFont *titleFont; // @synthesize titleFont=_titleFont;
@property(retain, nonatomic) NSArray *topBarTitles; // @synthesize topBarTitles=_topBarTitles;
@property(retain, nonatomic) UIColor *bottomlineColor; // @synthesize bottomlineColor=_bottomlineColor;
@property(nonatomic) double bottomLineHeight; // @synthesize bottomLineHeight=_bottomLineHeight;
@property(nonatomic) _Bool showBottomLine; // @synthesize showBottomLine=_showBottomLine;
@property(nonatomic) long long numberOfColumns; // @synthesize numberOfColumns=_numberOfColumns;
@property(nonatomic) double topTabbarHight; // @synthesize topTabbarHight=_topTabbarHight;
@property(nonatomic) __weak id <YMMTopTabbarDatasource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak id <YMMTopTabbarDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) unsigned long long topBarStyle; // @synthesize topBarStyle=_topBarStyle;
- (void).cxx_destruct;
- (void)setSelectedColumnIndex:(long long)arg1 fromIndex:(long long)arg2 needUpdateView:(_Bool)arg3;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)refreshCurrentColumnContentView;
- (void)reloadTopBarData;
- (void)reloadData;
- (void)scrollToColumnAtIndex:(long long)arg1 animated:(_Bool)arg2;
- (id)contentViewAtIndex:(unsigned long long)arg1;
- (id)colomnItemAtIndex:(unsigned long long)arg1;
- (void)_resetColumAtIndex:(long long)arg1 fromIndex:(long long)arg2;
- (void)makeEqualWidthViews:(id)arg1 inView:(id)arg2;
- (void)reSetUpTopBar;
- (void)reSetUpContentView;
- (void)_columnSelected:(id)arg1;
- (id)_createTitleLabelByTitle:(id)arg1;
- (void)_handleTitlesArr;
- (void)confirmDataSource;
- (void)confirmTopBarDatasource;
- (void)layoutSubviews;
- (void)setupViews;
- (id)init;
- (id)initWithtopBarStyle:(unsigned long long)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

