//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel, YMMIMChatWayBillInfo;

@interface YMMToolOrderView : UIView
{
    id <EaseOrderViewDelegate> _delegate;
    YMMIMChatWayBillInfo *_wayBillInfo;
    UILabel *_orderInfoLabel;
}

@property(nonatomic) __weak UILabel *orderInfoLabel; // @synthesize orderInfoLabel=_orderInfoLabel;
@property(retain, nonatomic) YMMIMChatWayBillInfo *wayBillInfo; // @synthesize wayBillInfo=_wayBillInfo;
@property(nonatomic) __weak id <EaseOrderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)closeButtonAction:(id)arg1;
- (void)tapAction:(id)arg1;
- (void)addAllSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

