//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, UITableView, YMMPopoverView, YMMTransactionListModel;

@interface YMMTransactionListViewController : YMMBaseViewController <UITableViewDelegate, UITableViewDataSource>
{
    UITableView *_tableview;
    YMMPopoverView *_popView;
    NSArray *_popActions;
    YMMTransactionListModel *_transactionList;
    long long _accountFlowItemType;
}

@property(nonatomic) long long accountFlowItemType; // @synthesize accountFlowItemType=_accountFlowItemType;
@property(retain, nonatomic) YMMTransactionListModel *transactionList; // @synthesize transactionList=_transactionList;
@property(retain, nonatomic) NSArray *popActions; // @synthesize popActions=_popActions;
@property(retain, nonatomic) YMMPopoverView *popView; // @synthesize popView=_popView;
@property(retain, nonatomic) UITableView *tableview; // @synthesize tableview=_tableview;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)gotoWithdrawStatusViewController:(id)arg1;
- (void)filterAction:(id)arg1;
- (void)setupViews;
- (void)getTransactionListByIsRefresh:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)addRightNavigationItem;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

