//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSNumber, NSString;

@interface YMMUserInfo : NSObject
{
    _Bool _isAllAuthority;
    _Bool _isPilotUser;
    NSDictionary *_ymmTokenInfo;
    NSString *_globalUUID;
    NSString *_ymmUserSession;
    NSString *_ymmUserToken;
    NSString *_ymmUserId;
    NSString *_ymmUserName;
    NSString *_telephone;
    NSString *_accountName;
    NSNumber *_userType;
    NSString *_avatar;
}

@property(nonatomic) _Bool isPilotUser; // @synthesize isPilotUser=_isPilotUser;
@property(nonatomic) _Bool isAllAuthority; // @synthesize isAllAuthority=_isAllAuthority;
@property(retain, nonatomic) NSString *avatar; // @synthesize avatar=_avatar;
@property(retain, nonatomic) NSNumber *userType; // @synthesize userType=_userType;
@property(retain, nonatomic) NSString *accountName; // @synthesize accountName=_accountName;
@property(retain, nonatomic) NSString *telephone; // @synthesize telephone=_telephone;
@property(retain, nonatomic) NSString *ymmUserName; // @synthesize ymmUserName=_ymmUserName;
@property(retain, nonatomic) NSString *ymmUserId; // @synthesize ymmUserId=_ymmUserId;
@property(retain, nonatomic) NSString *ymmUserToken; // @synthesize ymmUserToken=_ymmUserToken;
@property(retain, nonatomic) NSString *ymmUserSession; // @synthesize ymmUserSession=_ymmUserSession;
@property(retain, nonatomic) NSString *globalUUID; // @synthesize globalUUID=_globalUUID;
@property(retain, nonatomic) NSDictionary *ymmTokenInfo; // @synthesize ymmTokenInfo=_ymmTokenInfo;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end

