//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBasicsLog.h"

@class NSNumber, NSString;

@interface YMMViewTouchClickLog : YMMBasicsLog
{
    _Bool _isGesture;
    NSString *_pageLifecycleId;
    NSString *_frameDes;
    NSString *_mark;
    NSNumber *_selectedIndex;
    NSNumber *_swithOn;
    NSString *_alertButtonTitle;
}

+ (id)modelCustomPropertyMapper;
@property(copy, nonatomic) NSString *alertButtonTitle; // @synthesize alertButtonTitle=_alertButtonTitle;
@property(retain, nonatomic) NSNumber *swithOn; // @synthesize swithOn=_swithOn;
@property(retain, nonatomic) NSNumber *selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(nonatomic) _Bool isGesture; // @synthesize isGesture=_isGesture;
@property(copy, nonatomic) NSString *mark; // @synthesize mark=_mark;
@property(copy, nonatomic) NSString *frameDes; // @synthesize frameDes=_frameDes;
@property(copy, nonatomic) NSString *pageLifecycleId; // @synthesize pageLifecycleId=_pageLifecycleId;
- (void).cxx_destruct;
- (id)init;

@end

