//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ZHCardInfo : NSObject
{
    NSString *_cardId;
    NSString *_cardType;
    NSString *_cardVersion;
    NSString *_provider;
    NSString *_signedDate;
    NSString *_expiredDate;
    NSString *_vehicleNumber;
    NSString *_userType;
    NSString *_plateColor;
    NSString *_vehicleMode;
    NSString *_balance;
}

@property(copy, nonatomic) NSString *balance; // @synthesize balance=_balance;
@property(copy, nonatomic) NSString *vehicleMode; // @synthesize vehicleMode=_vehicleMode;
@property(copy, nonatomic) NSString *plateColor; // @synthesize plateColor=_plateColor;
@property(copy, nonatomic) NSString *userType; // @synthesize userType=_userType;
@property(copy, nonatomic) NSString *vehicleNumber; // @synthesize vehicleNumber=_vehicleNumber;
@property(copy, nonatomic) NSString *expiredDate; // @synthesize expiredDate=_expiredDate;
@property(copy, nonatomic) NSString *signedDate; // @synthesize signedDate=_signedDate;
@property(copy, nonatomic) NSString *provider; // @synthesize provider=_provider;
@property(copy, nonatomic) NSString *cardVersion; // @synthesize cardVersion=_cardVersion;
@property(copy, nonatomic) NSString *cardType; // @synthesize cardType=_cardType;
@property(copy, nonatomic) NSString *cardId; // @synthesize cardId=_cardId;
- (void).cxx_destruct;
- (id)description;
- (void)setInfomation:(id)arg1 balance:(id)arg2;

@end

