//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AMapTrackObject.h"

@class NSString;

@interface AMapTrackBaseRequest : AMapTrackObject
{
    NSString *_serviceID;
}

@property(copy, nonatomic) NSString *serviceID; // @synthesize serviceID=_serviceID;
- (void).cxx_destruct;
- (id)init;

@end

