//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AMapNaviTopInfoView;

@protocol AMapNaviTopInfoViewState <NSObject>
- (void)buildConstraints:(AMapNaviTopInfoView *)arg1;
- (void)buildTopInfoView:(AMapNaviTopInfoView *)arg1;
@end

