//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AMapLocationManagerDelegate.h"

@class AMapLocationManager, AMapNetworkManager, AMapTrackTimerGhostManager, CLLocation, NSDate, NSMapTable, NSString, NSTimer;

@interface AMapTrackManager : NSObject <AMapLocationManagerDelegate>
{
    AMapTrackTimerGhostManager *_ghostManager;
    NSTimer *_gatherAndPackTimer;
    _Bool _isGatherAndPack;
    _Bool _isHandlingUploadPointError;
    id <AMapTrackManagerDelegate> _delegate;
    unsigned long long _gatherInterval;
    unsigned long long _packInterval;
    NSString *_serviceID;
    NSString *_terminalID;
    NSString *_trackID;
    long long _timeout;
    AMapLocationManager *_locationManager;
    CLLocation *_latestLocation;
    NSDate *_latestLocTimestamp;
    AMapNetworkManager *_networkManager;
    NSMapTable *_requestOperationMapping;
    unsigned long long _intervalFactor;
    unsigned long long _gatherTime;
    NSString *_trackName;
}

+ (void)registerDelegateSelectors;
+ (void)registerResponseClasses;
+ (SEL)delegateSelectorForRequestClass:(Class)arg1;
+ (Class)responseClassForRequestClass:(Class)arg1;
+ (void)registerDelegateSelector:(SEL)arg1 forRequestClass:(Class)arg2;
+ (void)registerResponseClass:(Class)arg1 forRequestClass:(Class)arg2;
+ (id)responseClassMapping;
+ (id)delegateSelectorMapping;
@property(copy, nonatomic) NSString *trackName; // @synthesize trackName=_trackName;
@property _Bool isHandlingUploadPointError; // @synthesize isHandlingUploadPointError=_isHandlingUploadPointError;
@property(nonatomic) unsigned long long gatherTime; // @synthesize gatherTime=_gatherTime;
@property(nonatomic) unsigned long long intervalFactor; // @synthesize intervalFactor=_intervalFactor;
@property _Bool isGatherAndPack; // @synthesize isGatherAndPack=_isGatherAndPack;
@property(retain, nonatomic) NSMapTable *requestOperationMapping; // @synthesize requestOperationMapping=_requestOperationMapping;
@property(retain, nonatomic) AMapNetworkManager *networkManager; // @synthesize networkManager=_networkManager;
@property(copy, nonatomic) NSDate *latestLocTimestamp; // @synthesize latestLocTimestamp=_latestLocTimestamp;
@property(retain) CLLocation *latestLocation; // @synthesize latestLocation=_latestLocation;
@property(retain, nonatomic) AMapLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(nonatomic) long long timeout; // @synthesize timeout=_timeout;
@property(copy, nonatomic) NSString *trackID; // @synthesize trackID=_trackID;
@property(copy, nonatomic) NSString *terminalID; // @synthesize terminalID=_terminalID;
@property(copy, nonatomic) NSString *serviceID; // @synthesize serviceID=_serviceID;
@property(nonatomic) unsigned long long packInterval; // @synthesize packInterval=_packInterval;
@property(nonatomic) unsigned long long gatherInterval; // @synthesize gatherInterval=_gatherInterval;
@property(nonatomic) __weak id <AMapTrackManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)clearAllOperations;
- (id)removeOperationForRequest:(id)arg1;
- (void)addOperation:(id)arg1 forRequest:(id)arg2;
- (_Bool)containsRequest:(id)arg1;
- (id)operationForRequest:(id)arg1;
- (void)amapLocationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)amapLocationManager:(id)arg1 didUpdateLocation:(id)arg2;
- (void)amapLocationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)performRequestWithReformer:(id)arg1 request:(id)arg2;
- (id)additionalParameters;
- (void)invokeDelegateWithResponse:(id)arg1 request:(id)arg2;
- (void)invokeDelegateWithError:(id)arg1 forRequest:(id)arg2;
- (void)invokeDelegateWithURLError:(id)arg1 forRequest:(id)arg2;
- (void)invokeDelegateWithTrackErrorCode:(long long)arg1 description:(id)arg2;
- (id)errorWithTrackErrorCode:(long long)arg1 description:(id)arg2;
- (void)AMapTrackQueryTrackInfo:(id)arg1;
- (void)AMapTrackQueryTrackHistoryAndDistance:(id)arg1;
- (void)AMapTrackQueryTrackDistance:(id)arg1;
- (void)AMapTrackQueryLastPoint:(id)arg1;
- (void)AMapTrackDeleteTrack:(id)arg1;
- (void)AMapTrackAddTrack:(id)arg1;
- (void)AMapTrackQueryTerminal:(id)arg1;
- (void)AMapTrackUpdateTerminal:(id)arg1;
- (void)AMapTrackDeleteTerminal:(id)arg1;
- (void)AMapTrackAddTerminal:(id)arg1;
- (void)AMapTrackQueryService:(id)arg1;
- (void)AMapTrackAddService:(id)arg1;
@property(readonly, nonatomic) unsigned long long cacheMaxSize;
- (_Bool)setLocalCacheMaxSize:(long long)arg1;
- (long long)errorCodeWithResponseData:(id)arg1;
- (void)handleUploadPointErrorWith:(id)arg1 error:(id)arg2 serviceID:(id)arg3 terminalID:(id)arg4 terminalName:(id)arg5 trackID:(id)arg6 trackName:(id)arg7;
- (void)gatherAndPackTimerAction:(id)arg1;
- (void)resetGatherAndPackFlag;
- (void)stopGatherAndPackTimer;
- (void)startGatherAndPackTimer;
- (void)internalStopGaterAndPack;
- (void)internalStartGatherAndPack;
- (void)stopGaterAndPack;
- (void)startGatherAndPack;
- (void)stopService;
- (void)startServiceWithOptions:(id)arg1;
- (void)changeGatherAndPackTimeInterval:(long long)arg1 packTimeInterval:(long long)arg2;
@property(nonatomic) _Bool allowsBackgroundLocationUpdates;
@property(nonatomic) _Bool pausesLocationUpdatesAutomatically;
@property(nonatomic) double desiredAccuracy;
@property(nonatomic) double distanceFilter;
@property(nonatomic) long long activityType;
- (void)stopCLMLocating;
- (void)startCLMLocating;
- (void)createLocationManager;
- (void)initProperties;
- (void)createTrackManagerWithOptions:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)cancelAllRequests;
- (void)deallocOperation;
- (void)dealloc;
- (id)initWithOptions:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

