//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AMapNaviInfo, AMapNaviLocation, AMapNaviRoute, AMapNaviWalkManager;

@protocol AMapNaviWalkDataRepresentable <NSObject>

@optional
- (void)walkManager:(AMapNaviWalkManager *)arg1 updateNaviLocation:(AMapNaviLocation *)arg2;
- (void)walkManager:(AMapNaviWalkManager *)arg1 updateNaviInfo:(AMapNaviInfo *)arg2;
- (void)walkManager:(AMapNaviWalkManager *)arg1 updateNaviRoute:(AMapNaviRoute *)arg2;
- (void)walkManager:(AMapNaviWalkManager *)arg1 updateNaviRouteID:(long long)arg2;
- (void)walkManager:(AMapNaviWalkManager *)arg1 updateNaviMode:(long long)arg2;
@end

