//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AMapNaviCompositeManager, AMapNaviRoutePlanPOIObj, AMapNaviVehicleInfo, NSArray, NSMutableArray, UIView;

@interface AMapNaviCompositeUserConfig : NSObject
{
    _Bool _isNeedUseMyPosition;
    _Bool _isDirectGPSNavi;
    _Bool _isNeedPresent;
    _Bool _isNeedCompositeManagerCalculateRoute;
    _Bool _isNeedStopNaviWhenNaviDriveVCPop;
    _Bool _isNeedDestoryDriveManagerInstanceWhenDismiss;
    _Bool _isNeedShowConfirmViewWhenStopGPSNavi;
    _Bool _isNotSupportLandscape;
    _Bool _isShowCrossImage;
    _Bool _isShowDrivingStrategyPreferenceView;
    _Bool _isRemoveRoutePolylineWhenArrivedDestination;
    _Bool _isMultiPathsNaviMode;
    AMapNaviRoutePlanPOIObj *_startObj;
    AMapNaviRoutePlanPOIObj *_endObj;
    NSMutableArray *_wayObjs;
    NSArray *_mids;
    long long _theOnlineCarHailingType;
    AMapNaviVehicleInfo *_myVehicleInfo;
    NSArray *_transportationTypes;
    NSMutableArray *_transportationTypeTexts;
    UIView *_naviDriveBottomCustomView;
    UIView *_naviDriveBottomExtraCustomView;
    long long _outterSettedDrivingStrategy;
    AMapNaviCompositeManager *_compositeManager;
}

@property(nonatomic) __weak AMapNaviCompositeManager *compositeManager; // @synthesize compositeManager=_compositeManager;
@property(nonatomic) _Bool isMultiPathsNaviMode; // @synthesize isMultiPathsNaviMode=_isMultiPathsNaviMode;
@property(nonatomic) _Bool isRemoveRoutePolylineWhenArrivedDestination; // @synthesize isRemoveRoutePolylineWhenArrivedDestination=_isRemoveRoutePolylineWhenArrivedDestination;
@property(nonatomic) long long outterSettedDrivingStrategy; // @synthesize outterSettedDrivingStrategy=_outterSettedDrivingStrategy;
@property(nonatomic) _Bool isShowDrivingStrategyPreferenceView; // @synthesize isShowDrivingStrategyPreferenceView=_isShowDrivingStrategyPreferenceView;
@property(nonatomic) _Bool isShowCrossImage; // @synthesize isShowCrossImage=_isShowCrossImage;
@property(retain, nonatomic) UIView *naviDriveBottomExtraCustomView; // @synthesize naviDriveBottomExtraCustomView=_naviDriveBottomExtraCustomView;
@property(retain, nonatomic) UIView *naviDriveBottomCustomView; // @synthesize naviDriveBottomCustomView=_naviDriveBottomCustomView;
@property(nonatomic) _Bool isNotSupportLandscape; // @synthesize isNotSupportLandscape=_isNotSupportLandscape;
@property(nonatomic) _Bool isNeedShowConfirmViewWhenStopGPSNavi; // @synthesize isNeedShowConfirmViewWhenStopGPSNavi=_isNeedShowConfirmViewWhenStopGPSNavi;
@property(nonatomic) _Bool isNeedDestoryDriveManagerInstanceWhenDismiss; // @synthesize isNeedDestoryDriveManagerInstanceWhenDismiss=_isNeedDestoryDriveManagerInstanceWhenDismiss;
@property(nonatomic) _Bool isNeedStopNaviWhenNaviDriveVCPop; // @synthesize isNeedStopNaviWhenNaviDriveVCPop=_isNeedStopNaviWhenNaviDriveVCPop;
@property(nonatomic) _Bool isNeedCompositeManagerCalculateRoute; // @synthesize isNeedCompositeManagerCalculateRoute=_isNeedCompositeManagerCalculateRoute;
@property(retain, nonatomic) NSMutableArray *transportationTypeTexts; // @synthesize transportationTypeTexts=_transportationTypeTexts;
@property(copy, nonatomic) NSArray *transportationTypes; // @synthesize transportationTypes=_transportationTypes;
@property(retain, nonatomic) AMapNaviVehicleInfo *myVehicleInfo; // @synthesize myVehicleInfo=_myVehicleInfo;
@property(nonatomic) _Bool isNeedPresent; // @synthesize isNeedPresent=_isNeedPresent;
@property(nonatomic) long long theOnlineCarHailingType; // @synthesize theOnlineCarHailingType=_theOnlineCarHailingType;
@property(nonatomic) _Bool isDirectGPSNavi; // @synthesize isDirectGPSNavi=_isDirectGPSNavi;
@property(nonatomic) _Bool isNeedUseMyPosition; // @synthesize isNeedUseMyPosition=_isNeedUseMyPosition;
@property(copy, nonatomic) NSArray *mids; // @synthesize mids=_mids;
@property(retain, nonatomic) NSMutableArray *wayObjs; // @synthesize wayObjs=_wayObjs;
@property(retain, nonatomic) AMapNaviRoutePlanPOIObj *endObj; // @synthesize endObj=_endObj;
@property(retain, nonatomic) AMapNaviRoutePlanPOIObj *startObj; // @synthesize startObj=_startObj;
- (void).cxx_destruct;
- (void)handleAfterBatchRequestDone:(id)arg1;
- (id)defaultNameType:(long long)arg1;
- (void)setupTransportationTypes:(id)arg1;
- (_Bool)setOnlineCarHailingType:(long long)arg1;
- (_Bool)setMultipleRouteNaviMode:(_Bool)arg1;
- (void)setRemovePolylineAndVectorlineWhenArrivedDestination:(_Bool)arg1;
- (void)setShowDrivingStrategyPreferenceView:(_Bool)arg1;
- (void)setShowCrossImage:(_Bool)arg1;
- (void)setDriveStrategy:(long long)arg1;
- (void)setSupportOrientationLandscape:(_Bool)arg1;
- (_Bool)addCustomBottomViewToNaviDriveView:(id)arg1;
- (void)addCustomViewToNaviDriveView:(id)arg1;
- (void)setVehicleInfo:(id)arg1;
- (void)setNeedShowConfirmViewWhenStopGPSNavi:(_Bool)arg1;
- (void)setNeedDestoryDriveManagerInstanceWhenDismiss:(_Bool)arg1;
- (void)setNeedStopNaviWhenNaviDriveViewDismiss:(_Bool)arg1;
- (void)setNeedCalculateRouteWhenPresent:(_Bool)arg1;
- (void)setStartNaviDirectly:(_Bool)arg1;
- (void)setThemeType:(long long)arg1;
- (_Bool)setRoutePlanPOIType:(long long)arg1 location:(id)arg2 name:(id)arg3 POIId:(id)arg4;
- (void)configWhenPresent;
- (void)dealloc;
- (id)init;

@end

