//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

#import "UIApplicationDelegate.h"
#import "VFSDKTokenProviderDelegate.h"

@class BMKMapManager, NSDate, NSString, UIWindow;

@interface AppDelegate : UIResponder <VFSDKTokenProviderDelegate, UIApplicationDelegate>
{
    UIWindow *_window;
}

@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (_Bool)applicationHandleOpenURL:(id)arg1;
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)application:(id)arg1 didReceiveLocalNotification:(id)arg2;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)initForAppWindow:(id)arg1;
- (void)getHCBWalletTokenWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)refreshWalletTokenWithCompleteBlock:(CDUnknownBlockType)arg1;
- (void)networkDidChange;
- (void)configureForHCB:(id)arg1;
- (void)setIsRequestingForWalletToken:(_Bool)arg1;
- (_Bool)isRequestingForWalletToken;
@property(copy, nonatomic) NSString *requestingForWalletTokenStatus;
- (void)journalForTerminate;
- (void)addJournalForLaunch;
- (void)journalForAppDidEnterForeground;
- (void)journalForAppDidEnterBackground;
- (void)journalForLaunch;
@property(retain, nonatomic) NSDate *timeToForeground;
- (void)uploadExtensionAPPJournal;
- (void)journalForUsabilityUpdateSessionId;
- (void)reqestForMainTabConfigs;
- (void)setupTTS;
- (void)registerHcbTruckNavi;
- (void)registerIFLy;
- (void)baiduMapSettings;
- (_Bool)ymmHandleApplicationHandleOpenURL:(id)arg1;
- (void)ymmHandleApplication:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (_Bool)ymmHandleApplication:(id)arg1 openURL:(id)arg2 options:(id)arg3;
- (_Bool)ymmHandleApplication:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)ymmHandleApplication:(id)arg1 didReceiveLocalNotification:(id)arg2;
- (void)ymmHandleApplication:(id)arg1 didReceiveRemoteNotification:(id)arg2 fetchCompletionHandler:(CDUnknownBlockType)arg3;
- (void)ymmHandleApplicationDidBecomeActive:(id)arg1;
- (void)ymmHandleApplicationWillEnterForeground:(id)arg1;
- (void)ymmHandleApplicationDidEnterBackground:(id)arg1;
- (void)ymmHandleApplicationWillResignActive:(id)arg1;
- (void)ymmHandleApplication:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)ymmHandleForTerminate:(id)arg1;
- (void)configureForYMM:(id)arg1 didFinishLaunch:(id)arg2;
@property(retain, nonatomic) NSDate *lastRequestMainTabTime;
@property(retain, nonatomic) NSDate *enterBackgroundDate;
@property(retain, nonatomic) BMKMapManager *mapManager;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

