//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YFNetMessageModel.h"

@class BargainNetBaseMessageModel;

@interface BargainNetMessageModel : YFNetMessageModel
{
}

+ (id)messageBodyFromNetModel:(id)arg1 currentUser:(id)arg2 conversationId:(id)arg3 andBodyType:(long long)arg4;
+ (id)modelFromMessage:(id)arg1;
- (id)messageFromNetMessageModel;

// Remaining properties
@property(retain, nonatomic) BargainNetBaseMessageModel *base;

@end

