//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BaseFile : NSObject
{
}

+ (_Bool)AppendData:(id)arg1 toPath:(id)arg2;
+ (void)ClearPath:(id)arg1;
+ (_Bool)RemoveFile:(id)arg1;
+ (_Bool)CreateFile:(id)arg1;
+ (_Bool)CreatePath:(id)arg1;
+ (void)EnsureCreateParentDir:(id)arg1;
+ (_Bool)FileExist:(id)arg1;

@end

