//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSStreamDelegate.h"

@class NSInputStream, NSMutableURLRequest, NSOutputStream, NSString, NSTimer, NSURL, NSURLConnection;

@interface BDS_TTSbds_Chunk_Connection : NSObject <NSStreamDelegate>
{
    struct __CFReadStream *downReadStream;
    struct __CFWriteStream *downWriteStream;
    struct bds_shared_ptr<BDS_TTS::PCMQueue> uploadData;
    struct bds_shared_ptr<BDS_TTS::PCMQueue> downloadData;
    struct bds_shared_ptr<BDS_TTS::PCMQueue> decodedData;
    bds_weak_ptr_7348b3b7 m_callback;
    _Bool _isRunning;
    _Bool _stoppedCallback;
    _Bool _isWriteRequestRunning;
    _Bool _hasStopped;
    _Bool _hasSpace;
    _Bool _isDownloadRequest;
    NSInputStream *_upInputStream;
    NSOutputStream *_upOutputStream;
    NSURLConnection *_connection;
    NSMutableURLRequest *_urlRequest;
    NSTimer *_downTimer;
    char *_buffer;
    unsigned long long _buffer_len;
    long long _curStatus;
    long long _curChunkLen;
    long long _totalUploadData;
    NSURL *_originalURL;
}

@property(retain, nonatomic) NSURL *originalURL; // @synthesize originalURL=_originalURL;
@property(nonatomic) long long totalUploadData; // @synthesize totalUploadData=_totalUploadData;
@property(nonatomic) long long curChunkLen; // @synthesize curChunkLen=_curChunkLen;
@property(nonatomic) long long curStatus; // @synthesize curStatus=_curStatus;
@property(nonatomic) unsigned long long buffer_len; // @synthesize buffer_len=_buffer_len;
@property(nonatomic) char *buffer; // @synthesize buffer=_buffer;
@property(retain, nonatomic) NSTimer *downTimer; // @synthesize downTimer=_downTimer;
@property(retain, nonatomic) NSMutableURLRequest *urlRequest; // @synthesize urlRequest=_urlRequest;
@property(retain, nonatomic) NSURLConnection *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) NSOutputStream *upOutputStream; // @synthesize upOutputStream=_upOutputStream;
@property(retain, nonatomic) NSInputStream *upInputStream; // @synthesize upInputStream=_upInputStream;
@property(nonatomic) _Bool isDownloadRequest; // @synthesize isDownloadRequest=_isDownloadRequest;
@property(nonatomic) _Bool hasSpace; // @synthesize hasSpace=_hasSpace;
@property(nonatomic) _Bool hasStopped; // @synthesize hasStopped=_hasStopped;
@property(nonatomic) _Bool isWriteRequestRunning; // @synthesize isWriteRequestRunning=_isWriteRequestRunning;
@property(nonatomic) _Bool stoppedCallback; // @synthesize stoppedCallback=_stoppedCallback;
@property(nonatomic) _Bool isRunning; // @synthesize isRunning=_isRunning;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)createBoundInputStream:(id *)arg1 outputStream:(id *)arg2 bufferSize:(unsigned long long)arg3;
- (void)httpEventHandler:(bds_shared_ptr_fc3b82c9)arg1;
- (int)httpChunkDecode:(char *)arg1 withLength:(unsigned int)arg2 andOutputData:(char **)arg3 andHttpStatus:(unsigned int *)arg4;
- (void)downTimeoutHandler;
- (void)startDownConnectionWithRequest:(id)arg1 andOriginalURL:(id)arg2 andCallback:(bds_weak_ptr_7348b3b7 *)arg3;
- (void)connection:(id)arg1 willSendRequestForAuthenticationChallenge:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didSendBodyData:(long long)arg2 totalBytesWritten:(long long)arg3 totalBytesExpectedToWrite:(long long)arg4;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)stream:(id)arg1 handleEvent:(unsigned long long)arg2;
- (void)sendData:(bds_shared_ptr_1584cfbf *)arg1 length:(long long)arg2 isLast:(_Bool)arg3;
- (void)startUpConnectionWithRequest:(id)arg1 andOriginalURL:(id)arg2 andCallback:(bds_weak_ptr_7348b3b7 *)arg3;
- (void)clearDownload;
- (void)clearUpload;
- (void)markForClearup;
- (void)cancelConnection;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

