//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "Decoder.h"
#import "NSCopying.h"

@class NSMutableDictionary, NSString;

@interface Decoder : NSObject <Decoder, NSCopying>
{
    NSMutableDictionary *__mappings;
    NSString *_rootPath;
}

@property(copy, nonatomic) NSString *rootPath; // @synthesize rootPath=_rootPath;
- (void).cxx_destruct;
- (id)decode:(id)arg1 withClass:(Class)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)append:(id)arg1;
- (id)initWithAttributes:(id)arg1;
- (id)initWithMappings:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

