//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, YMMChatWordsView;

@protocol EaseWordsViewDelegate <NSObject>
- (void)didClickEditWithView:(YMMChatWordsView *)arg1;
- (void)endAddWords;
- (void)beginAddWords;
- (void)commonWordsDidClickAddWithView:(YMMChatWordsView *)arg1 content:(NSString *)arg2;
- (void)wordsViewClickIndex:(long long)arg1 wordsArray:(NSArray *)arg2;
@end

