//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, UILabel, UIView, YMMGTSearchDriverModel;

@interface GTCollecVerifyImageContainerCell : UITableViewCell
{
    UILabel *_topTitleLabel;
    UIButton *_addImageButton;
    UIView *_imageContainerView;
    long long _maxImageSelectNumber;
    CDUnknownBlockType _clickAddButtonBlock;
    YMMGTSearchDriverModel *_cellDriverModel;
}

@property(retain, nonatomic) YMMGTSearchDriverModel *cellDriverModel; // @synthesize cellDriverModel=_cellDriverModel;
@property(copy, nonatomic) CDUnknownBlockType clickAddButtonBlock; // @synthesize clickAddButtonBlock=_clickAddButtonBlock;
@property(nonatomic) long long maxImageSelectNumber; // @synthesize maxImageSelectNumber=_maxImageSelectNumber;
@property(retain, nonatomic) UIView *imageContainerView; // @synthesize imageContainerView=_imageContainerView;
@property(retain, nonatomic) UIButton *addImageButton; // @synthesize addImageButton=_addImageButton;
@property(retain, nonatomic) UILabel *topTitleLabel; // @synthesize topTitleLabel=_topTitleLabel;
- (void).cxx_destruct;
- (void)deleteImageAction:(id)arg1;
- (void)loadImageContainer;
- (void)addImageAction:(id)arg1;
- (void)reloadCellData:(id)arg1;
- (void)addConstraint;
- (void)dealloc;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

