//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GTPaySDKProtocol.h"
#import "YMMWebViewDelegate.h"

@class NSObject<OS_dispatch_source>, NSString, UIViewController, YMMPayOrderInfoModel, YMMWebView;

@interface GTH5WXPaySDK : NSObject <YMMWebViewDelegate, GTPaySDKProtocol>
{
    CDUnknownBlockType resultCallBack;
    YMMPayOrderInfoModel *_orderInfo;
    UIViewController *_parentVc;
    NSString *_YBChannelName;
    NSObject<OS_dispatch_source> *_checkTimer;
    UIViewController *_schemeVC;
    YMMWebView *_webView;
}

@property(retain, nonatomic) YMMWebView *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) UIViewController *schemeVC; // @synthesize schemeVC=_schemeVC;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *checkTimer; // @synthesize checkTimer=_checkTimer;
@property(retain, nonatomic) NSString *YBChannelName; // @synthesize YBChannelName=_YBChannelName;
@property(nonatomic) __weak UIViewController *parentVc; // @synthesize parentVc=_parentVc;
@property(retain, nonatomic) YMMPayOrderInfoModel *orderInfo; // @synthesize orderInfo=_orderInfo;
@property(copy, nonatomic) CDUnknownBlockType resultCallBack; // @synthesize resultCallBack;
- (void).cxx_destruct;
- (void)installWx;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (void)doubleCheckOrderStatus;
- (void)scheduledDoubleCheckYBOrderStatus;
- (void)cancelCheckYBOrderStatusTimer;
- (void)listen;
- (void)H5WechatPaynotification:(id)arg1;
- (void)dealloc;
- (void)sendOrder:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)alipayNotificationRegister;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

