//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIColor, YYLabel;

@interface GTInsuranceBuyTextView : UIView
{
    long long _fontSize;
    UIColor *_textColor;
    NSString *_textContent;
    YYLabel *_titleLabel;
}

@property(retain, nonatomic) YYLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(copy, nonatomic) NSString *textContent; // @synthesize textContent=_textContent;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(nonatomic) long long fontSize; // @synthesize fontSize=_fontSize;
- (void).cxx_destruct;
- (void)textLinkSchemeRouter:(id)arg1;
- (void)setupContentView;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

