//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GTPayJournal : NSObject
{
}

+ (void)openPayCenterJournalWithTradeType:(id)arg1 OrderId:(id)arg2;
+ (void)openBalancePayJournal:(long long)arg1 Msg:(id)arg2 TradeType:(id)arg3 OrderId:(id)arg4;
+ (void)openPrePayForNativeJournal:(long long)arg1 Msg:(id)arg2 OrderInfo:(id)arg3 PayChannelType:(long long)arg4 PayChannelId:(long long)arg5;
+ (void)openGetPayChannelJournal:(long long)arg1 Msg:(id)arg2 OrderInfo:(id)arg3;
+ (void)openPaySDKResultJournal:(long long)arg1 Msg:(id)arg2 WithOrderInfo:(id)arg3 PayChannelType:(long long)arg4 PayChannelId:(long long)arg5;

@end

