//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class GTImageView, GTShareLuckMoneyContext, UIButton;

@interface GTShareLuckMoneyMiniView : UIView
{
    GTImageView *_imageView;
    UIButton *_imageButton;
    GTShareLuckMoneyContext *_context;
}

@property(retain, nonatomic) GTShareLuckMoneyContext *context; // @synthesize context=_context;
@property(retain, nonatomic) UIButton *imageButton; // @synthesize imageButton=_imageButton;
@property(retain, nonatomic) GTImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)showView;
- (void)touchSubmit;
- (id)initWithContext:(id)arg1;

@end

