//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "HCBLoanAddressPickerDelegate.h"
#import "UITextFieldDelegate.h"

@class HCBLoanAddressPicker, NSString, UIButton, UILabel, UITextField, UITextView;

@interface HCBLoanPPCustomerInfoAddressCell : UITableViewCell <HCBLoanAddressPickerDelegate, UITextFieldDelegate>
{
    UILabel *_titleLabel;
    UILabel *_regionLabel;
    UILabel *_detailPlaceholderLabel;
    UITextView *_detailTextView;
    UIButton *_regionButton;
    CDUnknownBlockType _regionDidChanged;
    CDUnknownBlockType _textViewTextDidChanged;
    UITextField *_field;
    HCBLoanAddressPicker *_addressPicker;
}

@property(retain, nonatomic) HCBLoanAddressPicker *addressPicker; // @synthesize addressPicker=_addressPicker;
@property(nonatomic) __weak UITextField *field; // @synthesize field=_field;
@property(copy, nonatomic) CDUnknownBlockType textViewTextDidChanged; // @synthesize textViewTextDidChanged=_textViewTextDidChanged;
@property(copy, nonatomic) CDUnknownBlockType regionDidChanged; // @synthesize regionDidChanged=_regionDidChanged;
@property(nonatomic) __weak UIButton *regionButton; // @synthesize regionButton=_regionButton;
@property(nonatomic) __weak UITextView *detailTextView; // @synthesize detailTextView=_detailTextView;
@property(nonatomic) __weak UILabel *detailPlaceholderLabel; // @synthesize detailPlaceholderLabel=_detailPlaceholderLabel;
@property(nonatomic) __weak UILabel *regionLabel; // @synthesize regionLabel=_regionLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)addressPicker:(id)arg1 didSelectedAddress:(id)arg2;
- (void)addressPickerDidCanceled:(id)arg1;
- (void)_textViewTextDidChanged:(id)arg1;
- (void)_regionButtonDidPressed:(id)arg1;
- (void)awakeFromNib;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

