//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HCBLoanBaseViewController.h"

#import "HCBLoanFillMultiTextCellDelegate.h"
#import "HCBLoanFillPickerCellDelegate.h"
#import "HCBLoanFillTextCellDelegate.h"

@class NSDictionary, NSMutableArray, NSString, UITableView;

@interface HCBLoanFillPersonalInfoViewController : HCBLoanBaseViewController <HCBLoanFillTextCellDelegate, HCBLoanFillPickerCellDelegate, HCBLoanFillMultiTextCellDelegate>
{
    NSMutableArray *personalInfo;
    NSDictionary *loanPickItems;
    NSString *_phone;
    UITableView *_tableView;
}

@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(copy, nonatomic) NSString *phone; // @synthesize phone=_phone;
@property(retain, nonatomic) NSDictionary *loanPickItems; // @synthesize loanPickItems;
@property(retain, nonatomic) NSMutableArray *personalInfo; // @synthesize personalInfo;
- (void).cxx_destruct;
- (void)toFillOtherInfo;
- (_Bool)checkValue;
- (void)saveMultiText:(id)arg1;
- (void)savePickerInfo:(id)arg1 key:(id)arg2;
- (void)saveInputInfo:(long long)arg1 withContent:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)configMultiTextCell:(id)arg1 atIndexPath:(id)arg2;
- (id)configPickCell:(id)arg1 atIndexPath:(id)arg2;
- (id)configTextCell:(id)arg1 atIndexPath:(id)arg2;
- (id)addTableFooter;
- (id)addHeader;
- (void)setupTableView;
- (void)setupPersonalInfoArrary;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

