//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel, UIView;

@interface HCBLoanCLNewDayProductCell : UITableViewCell
{
    UIImageView *_selectIV;
    UILabel *_productNameLabel;
    UILabel *_feeLabel;
    UILabel *_repayDayLabel;
    UIImageView *_maskView;
    UILabel *_couponLabel;
    UIView *_boxView;
}

@property(nonatomic) __weak UIView *boxView; // @synthesize boxView=_boxView;
@property(nonatomic) __weak UILabel *couponLabel; // @synthesize couponLabel=_couponLabel;
@property(nonatomic) __weak UIImageView *maskView; // @synthesize maskView=_maskView;
@property(nonatomic) __weak UILabel *repayDayLabel; // @synthesize repayDayLabel=_repayDayLabel;
@property(nonatomic) __weak UILabel *feeLabel; // @synthesize feeLabel=_feeLabel;
@property(nonatomic) __weak UILabel *productNameLabel; // @synthesize productNameLabel=_productNameLabel;
@property(nonatomic) __weak UIImageView *selectIV; // @synthesize selectIV=_selectIV;
- (void).cxx_destruct;
- (id)structuralString:(id)arg1 location:(long long)arg2 length:(long long)arg3;
- (void)updateCellWithProduct:(id)arg1 select:(_Bool)arg2;
- (void)awakeFromNib;

@end

