//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "UITextFieldDelegate.h"

@class NSString, UILabel, UITextField;

@interface HCBLoanReadAddressBookTableViewCell : UITableViewCell <UITextFieldDelegate>
{
    id <HCBLoanReadAddressBookTableViewCellDelegate> _delegate;
    UILabel *_titleLabel;
    UITextField *_contentTextField;
}

@property(nonatomic) __weak UITextField *contentTextField; // @synthesize contentTextField=_contentTextField;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak id <HCBLoanReadAddressBookTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updateCell:(id)arg1;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

