//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface HCBMonitorData : NSObject
{
    id _object;
}

+ (id)dataWithObject:(id)arg1;
@property(readonly, nonatomic) id object; // @synthesize object=_object;
- (void).cxx_destruct;
- (id)initWithObject:(id)arg1;
- (id)data;
- (id)JSONString;
- (id)JSON;

@end

