//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HCBMonitorDataUploader.h"

@class NSDictionary;

@interface HCBMonitorDataUploaderKepler : HCBMonitorDataUploader
{
    NSDictionary *_keplerHostMap;
}

- (void).cxx_destruct;
- (id)env_str:(unsigned long long)arg1;
- (id)keplerHostMap;
- (id)keplerBaseURL;
- (Class)configurationClass;
- (id)request:(id)arg1 body:(id)arg2;

@end

