//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface HCBNavUrlComponents : NSObject
{
    NSString *_urlString;
    NSString *_scheme;
    NSString *_host;
    NSString *_path;
    NSString *_query;
    NSDictionary *_queryComponents;
}

+ (id)componentsWithURL:(id)arg1;
@property(copy, nonatomic) NSDictionary *queryComponents; // @synthesize queryComponents=_queryComponents;
@property(copy, nonatomic) NSString *query; // @synthesize query=_query;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
@property(copy, nonatomic) NSString *host; // @synthesize host=_host;
@property(copy, nonatomic) NSString *scheme; // @synthesize scheme=_scheme;
@property(copy, nonatomic) NSString *urlString; // @synthesize urlString=_urlString;
- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *appliedQuery;

@end

