//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class HCBLabel, NSString, UIButton, UIImageView;

@interface HCBNoticeBar : UIView
{
    _Bool _needClose;
    NSString *_content;
    CDUnknownBlockType _closeBlock;
    UIButton *_closeButton;
    UIImageView *_iconView;
    HCBLabel *_contentLabel;
    long long _barStyle;
}

@property(nonatomic) _Bool needClose; // @synthesize needClose=_needClose;
@property(nonatomic) long long barStyle; // @synthesize barStyle=_barStyle;
@property(retain, nonatomic) HCBLabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(copy, nonatomic) CDUnknownBlockType closeBlock; // @synthesize closeBlock=_closeBlock;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
- (void).cxx_destruct;
- (void)closeAction:(id)arg1;
- (void)setupIconView:(id)arg1;
- (void)setupContentLabel:(id)arg1 showIcon:(_Bool)arg2;
- (void)setupCloseButton:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 style:(long long)arg2 needClose:(_Bool)arg3;

@end

