//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIWebView;

@interface HCBWebViewSDK_UserAgent : NSObject
{
    UIWebView *_webView;
}

+ (id)userAgentAppendingString;
+ (void)changeWebViewUserAgent;
+ (void)setupWithClientType:(unsigned long long)arg1 appUserDomainId:(int)arg2;
+ (id)sharedSDK;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
- (void).cxx_destruct;

@end

