//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol KeyboardAccessoryViewDelegate <NSObject>
- (void)didTapConfirmText:(NSString *)arg1 withTipTextType:(unsigned long long)arg2 withIsRefund:(_Bool)arg3;
@end

