//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface LKDBUtils : NSObject
{
}

+ (id)numberFormatter;
+ (id)dateWithString:(id)arg1;
+ (id)stringWithDate:(id)arg1;
+ (id)getDBDateFormat;
+ (id)getTrimStringWithString:(id)arg1;
+ (_Bool)checkStringIsEmpty:(id)arg1;
+ (id)getFilenamesWithDir:(id)arg1;
+ (_Bool)deleteWithFilepath:(id)arg1;
+ (_Bool)isFileExists:(id)arg1;
+ (id)getPathForDocuments:(id)arg1 inDir:(id)arg2;
+ (id)getPathForDocuments:(id)arg1;
+ (id)getDirectoryForDocuments:(id)arg1;
+ (id)getDocumentPath;
+ (_Bool)createDirectoryWithFilePath:(id)arg1;

@end

