//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface LogInfo : NSObject
{
    int _line;
    unsigned long long _level;
    const char *_module;
    const char *_func;
    NSString *_log;
    unsigned long long _cryptType;
}

@property(nonatomic) unsigned long long cryptType; // @synthesize cryptType=_cryptType;
@property(retain, nonatomic) NSString *log; // @synthesize log=_log;
@property(nonatomic) int line; // @synthesize line=_line;
@property(nonatomic) const char *func; // @synthesize func=_func;
@property(nonatomic) const char *module; // @synthesize module=_module;
@property(nonatomic) unsigned long long level; // @synthesize level=_level;
- (void).cxx_destruct;

@end

