//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MBBaseModuleView.h"

@class UIButton, UILabel;

@interface MBSelectTextValueComponent : MBBaseModuleView
{
    _Bool _selected;
    UIButton *_checkButton;
    UILabel *_titleLabel;
    UILabel *_descLabel;
}

+ (double)heightForViewModel:(id)arg1;
@property(nonatomic) _Bool selected; // @synthesize selected=_selected;
@property(retain, nonatomic) UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIButton *checkButton; // @synthesize checkButton=_checkButton;
- (void).cxx_destruct;
- (id)componentViewModel;
- (void)checkButtonClick:(id)arg1;
- (void)refreshView;
- (void)setupContentView;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)init;

@end

