//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (Encrypt)
- (id)decryptedDataByAES128WithKey:(id)arg1;
- (id)encryptedDataByAES128WithKey:(id)arg1;
- (id)decryptedDataBy3DESWithKey:(id)arg1;
- (id)encryptedDataBy3DESWithKey:(id)arg1;
- (id)decryptedDataByDESWithKey:(id)arg1;
- (id)encryptedDataByDESWithKey:(id)arg1;
@end

