//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

@interface NSDictionary (DTError)
+ (id)dictionaryWithContentsOfData:(id)arg1 error:(id *)arg2;
+ (id)dictionaryWithContentsOfFile:(id)arg1 error:(id *)arg2;
+ (id)dictionaryWithContentsOfURL:(id)arg1 error:(id *)arg2;
@end

