//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (NullOperate)
+ (id)stringConvertNotEmpty:(id)arg1;
+ (id)nullToString;
+ (id)stringToString:(id)arg1;
+ (id)nullArr:(id)arg1;
+ (id)changeType:(id)arg1;
+ (id)nullDic:(id)arg1;
- (_Bool)ymmim_isValidStringAndNotEmpty:(id)arg1;
- (_Bool)ymmim_isValidString:(id)arg1;
@end

