//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class UIImageView, UILabel;

@interface PPIPayUnionPayViews : UIControl
{
    UIImageView *imageView;
    UILabel *labelName;
}

- (void).cxx_destruct;
- (void)initView;
- (void)setLableName:(id)arg1;
- (void)setImageView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

