//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class NSString;

@interface PublishFreightModel : YMMCommonModel
{
    NSString *_suggestPriceValue;
    NSString *_priceValue;
    unsigned long long _dealModel;
}

@property(nonatomic) unsigned long long dealModel; // @synthesize dealModel=_dealModel;
@property(retain, nonatomic) NSString *priceValue; // @synthesize priceValue=_priceValue;
@property(retain, nonatomic) NSString *suggestPriceValue; // @synthesize suggestPriceValue=_suggestPriceValue;
- (void).cxx_destruct;

@end

