//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewHeaderFooterView.h"

@class UIImageView, UILabel;

@interface SectionHeaderView : UITableViewHeaderFooterView
{
    _Bool _isShowed;
    id <SectionHeaderViewDelegate> _delegate;
    UILabel *_seperatroLine;
    UILabel *_titleLabel;
    UIImageView *_arrowIndicatorImageView;
}

@property(retain, nonatomic) UIImageView *arrowIndicatorImageView; // @synthesize arrowIndicatorImageView=_arrowIndicatorImageView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UILabel *seperatroLine; // @synthesize seperatroLine=_seperatroLine;
@property(nonatomic) __weak id <SectionHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool isShowed; // @synthesize isShowed=_isShowed;
- (void).cxx_destruct;
- (void)tapGestureHandle:(id)arg1;
- (void)setupGestureRecognizer;
- (void)setupConstraints;
- (id)initWithReuseIdentifier:(id)arg1;

@end

