//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseViewController.h"

#import "UISearchBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSDictionary, NSMutableArray, NSMutableDictionary, NSString, SHAddressBookFooterView, UISearchBar, UITableView, YMMNoDataView, YMMTruckAddressBookTipView, YMMTruckFilterAddressBookModel;

@interface SHAddressBookViewController : YMMBaseViewController <UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate>
{
    long long selectNumber;
    _Bool isSearch;
    _Bool _closeTip;
    YMMTruckFilterAddressBookModel *_model;
    YMMTruckAddressBookTipView *_tipView;
    UITableView *_tableView;
    SHAddressBookFooterView *_footerView;
    UISearchBar *_searchBar;
    NSDictionary *_personDic;
    NSMutableArray *_sectionArray;
    NSMutableDictionary *_showPersonDic;
    NSMutableArray *_showSectionArray;
    YMMNoDataView *_noDataview;
}

@property(nonatomic) _Bool closeTip; // @synthesize closeTip=_closeTip;
@property(retain, nonatomic) YMMNoDataView *noDataview; // @synthesize noDataview=_noDataview;
@property(retain, nonatomic) NSMutableArray *showSectionArray; // @synthesize showSectionArray=_showSectionArray;
@property(retain, nonatomic) NSMutableDictionary *showPersonDic; // @synthesize showPersonDic=_showPersonDic;
@property(retain, nonatomic) NSMutableArray *sectionArray; // @synthesize sectionArray=_sectionArray;
@property(retain, nonatomic) NSDictionary *personDic; // @synthesize personDic=_personDic;
@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) SHAddressBookFooterView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) YMMTruckAddressBookTipView *tipView; // @synthesize tipView=_tipView;
@property(retain, nonatomic) YMMTruckFilterAddressBookModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)addPerson;
- (void)selectAllPerson:(_Bool)arg1;
- (void)searchFor:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)reloadView;
- (void)personsSoft:(id)arg1;
- (void)getFilterPersionArrayForAllPersion:(id)arg1 FilterTelephoneList:(id)arg2;
- (id)addressBookTelephoneList:(id)arg1;
- (void)requestFilterAddressBook:(id)arg1;
- (void)addressBooks;
- (void)closeTipView;
- (void)hideKeyboard;
- (void)didReceiveMemoryWarning;
- (void)updateViewMasnory;
- (void)updateViewConstraints;
- (void)initUI;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

