//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMPublishCommonNetworkTask.h"

@class NSNumber;

@interface SHAddDriverPriceTask : YMMPublishCommonNetworkTask
{
    int _addToMyCar;
    NSNumber *_driverUserId;
    NSNumber *_price;
    NSNumber *_messageId;
}

@property(nonatomic) int addToMyCar; // @synthesize addToMyCar=_addToMyCar;
@property(retain, nonatomic) NSNumber *messageId; // @synthesize messageId=_messageId;
@property(retain, nonatomic) NSNumber *price; // @synthesize price=_price;
@property(retain, nonatomic) NSNumber *driverUserId; // @synthesize driverUserId=_driverUserId;
- (void).cxx_destruct;
- (Class)ymm_responseModelClass;
- (id)ymm_networkAPIPath;

@end

