//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface SHDesignateDriverViewModel : NSObject
{
    NSMutableArray *_listHandle;
}

+ (id)searchDriver:(id)arg1 actionButton:(id)arg2;
+ (_Bool)isHasDedignateDriver:(unsigned long long)arg1 upStreamOrderId:(id)arg2;
@property(retain, nonatomic) NSMutableArray *listHandle; // @synthesize listHandle=_listHandle;
- (void).cxx_destruct;
- (void)handleDesignateDriverData:(id)arg1 cargoType:(long long)arg2 cargoId:(id)arg3 handle:(CDUnknownBlockType)arg4;
- (id)handleList:(id)arg1;
- (id)pictureFullUrlString:(id)arg1;
- (void)listLoadDataCargoType:(long long)arg1 cargoId:(id)arg2 successBack:(CDUnknownBlockType)arg3 error:(CDUnknownBlockType)arg4;
- (void)listLoadMoreCargoType:(long long)arg1 cargoId:(id)arg2 successBack:(CDUnknownBlockType)arg3 error:(CDUnknownBlockType)arg4;

@end

