//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SKY_Store : NSObject
{
}

+ (_Bool)boolForKey:(id)arg1;
+ (void)storeBool:(_Bool)arg1 forKey:(id)arg2;
+ (id)dictForKey:(id)arg1;
+ (void)removeObjForKey:(id)arg1;
+ (id)objForKey:(id)arg1;
+ (void)storeObj:(id)arg1 forKey:(id)arg2;

@end

