//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TimerTarget : NSObject
{
    id _realTarget;
}

@property(nonatomic) __weak id realTarget; // @synthesize realTarget=_realTarget;
- (void).cxx_destruct;
- (void)animationFade;

@end

