//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseTableViewCell.h"

@class UIButton, UILabel, UIView;

@interface TMMDriverDetailTransactionCell : YMMBaseTableViewCell
{
    UILabel *_destinationLb;
    UILabel *_timeLb;
    UILabel *_cargoInfoLb;
    UIButton *_favrateBtn;
    UIView *_line;
}

+ (double)ymm_heightForCellWithItem:(id)arg1 contentWidth:(double)arg2;
@property(retain, nonatomic) UIView *line; // @synthesize line=_line;
@property(retain, nonatomic) UIButton *favrateBtn; // @synthesize favrateBtn=_favrateBtn;
@property(retain, nonatomic) UILabel *cargoInfoLb; // @synthesize cargoInfoLb=_cargoInfoLb;
@property(retain, nonatomic) UILabel *timeLb; // @synthesize timeLb=_timeLb;
@property(retain, nonatomic) UILabel *destinationLb; // @synthesize destinationLb=_destinationLb;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)ymm_configWithItemModel:(id)arg1;
- (void)initUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

