//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (HCBTruckNavi)
+ (id)createImageWithColor:(id)arg1;
+ (id)truckNavi_bundleImageNamed:(id)arg1;
- (id)truck_stretchLeftAndRightWithContainerSize:(struct CGSize)arg1;
- (id)scaledToSize:(struct CGSize)arg1;
@end

