//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

@interface UINavigationController (Consistent)
+ (void)ymm_crash_UINavigationAddSelfCrash;
+ (void)launchNavigationCrashProtection;
- (void)preResetTransitionInProgress;
- (_Bool)isViewTransitionInProgress;
- (void)setViewTransitionInProgress:(_Bool)arg1;
@end

