//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VFSDKBaseModelObject.h"

@class NSArray, NSString;

@interface VFSDKLoanProductModel : VFSDKBaseModelObject
{
    NSString *_totalFeeStr;
    NSString *_term;
    NSString *_termShouldRepayStr;
    NSString *_firstPayFeeStr;
    NSString *_interestRate;
    NSString *_repayLimit;
    NSString *_repayTotal;
    NSString *_productName;
    NSString *_productId;
    NSString *_repayMethod;
    NSString *_repayDate;
    NSArray *_terms;
    NSString *_productUid;
    NSString *_iconUrl;
}

@property(copy, nonatomic) NSString *iconUrl; // @synthesize iconUrl=_iconUrl;
@property(copy, nonatomic) NSString *productUid; // @synthesize productUid=_productUid;
@property(retain, nonatomic) NSArray *terms; // @synthesize terms=_terms;
@property(copy, nonatomic) NSString *repayDate; // @synthesize repayDate=_repayDate;
@property(copy, nonatomic) NSString *repayMethod; // @synthesize repayMethod=_repayMethod;
@property(copy, nonatomic) NSString *productId; // @synthesize productId=_productId;
@property(copy, nonatomic) NSString *productName; // @synthesize productName=_productName;
@property(copy, nonatomic) NSString *repayTotal; // @synthesize repayTotal=_repayTotal;
@property(copy, nonatomic) NSString *repayLimit; // @synthesize repayLimit=_repayLimit;
@property(copy, nonatomic) NSString *interestRate; // @synthesize interestRate=_interestRate;
@property(copy, nonatomic) NSString *firstPayFeeStr; // @synthesize firstPayFeeStr=_firstPayFeeStr;
@property(copy, nonatomic) NSString *termShouldRepayStr; // @synthesize termShouldRepayStr=_termShouldRepayStr;
@property(copy, nonatomic) NSString *term; // @synthesize term=_term;
@property(copy, nonatomic) NSString *totalFeeStr; // @synthesize totalFeeStr=_totalFeeStr;
- (void).cxx_destruct;
- (id)attributeMapDictionary;

@end

