//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VFSDKBaseViewController.h"

#import "VFSDKQPBankCardMoreInfoCellDelegate.h"
#import "VFSDKWithDrawV2BalanceCellDelegate.h"
#import "VFSDKWithDrawV2MoneyCellDelegate.h"
#import "VFSDKWithdrawSuccessHandler.h"

@class NSString, UIButton, UILabel, UITableView, VFSDKApplyWithdrawParam, VFSDKUserInfoViewModel;

@interface VFSDKWithDrawV2NewCardViewController : VFSDKBaseViewController <VFSDKWithDrawV2MoneyCellDelegate, VFSDKWithDrawV2BalanceCellDelegate, VFSDKQPBankCardMoreInfoCellDelegate, VFSDKWithdrawSuccessHandler>
{
    NSString *_withdrawTimeDesc;
    UITableView *_tableView;
    UILabel *_tipLabel;
    UIButton *_withDrwaButton;
    VFSDKApplyWithdrawParam *_withDrawParam;
    NSString *_moneyStr;
    NSString *_cardNo;
    NSString *_lastAddedCardNo;
    NSString *_mobile;
    NSString *_bankCardID;
    NSString *_bankCardName;
    VFSDKUserInfoViewModel *_userInfoVM;
}

@property(retain, nonatomic) VFSDKUserInfoViewModel *userInfoVM; // @synthesize userInfoVM=_userInfoVM;
@property(copy, nonatomic) NSString *bankCardName; // @synthesize bankCardName=_bankCardName;
@property(copy, nonatomic) NSString *bankCardID; // @synthesize bankCardID=_bankCardID;
@property(copy, nonatomic) NSString *mobile; // @synthesize mobile=_mobile;
@property(copy, nonatomic) NSString *lastAddedCardNo; // @synthesize lastAddedCardNo=_lastAddedCardNo;
@property(copy, nonatomic) NSString *cardNo; // @synthesize cardNo=_cardNo;
@property(copy, nonatomic) NSString *moneyStr; // @synthesize moneyStr=_moneyStr;
@property(retain, nonatomic) VFSDKApplyWithdrawParam *withDrawParam; // @synthesize withDrawParam=_withDrawParam;
@property(retain, nonatomic) UIButton *withDrwaButton; // @synthesize withDrwaButton=_withDrwaButton;
@property(retain, nonatomic) UILabel *tipLabel; // @synthesize tipLabel=_tipLabel;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(copy, nonatomic) NSString *withdrawTimeDesc; // @synthesize withdrawTimeDesc=_withdrawTimeDesc;
- (void).cxx_destruct;
- (void)p_openPasswordKeyboard;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)saveInputInfo:(long long)arg1 withContent:(id)arg2;
- (void)allWithdraw;
- (void)withDrawV2MoneyCell:(id)arg1 hasMoney:(_Bool)arg2;
- (void)saveInputContent:(id)arg1;
- (void)showSupportBank;
- (void)withDrawSuccessedWithData:(id)arg1 pvId:(id)arg2;
- (void)withdraw:(id)arg1;
- (_Bool)checkValue;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)configWithDrawV2CardholderCell:(id)arg1 atIndexPath:(id)arg2;
- (id)configInfoCell:(id)arg1 atIndexPath:(id)arg2;
- (id)configWithDrawV2BalanceCell:(id)arg1 atIndexPath:(id)arg2;
- (id)configWithDrawV2MoneyCell:(id)arg1 atIndexPath:(id)arg2;
- (id)configHeaderCell:(id)arg1 atIndexPath:(id)arg2;
- (void)applyWithDraw;
- (void)vouWithDrawRequest;
- (void)addWithdrawCard;
- (void)userInfoRequest;
- (id)addTableFooter;
- (void)setupTableView;
- (void)didReceiveMemoryWarning;
- (void)viewWillFirstAppear;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

