//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "DZNEmptyDataSetDelegate.h"
#import "DZNEmptyDataSetSource.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, UITableView;

@interface VFSDKCouponCarrierView : UIView <UITableViewDelegate, UITableViewDataSource, DZNEmptyDataSetSource, DZNEmptyDataSetDelegate>
{
    long long _status;
    UITableView *_tableView;
    NSMutableArray *_targetModels;
}

@property(retain, nonatomic) NSMutableArray *targetModels; // @synthesize targetModels=_targetModels;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) long long status; // @synthesize status=_status;
- (void).cxx_destruct;
- (_Bool)emptyDataSetShouldAllowScroll:(id)arg1;
- (id)customViewForEmptyDataSet:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)refreshList;
- (void)appendModels:(id)arg1 withArray:(id)arg2;
- (void)updateModels:(id)arg1 withArray:(id)arg2;
- (void)footerRefresh;
- (void)headerRefresh;
- (void)configTable;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

