//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VFSDKBaseModelObject.h"

@class NSString;

@interface VFSDKMoneyLimitModel : VFSDKBaseModelObject
{
    NSString *_payLimit;
    NSString *_todayPayLimit;
    NSString *_maxPayLimit;
    NSString *_withdrawLimit;
}

@property(copy, nonatomic) NSString *withdrawLimit; // @synthesize withdrawLimit=_withdrawLimit;
@property(copy, nonatomic) NSString *maxPayLimit; // @synthesize maxPayLimit=_maxPayLimit;
@property(copy, nonatomic) NSString *todayPayLimit; // @synthesize todayPayLimit=_todayPayLimit;
@property(copy, nonatomic) NSString *payLimit; // @synthesize payLimit=_payLimit;
- (void).cxx_destruct;
- (id)attributeMapDictionary;

@end

