//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VFSDKBaseViewController.h"

#import "VFSDKQPBankCardsListPopViewDelegate.h"
#import "VFSDKWithDrawV2BalanceCellDelegate.h"
#import "VFSDKWithDrawV2MoneyCellDelegate.h"
#import "VFSDKWithdrawSuccessHandler.h"

@class NSArray, NSString, UIButton, UILabel, UITableView, VFSDKApplyWithdrawParam, VFSDKCompositeBankCardModel;

@interface VFSDKWithDrawV2ViewController : VFSDKBaseViewController <VFSDKQPBankCardsListPopViewDelegate, VFSDKWithDrawV2MoneyCellDelegate, VFSDKWithDrawV2BalanceCellDelegate, VFSDKWithdrawSuccessHandler>
{
    _Bool isGetUserInfo;
    _Bool isGetAuthInfo;
    NSArray *cardlistArr;
    VFSDKCompositeBankCardModel *selectedCard;
    UILabel *tipLabel;
    VFSDKApplyWithdrawParam *withDrawParam;
    NSString *_withdrawTimeDesc;
    UITableView *_tableView;
    UIButton *_withDrwaButton;
    NSString *_moneyStr;
}

@property(copy, nonatomic) NSString *moneyStr; // @synthesize moneyStr=_moneyStr;
@property(retain, nonatomic) UIButton *withDrwaButton; // @synthesize withDrwaButton=_withDrwaButton;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(copy, nonatomic) NSString *withdrawTimeDesc; // @synthesize withdrawTimeDesc=_withdrawTimeDesc;
@property(retain, nonatomic) VFSDKApplyWithdrawParam *withDrawParam; // @synthesize withDrawParam;
@property(retain, nonatomic) UILabel *tipLabel; // @synthesize tipLabel;
@property(retain, nonatomic) VFSDKCompositeBankCardModel *selectedCard; // @synthesize selectedCard;
@property(retain, nonatomic) NSArray *cardlistArr; // @synthesize cardlistArr;
@property(nonatomic) _Bool isGetAuthInfo; // @synthesize isGetAuthInfo;
@property(nonatomic) _Bool isGetUserInfo; // @synthesize isGetUserInfo;
- (void).cxx_destruct;
- (void)p_openPasswordKeyboard;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)allWithdraw;
- (void)withDrawV2MoneyCell:(id)arg1 hasMoney:(_Bool)arg2;
- (void)saveInputContent:(id)arg1;
- (void)useNewCard;
- (void)didSelectedWithDrawCard:(id)arg1;
- (void)withDrawSuccessedWithData:(id)arg1 pvId:(id)arg2;
- (void)withdraw:(id)arg1;
- (_Bool)checkValue;
- (void)showBankCardsList;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)configWithDrawV2BalanceCell:(id)arg1 atIndexPath:(id)arg2;
- (id)configWithDrawV2MoneyCell:(id)arg1 atIndexPath:(id)arg2;
- (id)configWithDrawV2BankcardCell:(id)arg1 atIndexPath:(id)arg2;
- (id)configHeaderCell:(id)arg1 atIndexPath:(id)arg2;
- (void)applyWithDraw;
- (void)vouWithDrawRequest;
- (void)updateUI;
- (void)manageResult:(id)arg1;
- (void)userInfoRequest;
- (void)updateStatus;
- (id)addTableFooter;
- (void)setupTableView;
- (void)setupData;
- (void)clickBackButton:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

