//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VFSDKBaseViewController.h"

#import "UIAlertViewDelegate.h"
#import "UITextFieldDelegate.h"

@class NSMutableDictionary, NSString, NSTimer, UIButton, UILabel, UITextField, UIView, UIViewController;

@interface VFSDKValidateViewController : VFSDKBaseViewController <UITextFieldDelegate, UIAlertViewDelegate>
{
    NSTimer *mCountDownTimer;
    long long mTime;
    long long count;
    UIView *inputTFBg;
    UILabel *_mMobileNumberLabel;
    UITextField *_mValidateTextField;
    UIButton *_mRenewMessageButton;
    UIButton *_mConfirmButton;
    NSString *_mMobile;
    NSString *_mTicket;
    long long _mValidateMessageType;
    UIViewController *_mSuccessVC;
    NSMutableDictionary *_mSuccessDict;
    id <VFSDKValidateDelegate> _delegate;
}

@property(nonatomic) __weak id <VFSDKValidateDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSMutableDictionary *mSuccessDict; // @synthesize mSuccessDict=_mSuccessDict;
@property(retain, nonatomic) UIViewController *mSuccessVC; // @synthesize mSuccessVC=_mSuccessVC;
@property(nonatomic) long long mValidateMessageType; // @synthesize mValidateMessageType=_mValidateMessageType;
@property(copy, nonatomic) NSString *mTicket; // @synthesize mTicket=_mTicket;
@property(copy, nonatomic) NSString *mMobile; // @synthesize mMobile=_mMobile;
@property(nonatomic) __weak UIButton *mConfirmButton; // @synthesize mConfirmButton=_mConfirmButton;
@property(nonatomic) __weak UIButton *mRenewMessageButton; // @synthesize mRenewMessageButton=_mRenewMessageButton;
@property(nonatomic) __weak UITextField *mValidateTextField; // @synthesize mValidateTextField=_mValidateTextField;
@property(nonatomic) __weak UILabel *mMobileNumberLabel; // @synthesize mMobileNumberLabel=_mMobileNumberLabel;
- (void).cxx_destruct;
- (void)reSendRealNameRequest;
- (void)payPwdResendMsgRequest;
- (void)resendPayMessage;
- (void)rechargeResendMessageRequest;
- (void)sendMsgRequest;
- (void)payConfirmRequest;
- (void)realNameConfirmRequest;
- (void)rechargeConfirmRequest;
- (void)transterConfirmRequest;
- (void)withDrawConfirmRequest;
- (void)addFastBankCardConfirmRequest;
- (void)confirmPayPwdRequest;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)sendRequest;
- (void)updateTitle;
- (void)sendMsgAction;
- (void)createView;
- (void)smsCodeMessage:(id)arg1;
- (void)handleOK:(id)arg1;
- (void)sendSMSAction:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

