//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VFSDKBaseViewController.h"

@class NSDictionary, UIButton, UIImageView, UILabel, UIView;

@interface VFSDK6ElemOpenAccountResultViewController : VFSDKBaseViewController
{
    _Bool _isQuerying;
    NSDictionary *_resultData;
    UIImageView *_iconView;
    UIView *_topContentView;
    UILabel *_titleLabel;
    UIButton *_button;
}

+ (_Bool)baseLoadFromNib;
@property _Bool isQuerying; // @synthesize isQuerying=_isQuerying;
@property(retain, nonatomic) UIButton *button; // @synthesize button=_button;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *topContentView; // @synthesize topContentView=_topContentView;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) NSDictionary *resultData; // @synthesize resultData=_resultData;
- (void).cxx_destruct;
- (void)_p_goto6ElemRealNameAuthWithTips:(id)arg1 agreements:(id)arg2;
- (void)_p_gotoUploadIDCardImage;
- (void)p_fackResultDataToProcessingState;
- (void)p_openAccountSucceed;
- (void)p_buttonDidPressed:(id)arg1;
- (void)p_queryOpenAccountResult;
- (void)p_startQueryOpenAccountResultIfNeededAfterDelay:(double)arg1;
- (void)p_stopQueryOperation;
- (void)p_refreshUIWithCurrentResultData;
@property(readonly, nonatomic) NSDictionary *btnConfig;
@property(readonly, nonatomic) long long realNameStatus;
- (void)p_setupUI;
- (void)clickBackButton:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

