//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VFSDKBaseViewController.h"

#import "VFSDKCommonInputCellDelegate.h"
#import "VFSDKQPUserAgreementViewControllerDelegate.h"

@class NSLayoutConstraint, NSMutableArray, NSString, UIButton, UITableView;

@interface VFSDKRecoverPasswordViewController : VFSDKBaseViewController <VFSDKQPUserAgreementViewControllerDelegate, VFSDKCommonInputCellDelegate>
{
    _Bool selectedAgreement;
    NSMutableArray *moreInfoArr;
    UIButton *markBtn;
    NSString *ticket;
    UITableView *_tableView;
    UIButton *_nextBtn;
    NSLayoutConstraint *_nextBtnBottom;
}

@property(nonatomic) __weak NSLayoutConstraint *nextBtnBottom; // @synthesize nextBtnBottom=_nextBtnBottom;
@property(nonatomic) __weak UIButton *nextBtn; // @synthesize nextBtn=_nextBtn;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(copy, nonatomic) NSString *ticket; // @synthesize ticket;
@property(nonatomic) _Bool selectedAgreement; // @synthesize selectedAgreement;
@property(retain, nonatomic) UIButton *markBtn; // @synthesize markBtn;
@property(retain, nonatomic) NSMutableArray *moreInfoArr; // @synthesize moreInfoArr;
- (void).cxx_destruct;
- (void)saveInputInfo:(long long)arg1 withContent:(id)arg2;
- (void)userAgreed;
- (void)toVerifyMobilePage;
- (void)next:(id)arg1;
- (void)toUserAgreement;
- (void)markBtnTouch:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)checkBankcard;
- (_Bool)checkValue;
- (struct CGSize)footerLabelSize;
- (id)addFooter;
- (void)setupAuthInfo;
- (void)setupMoreInfoArrary;
- (void)setupTableView;
- (void)setupStyle;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)clickBackButton:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

