//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VFSDKBaseViewController.h"

@class NSMutableArray, UITableView;

@interface VFSDKAuthInfoViewController : VFSDKBaseViewController
{
    UITableView *_tableView;
    NSMutableArray *_infoArr;
}

@property(retain, nonatomic) NSMutableArray *infoArr; // @synthesize infoArr=_infoArr;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)configInfoCell:(id)arg1 atIndexPath:(id)arg2;
- (id)configHeaderCell:(id)arg1 atIndexPath:(id)arg2;
- (long long)getIdx:(id)arg1;
- (void)setupInfoArrary;
- (void)setupTableView;
- (void)viewDidLoad;

@end

