//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WLJsBridgeApi.h"

@class NSString;

@interface WLJsTrackApi : WLJsBridgeApi
{
    NSString *_label;
    NSString *_values;
}

+ (id)parseToApi:(id)arg1;
@property(copy, nonatomic) NSString *values; // @synthesize values=_values;
@property(copy, nonatomic) NSString *label; // @synthesize label=_label;
- (void).cxx_destruct;

@end

