//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WLJsBridgeApi.h"

@class NSString;

@interface WLJsContactApi : WLJsBridgeApi
{
    _Bool _enableRegexTrim;
    NSString *_trimRegexStr;
}

+ (id)parseToApi:(id)arg1;
@property(copy, nonatomic) NSString *trimRegexStr; // @synthesize trimRegexStr=_trimRegexStr;
@property(nonatomic) _Bool enableRegexTrim; // @synthesize enableRegexTrim=_enableRegexTrim;
- (void).cxx_destruct;

@end

