//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JSExport.h"

@class NSString;

@protocol WLShareJSExport <JSExport>
- (void)shareToCopyLink:(NSString *)arg1;
- (void)shareToShortMessage:(NSString *)arg1;
- (void)shareToWechatMoments:(NSString *)arg1;
- (void)shareToWechat:(NSString *)arg1;
- (void)shareToQZone:(NSString *)arg1;
- (void)shareToQQ:(NSString *)arg1;
- (void)startShare:(NSString *)arg1;
- (void)share:(NSString *)arg1;
@end

