//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WLJsApiClass.h"

#import "WLShareJSExport.h"

@class WLJsShareApi;

@interface WLShare : WLJsApiClass <WLShareJSExport>
{
    WLJsShareApi *_shareApi;
}

@property(retain, nonatomic) WLJsShareApi *shareApi; // @synthesize shareApi=_shareApi;
- (void).cxx_destruct;
- (void)shareToCopyLink:(id)arg1;
- (void)shareToShortMessage:(id)arg1;
- (void)shareToWechatMoments:(id)arg1;
- (void)shareToWechat:(id)arg1;
- (void)shareToQZone:(id)arg1;
- (void)shareToQQ:(id)arg1;
- (void)startShare:(id)arg1;
- (void)selectPlatformToShare:(id)arg1;
- (void)shareWithInfoModel:(id)arg1;
- (void)share:(id)arg1;
- (_Bool)setShareInfo:(id)arg1;
- (_Bool)setSharePlatform:(id)arg1;
- (void)didShareSuccess;
- (void)didShareCanceled;
- (void)didSelectedSharePlatform:(id)arg1;
- (void)registerApi;

@end

