//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class NSArray, NSNumber;

@interface YFNetMessageItem : YMMCommonModel
{
    NSNumber *_success;
    NSArray *_data;
}

+ (Class)ymm_classForCollectionPropertyName:(id)arg1;
@property(retain, nonatomic) NSArray *data; // @synthesize data=_data;
@property(retain, nonatomic) NSNumber *success; // @synthesize success=_success;
- (void).cxx_destruct;

@end

