//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class NSNumber, NSString, YMMAdvertisementModel;

@interface YMMAdvertModel : YMMCommonModel
{
    NSNumber *_advertId;
    NSNumber *_positionCode;
    NSNumber *_startTime;
    NSNumber *_endTime;
    NSNumber *_updateTime;
    NSString *_pictureUrl;
    NSString *_url;
    NSString *_text;
    NSNumber *_appType;
    NSNumber *_sort;
    NSNumber *_frequency;
    long long _installType;
    NSString *_utmCampaign;
    YMMAdvertisementModel *_model;
}

@property(retain, nonatomic) YMMAdvertisementModel *model; // @synthesize model=_model;
@property(retain, nonatomic) NSString *utmCampaign; // @synthesize utmCampaign=_utmCampaign;
@property(nonatomic) long long installType; // @synthesize installType=_installType;
@property(retain, nonatomic) NSNumber *frequency; // @synthesize frequency=_frequency;
@property(retain, nonatomic) NSNumber *sort; // @synthesize sort=_sort;
@property(retain, nonatomic) NSNumber *appType; // @synthesize appType=_appType;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *pictureUrl; // @synthesize pictureUrl=_pictureUrl;
@property(retain, nonatomic) NSNumber *updateTime; // @synthesize updateTime=_updateTime;
@property(retain, nonatomic) NSNumber *endTime; // @synthesize endTime=_endTime;
@property(retain, nonatomic) NSNumber *startTime; // @synthesize startTime=_startTime;
@property(retain, nonatomic) NSNumber *positionCode; // @synthesize positionCode=_positionCode;
@property(retain, nonatomic) NSNumber *advertId; // @synthesize advertId=_advertId;
- (void).cxx_destruct;
- (id)advertModel;

@end

