//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface YMMAppInfoModel : NSObject
{
    long long _companyType;
    long long _appType;
    NSString *_appVersion;
    long long _appVersionInt;
    NSString *_appBundleId;
    NSString *_appPlistBundleID;
}

+ (void)loadYMMAppBundle;
+ (void)load;
@property(readonly, nonatomic) NSString *appPlistBundleID; // @synthesize appPlistBundleID=_appPlistBundleID;
@property(readonly, nonatomic) NSString *appBundleId; // @synthesize appBundleId=_appBundleId;
@property(nonatomic) long long appVersionInt; // @synthesize appVersionInt=_appVersionInt;
@property(retain, nonatomic) NSString *appVersion; // @synthesize appVersion=_appVersion;
@property(nonatomic) long long appType; // @synthesize appType=_appType;
@property(nonatomic) long long companyType; // @synthesize companyType=_companyType;
- (void).cxx_destruct;
- (long long)getVersionInt:(id)arg1;
- (long long)getAppTypeFromBundleId:(id)arg1;
- (id)init;

@end

