//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseModel.h"

@class NSArray, NSString, YMMBaigainCargoInfoModel, YMMBargainDialogModel, YMMBargainEarnestInfoModel, YMMBargainInfoModel;

@interface YMMBargainHomePageModel : YMMBaseModel
{
    _Bool _canVoice;
    _Bool _canBidding;
    _Bool _canTerminate;
    YMMBargainDialogModel *_limitDlg;
    long long _limitReason;
    YMMBargainDialogModel *_backDlg;
    YMMBargainDialogModel *_terminatedDlg;
    YMMBargainDialogModel *_privacyAuthDlg;
    NSString *_unreadSchema;
    NSString *_leftTimeText;
    long long _leftTime;
    YMMBaigainCargoInfoModel *_bargainCargoInfo;
    NSString *_commonProblemTitle;
    NSArray *_commonProblems;
    YMMBargainInfoModel *_bargainInfo;
    YMMBargainEarnestInfoModel *_earnestInfo;
    NSString *_voiceBtnText;
    NSString *_biddingBtnText;
}

@property(nonatomic) _Bool canTerminate; // @synthesize canTerminate=_canTerminate;
@property(nonatomic) _Bool canBidding; // @synthesize canBidding=_canBidding;
@property(nonatomic) _Bool canVoice; // @synthesize canVoice=_canVoice;
@property(copy, nonatomic) NSString *biddingBtnText; // @synthesize biddingBtnText=_biddingBtnText;
@property(copy, nonatomic) NSString *voiceBtnText; // @synthesize voiceBtnText=_voiceBtnText;
@property(retain, nonatomic) YMMBargainEarnestInfoModel *earnestInfo; // @synthesize earnestInfo=_earnestInfo;
@property(retain, nonatomic) YMMBargainInfoModel *bargainInfo; // @synthesize bargainInfo=_bargainInfo;
@property(copy, nonatomic) NSArray *commonProblems; // @synthesize commonProblems=_commonProblems;
@property(copy, nonatomic) NSString *commonProblemTitle; // @synthesize commonProblemTitle=_commonProblemTitle;
@property(retain, nonatomic) YMMBaigainCargoInfoModel *bargainCargoInfo; // @synthesize bargainCargoInfo=_bargainCargoInfo;
@property(nonatomic) long long leftTime; // @synthesize leftTime=_leftTime;
@property(copy, nonatomic) NSString *leftTimeText; // @synthesize leftTimeText=_leftTimeText;
@property(copy, nonatomic) NSString *unreadSchema; // @synthesize unreadSchema=_unreadSchema;
@property(retain, nonatomic) YMMBargainDialogModel *privacyAuthDlg; // @synthesize privacyAuthDlg=_privacyAuthDlg;
@property(retain, nonatomic) YMMBargainDialogModel *terminatedDlg; // @synthesize terminatedDlg=_terminatedDlg;
@property(retain, nonatomic) YMMBargainDialogModel *backDlg; // @synthesize backDlg=_backDlg;
@property(nonatomic) long long limitReason; // @synthesize limitReason=_limitReason;
@property(retain, nonatomic) YMMBargainDialogModel *limitDlg; // @synthesize limitDlg=_limitDlg;
- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long operationViewType;

@end

