//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSNumber, NSString, UITableView, YMMCommentTagsNewCell, YMMCommentViewModel, YMMEvaluationInfoModel;

@interface YMMCommentOthersViewListController : YMMBaseViewController <UITableViewDelegate, UITableViewDataSource>
{
    NSString *_userId;
    UITableView *_tableView;
    NSMutableArray *_commentListArray;
    YMMEvaluationInfoModel *_evaluationInfoModel;
    YMMCommentViewModel *_viewModel;
    NSNumber *_score;
    NSNumber *_tagId;
    YMMCommentTagsNewCell *_tagsNewCell;
}

@property(retain, nonatomic) YMMCommentTagsNewCell *tagsNewCell; // @synthesize tagsNewCell=_tagsNewCell;
@property(retain, nonatomic) NSNumber *tagId; // @synthesize tagId=_tagId;
@property(retain, nonatomic) NSNumber *score; // @synthesize score=_score;
@property(retain, nonatomic) YMMCommentViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) YMMEvaluationInfoModel *evaluationInfoModel; // @synthesize evaluationInfoModel=_evaluationInfoModel;
@property(retain, nonatomic) NSMutableArray *commentListArray; // @synthesize commentListArray=_commentListArray;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSString *userId; // @synthesize userId=_userId;
- (void).cxx_destruct;
- (id)ymm_pageName;
- (void)pagePVJournal;
- (id)drawCommentCellInTableView:(id)arg1 forIndexPath:(id)arg2;
- (id)drawScoreCellInTableView:(id)arg1 forIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)commentListTaskMoreDate;
- (void)commentListTaskUpDate;
- (void)getCommentInfoTask;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

