//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseTableViewCell.h"

@class UIButton, UIImageView, UILabel, UIView, YMMCargoModel;

@interface YMMCargoRecordCell : YMMBaseTableViewCell
{
    UILabel *_placeLabel;
    UILabel *_goodInfoLabel;
    UIImageView *_rightIcon;
    UILabel *_middleLabel;
    UIImageView *_avacterImageView;
    UILabel *_shipperNameLabel;
    UILabel *_dateTimeLabel;
    UIButton *_contactButton;
    UIButton *_priceButton;
    UILabel *_hasSoldoutLabel;
    UIButton *_remarkButton;
    UIImageView *_remarkIconImgView;
    UILabel *_remarkLabel;
    CDUnknownBlockType _callback;
    CDUnknownBlockType _contactShipperBlock;
    CDUnknownBlockType _payNewCargoBlock;
    UIView *_containerView;
    UILabel *_bottomLabel;
    UILabel *_tagLabel;
    YMMCargoModel *_cargoModel;
    long long _index;
}

+ (double)ymm_heightForCellWithItem:(id)arg1 contentWidth:(double)arg2;
+ (id)ymm_createCellForTableView:(id)arg1;
@property(nonatomic) long long index; // @synthesize index=_index;
@property(retain, nonatomic) YMMCargoModel *cargoModel; // @synthesize cargoModel=_cargoModel;
@property(retain, nonatomic) UILabel *tagLabel; // @synthesize tagLabel=_tagLabel;
@property(retain, nonatomic) UILabel *bottomLabel; // @synthesize bottomLabel=_bottomLabel;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(copy, nonatomic) CDUnknownBlockType payNewCargoBlock; // @synthesize payNewCargoBlock=_payNewCargoBlock;
@property(copy, nonatomic) CDUnknownBlockType contactShipperBlock; // @synthesize contactShipperBlock=_contactShipperBlock;
@property(copy, nonatomic) CDUnknownBlockType callback; // @synthesize callback=_callback;
@property(retain, nonatomic) UILabel *remarkLabel; // @synthesize remarkLabel=_remarkLabel;
@property(retain, nonatomic) UIImageView *remarkIconImgView; // @synthesize remarkIconImgView=_remarkIconImgView;
@property(retain, nonatomic) UIButton *remarkButton; // @synthesize remarkButton=_remarkButton;
@property(retain, nonatomic) UILabel *hasSoldoutLabel; // @synthesize hasSoldoutLabel=_hasSoldoutLabel;
@property(retain, nonatomic) UIButton *priceButton; // @synthesize priceButton=_priceButton;
@property(retain, nonatomic) UIButton *contactButton; // @synthesize contactButton=_contactButton;
@property(retain, nonatomic) UILabel *dateTimeLabel; // @synthesize dateTimeLabel=_dateTimeLabel;
@property(retain, nonatomic) UILabel *shipperNameLabel; // @synthesize shipperNameLabel=_shipperNameLabel;
@property(retain, nonatomic) UIImageView *avacterImageView; // @synthesize avacterImageView=_avacterImageView;
@property(retain, nonatomic) UILabel *middleLabel; // @synthesize middleLabel=_middleLabel;
@property(retain, nonatomic) UIImageView *rightIcon; // @synthesize rightIcon=_rightIcon;
@property(retain, nonatomic) UILabel *goodInfoLabel; // @synthesize goodInfoLabel=_goodInfoLabel;
@property(retain, nonatomic) UILabel *placeLabel; // @synthesize placeLabel=_placeLabel;
- (void).cxx_destruct;
- (_Bool)isCargoTypeBuyoutCargo;
- (_Bool)isContactButtonHidden;
- (_Bool)isCargoTypeBuyoutAndFineAndNormalOrMYB:(id)arg1;
- (void)payDeposit:(id)arg1;
- (void)contactShipper:(id)arg1;
- (void)addCallLogRemark:(id)arg1;
- (void)updateConstraints;
- (void)ymm_configWithItemModel:(id)arg1 cargoIndex:(long long)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

