//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseTableViewCell.h"

#import "UITextFieldDelegate.h"

@class NSArray, NSMutableArray, NSNumber, NSString, UIButton, UILabel, UITextField, UIView, YMMPublishDepositMarkInfoView;

@interface YMMCompanyQuoteSettlementCell : YMMBaseTableViewCell <UITextFieldDelegate>
{
    NSMutableArray *_buttonArr;
    long long _selectedSceneType;
    _Bool _isHideQuote;
    unsigned long long _companyQuoteMoneyType;
    long long _currentSceneType;
    NSNumber *_charge;
    unsigned long long _weightCapacityType;
    CDUnknownBlockType _selectQuoteMoneyCallback;
    CDUnknownBlockType _fieldDidChangedCallback;
    CDUnknownBlockType _editCallback;
    CDUnknownBlockType _dismissCallback;
    CDUnknownBlockType _dealTypeBlock;
    long long _buyoutPrice;
    long long _showBiddingModel;
    unsigned long long _dealType;
    long long _buttonChooseTag;
    CDUnknownBlockType _showTipsBlock;
    NSArray *_depositItem;
    CDUnknownBlockType _clickDepositBlock;
    CDUnknownBlockType _modelBtnBlock;
    CDUnknownBlockType _modelDefaultStateBlock;
    UIView *_sectionView;
    UILabel *_sectionLabel;
    UIView *_innerView;
    UILabel *_titleLabel;
    UIView *_buttonView;
    UIView *_typeView;
    UILabel *_typeLabel;
    UIButton *_typeButton;
    UIView *_typeButtonView;
    UIView *_inputView;
    UILabel *_inputLabel;
    UITextField *_inputField;
    UILabel *_freightLabel;
    YMMPublishDepositMarkInfoView *_depositMarkInfoView;
}

+ (double)ymm_heightForCellWithItem:(id)arg1 contentWidth:(double)arg2;
+ (double)cellLblHeight:(id)arg1;
+ (id)cellRightDepositGuarantee:(id)arg1 dealModel:(unsigned long long)arg2;
+ (id)createReuseCellForTableView:(id)arg1 withCellIdentifier:(id)arg2;
@property(retain, nonatomic) YMMPublishDepositMarkInfoView *depositMarkInfoView; // @synthesize depositMarkInfoView=_depositMarkInfoView;
@property(retain, nonatomic) UILabel *freightLabel; // @synthesize freightLabel=_freightLabel;
@property(retain, nonatomic) UITextField *inputField; // @synthesize inputField=_inputField;
@property(retain, nonatomic) UILabel *inputLabel; // @synthesize inputLabel=_inputLabel;
@property(retain, nonatomic) UIView *inputView; // @synthesize inputView=_inputView;
@property(retain, nonatomic) UIView *typeButtonView; // @synthesize typeButtonView=_typeButtonView;
@property(retain, nonatomic) UIButton *typeButton; // @synthesize typeButton=_typeButton;
@property(retain, nonatomic) UILabel *typeLabel; // @synthesize typeLabel=_typeLabel;
@property(retain, nonatomic) UIView *typeView; // @synthesize typeView=_typeView;
@property(retain, nonatomic) UIView *buttonView; // @synthesize buttonView=_buttonView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *innerView; // @synthesize innerView=_innerView;
@property(retain, nonatomic) UILabel *sectionLabel; // @synthesize sectionLabel=_sectionLabel;
@property(retain, nonatomic) UIView *sectionView; // @synthesize sectionView=_sectionView;
@property(copy, nonatomic) CDUnknownBlockType modelDefaultStateBlock; // @synthesize modelDefaultStateBlock=_modelDefaultStateBlock;
@property(copy, nonatomic) CDUnknownBlockType modelBtnBlock; // @synthesize modelBtnBlock=_modelBtnBlock;
@property(copy, nonatomic) CDUnknownBlockType clickDepositBlock; // @synthesize clickDepositBlock=_clickDepositBlock;
@property(retain, nonatomic) NSArray *depositItem; // @synthesize depositItem=_depositItem;
@property(copy, nonatomic) CDUnknownBlockType showTipsBlock; // @synthesize showTipsBlock=_showTipsBlock;
@property(nonatomic) long long buttonChooseTag; // @synthesize buttonChooseTag=_buttonChooseTag;
@property(nonatomic) unsigned long long dealType; // @synthesize dealType=_dealType;
@property(nonatomic) _Bool isHideQuote; // @synthesize isHideQuote=_isHideQuote;
@property(nonatomic) long long showBiddingModel; // @synthesize showBiddingModel=_showBiddingModel;
@property(nonatomic) long long buyoutPrice; // @synthesize buyoutPrice=_buyoutPrice;
@property(copy, nonatomic) CDUnknownBlockType dealTypeBlock; // @synthesize dealTypeBlock=_dealTypeBlock;
@property(copy, nonatomic) CDUnknownBlockType dismissCallback; // @synthesize dismissCallback=_dismissCallback;
@property(copy, nonatomic) CDUnknownBlockType editCallback; // @synthesize editCallback=_editCallback;
@property(copy, nonatomic) CDUnknownBlockType fieldDidChangedCallback; // @synthesize fieldDidChangedCallback=_fieldDidChangedCallback;
@property(copy, nonatomic) CDUnknownBlockType selectQuoteMoneyCallback; // @synthesize selectQuoteMoneyCallback=_selectQuoteMoneyCallback;
@property(nonatomic) unsigned long long weightCapacityType; // @synthesize weightCapacityType=_weightCapacityType;
@property(retain, nonatomic) NSNumber *charge; // @synthesize charge=_charge;
@property(nonatomic) long long currentSceneType; // @synthesize currentSceneType=_currentSceneType;
@property(nonatomic) unsigned long long companyQuoteMoneyType; // @synthesize companyQuoteMoneyType=_companyQuoteMoneyType;
- (void).cxx_destruct;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)keyboardWillBeHidden:(id)arg1;
- (void)keyboardWasShown:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)textFieldDidChanged:(id)arg1;
- (void)ymm_configWithItemModel:(id)arg1;
- (void)doneAction;
- (void)showTips:(id)arg1;
- (void)pick:(id)arg1;
- (double)getLblHeight:(id)arg1;
- (void)checkTipsShow;
- (id)getRightDepositGuarantee:(id)arg1;
- (void)pickType:(id)arg1;
- (long long)dealModelTransToBtntag:(unsigned long long)arg1;
- (void)removeKeyboardNotifications;
- (void)addObserverForTextField;
- (id)highlightAttr:(id)arg1;
- (void)setButtonHighlight:(id)arg1;
- (void)setButtonNormal:(id)arg1;
- (void)renderTypeOptionView;
- (void)renderOptionView;
- (void)removeViews;
- (void)initControls;
- (id)depositValues;
- (id)buyoutTitles;
- (id)depositBtnTitles;
- (id)freightUnitArr;
- (void)setNeedsUpdateConstraints;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

