//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseModel.h"

@class NSString;

@interface YMMComplaintOptionModel : YMMBaseModel
{
    long long _selectionKey;
    NSString *_selectionValue;
}

@property(copy, nonatomic) NSString *selectionValue; // @synthesize selectionValue=_selectionValue;
@property(nonatomic) long long selectionKey; // @synthesize selectionKey=_selectionKey;
- (void).cxx_destruct;

@end

