//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class NSString;

@interface YMMCargoInsuranceTip : YMMCommonModel
{
    NSString *_cargoInsuranceImg;
    NSString *_cargoInsuranceHint;
}

@property(copy, nonatomic) NSString *cargoInsuranceHint; // @synthesize cargoInsuranceHint=_cargoInsuranceHint;
@property(copy, nonatomic) NSString *cargoInsuranceImg; // @synthesize cargoInsuranceImg=_cargoInsuranceImg;
- (void).cxx_destruct;

@end

