//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class NSString;

@interface YMMCommonUseModel : YMMCommonModel
{
    long long _tagId;
    NSString *_content;
}

@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(nonatomic) long long tagId; // @synthesize tagId=_tagId;
- (void).cxx_destruct;

@end

