//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "YMMCustomActionSheetDelegate.h"
#import "YMMImagePickerManagerDelegate.h"

@class NSMutableArray, NSString, UIButton, UIImageView, UILabel, YMMCollectorViewModel, YMMOSSUploadManager;

@interface YMMCollectorUploadView : UIView <YMMCustomActionSheetDelegate, YMMImagePickerManagerDelegate>
{
    UIView *_maskView;
    UIView *_holdView;
    UIView *_lineView;
    UILabel *_titleLab;
    UILabel *_contentLab;
    UIImageView *_addImageView;
    UIButton *_submitBtn;
    NSMutableArray *_dataArr;
    NSMutableArray *_imgViewArr;
    YMMOSSUploadManager *_ossManager;
    YMMCollectorViewModel *_viewModel;
}

@property(retain, nonatomic) YMMCollectorViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) YMMOSSUploadManager *ossManager; // @synthesize ossManager=_ossManager;
@property(retain, nonatomic) NSMutableArray *imgViewArr; // @synthesize imgViewArr=_imgViewArr;
@property(retain, nonatomic) NSMutableArray *dataArr; // @synthesize dataArr=_dataArr;
@property(retain, nonatomic) UIButton *submitBtn; // @synthesize submitBtn=_submitBtn;
@property(retain, nonatomic) UIImageView *addImageView; // @synthesize addImageView=_addImageView;
@property(retain, nonatomic) UILabel *contentLab; // @synthesize contentLab=_contentLab;
@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) UIView *holdView; // @synthesize holdView=_holdView;
@property(retain, nonatomic) UIView *maskView; // @synthesize maskView=_maskView;
- (void).cxx_destruct;
- (void)ymm_imagePickerManagerDidSelectItem:(id)arg1 dataStringArray:(id)arg2;
- (void)actionSheet:(id)arg1 didClickedButtonAtIndex:(long long)arg2;
- (id)generateOSSUploadFileArrayByImages:(id)arg1;
- (void)submitBtnClicked:(id)arg1;
- (void)addImageAction;
- (void)tap:(id)arg1;
- (void)tapGesture:(id)arg1;
- (void)recreateImageView;
- (void)makeConstraint;
- (void)initUI;
- (void)initData;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

