//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class NSArray;

@interface YMMCompanyContactBaseModel : YMMCommonModel
{
    NSArray *_companyContactList;
}

+ (Class)ymm_classForCollectionPropertyName:(id)arg1;
@property(retain, nonatomic) NSArray *companyContactList; // @synthesize companyContactList=_companyContactList;
- (void).cxx_destruct;

@end

