//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class NSString;

@interface YMMCargoPointTextModel : YMMCommonModel
{
    NSString *_pointText;
}

@property(retain, nonatomic) NSString *pointText; // @synthesize pointText=_pointText;
- (void).cxx_destruct;
- (void)setValue:(id)arg1 forKey:(id)arg2;

@end

