//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class NSArray, NSString;

@interface YMMCompanyModel : YMMCommonModel
{
    NSString *_clientId;
    NSString *_clientName;
    NSArray *_cargoes;
}

+ (Class)ymm_classForCollectionPropertyName:(id)arg1;
@property(copy, nonatomic) NSArray *cargoes; // @synthesize cargoes=_cargoes;
@property(copy, nonatomic) NSString *clientName; // @synthesize clientName=_clientName;
@property(copy, nonatomic) NSString *clientId; // @synthesize clientId=_clientId;
- (void).cxx_destruct;

@end

