//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class NSNumber, NSString;

@interface YMMCommentOrderBeanModel : YMMCommonModel
{
    NSString *_startCity;
    NSNumber *_startCityCode;
    NSString *_endCity;
    NSNumber *_endCityCode;
    NSString *_cargoName;
    NSNumber *_orderId;
    NSString *_imageUrl;
    NSString *_username;
    NSNumber *_userId;
    NSNumber *_createTime;
    NSString *_telephone;
}

@property(copy, nonatomic) NSString *telephone; // @synthesize telephone=_telephone;
@property(retain, nonatomic) NSNumber *createTime; // @synthesize createTime=_createTime;
@property(copy, nonatomic) NSNumber *userId; // @synthesize userId=_userId;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(copy, nonatomic) NSString *imageUrl; // @synthesize imageUrl=_imageUrl;
@property(retain, nonatomic) NSNumber *orderId; // @synthesize orderId=_orderId;
@property(copy, nonatomic) NSString *cargoName; // @synthesize cargoName=_cargoName;
@property(retain, nonatomic) NSNumber *endCityCode; // @synthesize endCityCode=_endCityCode;
@property(copy, nonatomic) NSString *endCity; // @synthesize endCity=_endCity;
@property(retain, nonatomic) NSNumber *startCityCode; // @synthesize startCityCode=_startCityCode;
@property(copy, nonatomic) NSString *startCity; // @synthesize startCity=_startCity;
- (void).cxx_destruct;

@end

