//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, UILabel;

@interface YMMCargoCommentTagsView : UIView
{
    UIView *_tagsView;
    NSMutableArray *_selectedTagsButtonArray;
    NSMutableArray *_goodTagsButtonArr;
    NSMutableArray *_mediumTagsButtonArr;
    NSMutableArray *_badTagsButtonArr;
    UILabel *lbScoreType;
    long long _selectedTagsType;
    NSMutableArray *_selectedTagsArray;
    id <YMMCargoCommentTagsViewDelegate> _delegate;
}

@property(nonatomic) __weak id <YMMCargoCommentTagsViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSMutableArray *selectedTagsArray; // @synthesize selectedTagsArray=_selectedTagsArray;
@property(nonatomic) long long selectedTagsType; // @synthesize selectedTagsType=_selectedTagsType;
- (void).cxx_destruct;
- (void)showTagsByType:(id)arg1;
- (void)pick:(id)arg1;
- (id)renderViewFromCache:(long long)arg1;
- (id)tagsView:(long long)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

