//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BMKMapView, BMKPointAnnotation, UIImageView, UILabel, UIScrollView, YMMCollectionItemDataConfigure, YYTextView;

@interface YMMCollectionItemAlertContainerView : UIView
{
    YMMCollectionItemDataConfigure *_configure;
    YYTextView *_textView;
    UIScrollView *_scrollView;
    UIImageView *_imageView;
    UIImageView *_iconImageView;
    UILabel *_addressTitleLab;
    UILabel *_addressSubTitleLab;
    BMKMapView *_mapView;
    BMKPointAnnotation *_annotation;
}

@property(retain, nonatomic) BMKPointAnnotation *annotation; // @synthesize annotation=_annotation;
@property(retain, nonatomic) BMKMapView *mapView; // @synthesize mapView=_mapView;
@property(retain, nonatomic) UILabel *addressSubTitleLab; // @synthesize addressSubTitleLab=_addressSubTitleLab;
@property(retain, nonatomic) UILabel *addressTitleLab; // @synthesize addressTitleLab=_addressTitleLab;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) YYTextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) YMMCollectionItemDataConfigure *configure; // @synthesize configure=_configure;
- (void).cxx_destruct;
- (void)updateSubViewsIsVisable;
- (void)updateAddressLayout;
- (void)updateImageLayout;
- (void)updateTextLayout;
- (void)updateConstraints;
- (void)addSubViews;
- (void)configureWithCollectionItemDataConfigure:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

