//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSAttributedString, NSString;

@interface YMMConversation : NSObject
{
    _Bool _inTransportating;
    _Bool _supportVoice;
    NSString *_fromUid;
    NSString *_toUid;
    long long _lastId;
    long long _chatType;
    NSString *_msgType;
    NSString *_content;
    long long _cargoId;
    long long _unReadCount;
    NSString *_fromCity;
    NSString *_toCity;
    NSString *_route;
    NSString *_cargoMessage;
    long long _lastTimestamp;
    long long _localTime;
    long long _msgStatus;
    long long _sendStatus;
    long long _conversationId;
    NSString *_avatar;
    NSString *_userName;
    NSString *_userTelephone;
    long long _conversationType;
    NSString *_praiseRate;
    NSString *_schema;
    unsigned long long _orderRule;
    NSAttributedString *_conAttr;
    NSString *_cargoInfo;
    NSString *_lastTimeDesc;
}

@property(copy, nonatomic) NSString *lastTimeDesc; // @synthesize lastTimeDesc=_lastTimeDesc;
@property(copy, nonatomic) NSString *cargoInfo; // @synthesize cargoInfo=_cargoInfo;
@property(copy, nonatomic) NSAttributedString *conAttr; // @synthesize conAttr=_conAttr;
@property(nonatomic) unsigned long long orderRule; // @synthesize orderRule=_orderRule;
@property(nonatomic) _Bool supportVoice; // @synthesize supportVoice=_supportVoice;
@property(copy, nonatomic) NSString *schema; // @synthesize schema=_schema;
@property(nonatomic, getter=isInTransportating) _Bool inTransportating; // @synthesize inTransportating=_inTransportating;
@property(copy, nonatomic) NSString *praiseRate; // @synthesize praiseRate=_praiseRate;
@property(nonatomic) long long conversationType; // @synthesize conversationType=_conversationType;
@property(copy, nonatomic) NSString *userTelephone; // @synthesize userTelephone=_userTelephone;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(copy, nonatomic) NSString *avatar; // @synthesize avatar=_avatar;
@property(nonatomic) long long conversationId; // @synthesize conversationId=_conversationId;
@property(nonatomic) long long sendStatus; // @synthesize sendStatus=_sendStatus;
@property(nonatomic) long long msgStatus; // @synthesize msgStatus=_msgStatus;
@property(nonatomic) long long localTime; // @synthesize localTime=_localTime;
@property(nonatomic) long long lastTimestamp; // @synthesize lastTimestamp=_lastTimestamp;
@property(copy, nonatomic) NSString *cargoMessage; // @synthesize cargoMessage=_cargoMessage;
@property(copy, nonatomic) NSString *route; // @synthesize route=_route;
@property(copy, nonatomic) NSString *toCity; // @synthesize toCity=_toCity;
@property(copy, nonatomic) NSString *fromCity; // @synthesize fromCity=_fromCity;
@property(nonatomic) long long unReadCount; // @synthesize unReadCount=_unReadCount;
@property(nonatomic) long long cargoId; // @synthesize cargoId=_cargoId;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString *msgType; // @synthesize msgType=_msgType;
@property(nonatomic) long long chatType; // @synthesize chatType=_chatType;
@property(nonatomic) long long lastId; // @synthesize lastId=_lastId;
@property(copy, nonatomic) NSString *toUid; // @synthesize toUid=_toUid;
@property(copy, nonatomic) NSString *fromUid; // @synthesize fromUid=_fromUid;
- (void).cxx_destruct;
- (id)init;

@end

