//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseTableViewCell.h"

@class UIButton, UIImageView, UILabel, UIView, YMMCargoDetailModel;

@interface YMMCargoDetailRouteCell : YMMBaseTableViewCell
{
    CDUnknownBlockType _gotoMapDetailBlock;
    CDUnknownBlockType _showtipBlock;
    CDUnknownBlockType _showBuyoutTipBlock;
    YMMCargoDetailModel *_cargoModel;
    UILabel *_lineLb;
    UILabel *_updateTime;
    UILabel *_tipLb;
    UILabel *_miliLb;
    UIButton *_mapBt;
    UIView *_bottomLine;
    UIView *_bottomRightLine;
    UILabel *_quoteNumLb;
    UIButton *_cargoInsurBtn;
    UILabel *_visitNumLb;
    UILabel *_unpopularTipLb;
    UILabel *_unpopularIconLb;
    UILabel *_buyoutLabel;
    UIImageView *_buyoutIconImageView;
    UIButton *_buyoutView;
}

+ (id)attributedStringWithVisitorsNum:(unsigned long long)arg1 calledDriverCount:(unsigned long long)arg2;
+ (id)quoteNumAttributedString:(unsigned long long)arg1;
+ (struct CGSize)sizeLabelToFit:(id)arg1 height:(double)arg2;
+ (double)widthWithVisitorsNum:(unsigned long long)arg1 calledDriverCount:(unsigned long long)arg2;
+ (double)quoteNumAttributedStrWidth:(unsigned long long)arg1;
+ (double)ymm_heightForCellWithItem:(id)arg1 contentWidth:(double)arg2;
@property(retain, nonatomic) UIButton *buyoutView; // @synthesize buyoutView=_buyoutView;
@property(retain, nonatomic) UIImageView *buyoutIconImageView; // @synthesize buyoutIconImageView=_buyoutIconImageView;
@property(retain, nonatomic) UILabel *buyoutLabel; // @synthesize buyoutLabel=_buyoutLabel;
@property(retain, nonatomic) UILabel *unpopularIconLb; // @synthesize unpopularIconLb=_unpopularIconLb;
@property(retain, nonatomic) UILabel *unpopularTipLb; // @synthesize unpopularTipLb=_unpopularTipLb;
@property(retain, nonatomic) UILabel *visitNumLb; // @synthesize visitNumLb=_visitNumLb;
@property(retain, nonatomic) UIButton *cargoInsurBtn; // @synthesize cargoInsurBtn=_cargoInsurBtn;
@property(retain, nonatomic) UILabel *quoteNumLb; // @synthesize quoteNumLb=_quoteNumLb;
@property(retain, nonatomic) UIView *bottomRightLine; // @synthesize bottomRightLine=_bottomRightLine;
@property(retain, nonatomic) UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain, nonatomic) UIButton *mapBt; // @synthesize mapBt=_mapBt;
@property(retain, nonatomic) UILabel *miliLb; // @synthesize miliLb=_miliLb;
@property(retain, nonatomic) UILabel *tipLb; // @synthesize tipLb=_tipLb;
@property(retain, nonatomic) UILabel *updateTime; // @synthesize updateTime=_updateTime;
@property(retain, nonatomic) UILabel *lineLb; // @synthesize lineLb=_lineLb;
@property(retain, nonatomic) YMMCargoDetailModel *cargoModel; // @synthesize cargoModel=_cargoModel;
@property(copy, nonatomic) CDUnknownBlockType showBuyoutTipBlock; // @synthesize showBuyoutTipBlock=_showBuyoutTipBlock;
@property(copy, nonatomic) CDUnknownBlockType showtipBlock; // @synthesize showtipBlock=_showtipBlock;
@property(copy, nonatomic) CDUnknownBlockType gotoMapDetailBlock; // @synthesize gotoMapDetailBlock=_gotoMapDetailBlock;
- (void).cxx_destruct;
- (void)buyoutViewAction:(id)arg1;
- (id)tagImageWithSize:(struct CGSize)arg1;
- (void)EnableInsureBtn;
- (void)showTipView;
- (void)gotoMapDetail;
- (void)updateConstraints;
- (void)addSubViews;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)ymm_configWithItemModel:(id)arg1;

@end

