//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@interface YMMCargoPrivilege : YMMCommonModel
{
    _Bool _useStepCargo;
}

@property(nonatomic) _Bool useStepCargo; // @synthesize useStepCargo=_useStepCargo;

@end

