//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

#import "YMMCargoDelegateModel.h"

@class NSNumber, NSString;

@interface YMMCargoNewOrderInfoModel : YMMCommonModel <YMMCargoDelegateModel>
{
    long long _showWindow;
    NSString *_consignorName;
    long long _startPlace;
    long long _endPlace;
    NSNumber *_truckLength;
    NSString *_truckLengthSet;
    long long _truckType;
    NSString *_truckTypeSet;
    NSNumber *_weight;
    NSNumber *_capacity;
    NSString *_cargoName;
    NSNumber *_orderId;
    NSString *_hint;
    long long _lclCargo;
    NSString *_startName;
    NSString *_endName;
    NSString *_truckLengthCodes;
    NSString *_truckTypeCodes;
    NSString *_weightRange;
    NSString *_capacityRange;
}

@property(copy, nonatomic) NSString *capacityRange; // @synthesize capacityRange=_capacityRange;
@property(copy, nonatomic) NSString *weightRange; // @synthesize weightRange=_weightRange;
@property(copy, nonatomic) NSString *truckTypeCodes; // @synthesize truckTypeCodes=_truckTypeCodes;
@property(copy, nonatomic) NSString *truckLengthCodes; // @synthesize truckLengthCodes=_truckLengthCodes;
@property(copy, nonatomic) NSString *endName; // @synthesize endName=_endName;
@property(copy, nonatomic) NSString *startName; // @synthesize startName=_startName;
@property(nonatomic) long long lclCargo; // @synthesize lclCargo=_lclCargo;
@property(copy, nonatomic) NSString *hint; // @synthesize hint=_hint;
@property(retain, nonatomic) NSNumber *orderId; // @synthesize orderId=_orderId;
@property(copy, nonatomic) NSString *cargoName; // @synthesize cargoName=_cargoName;
@property(retain, nonatomic) NSNumber *capacity; // @synthesize capacity=_capacity;
@property(retain, nonatomic) NSNumber *weight; // @synthesize weight=_weight;
@property(retain, nonatomic) NSString *truckTypeSet; // @synthesize truckTypeSet=_truckTypeSet;
@property(nonatomic) long long truckType; // @synthesize truckType=_truckType;
@property(copy, nonatomic) NSString *truckLengthSet; // @synthesize truckLengthSet=_truckLengthSet;
@property(retain, nonatomic) NSNumber *truckLength; // @synthesize truckLength=_truckLength;
@property(nonatomic) long long endPlace; // @synthesize endPlace=_endPlace;
@property(nonatomic) long long startPlace; // @synthesize startPlace=_startPlace;
@property(copy, nonatomic) NSString *consignorName; // @synthesize consignorName=_consignorName;
@property(nonatomic) long long showWindow; // @synthesize showWindow=_showWindow;
- (void).cxx_destruct;
- (id)truckLengthDescription;
@property(readonly, copy, nonatomic) NSString *goodsInfo;
@property(readonly, copy, nonatomic) NSString *roadLine;

// Remaining properties
@property(nonatomic) long long biddingCargo;
@property(copy, nonatomic) NSString *calllogRemark;
@property(copy, nonatomic) NSString *cargoCarStr;
@property(retain, nonatomic) NSNumber *cargoId;
@property(retain, nonatomic) id cargoUserId;
@property(copy, nonatomic) NSString *contact;
@property(nonatomic) long long dealModel;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(retain, nonatomic) NSNumber *freight;
@property(retain, nonatomic) NSNumber *freightUnit;
@property(readonly) unsigned long long hash;
@property(nonatomic) long long isExpire;
@property(nonatomic) long long isSelfCargo;
@property(copy, nonatomic) NSString *picture;
@property(nonatomic) unsigned long long securedTran;
@property(readonly) Class superclass;
@property(copy, nonatomic) NSString *telephone;
@property(retain, nonatomic) NSNumber *updateTime;
@property(nonatomic) long long virtualContactCargo;

@end

