//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIImageView, UILabel;

@interface YMMCargoReturnRouteAddressNewHeaderView : UIView
{
    UIImageView *_imageView;
    UILabel *_lab;
    NSString *_tip;
}

@property(copy, nonatomic) NSString *tip; // @synthesize tip=_tip;
@property(retain, nonatomic) UILabel *lab; // @synthesize lab=_lab;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)configureWithTip:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

