//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MBBaseModuleViewModel.h"

@class NSString;

@interface YMMDepositTitleSubviewModel : MBBaseModuleViewModel
{
    _Bool _canModify;
    NSString *_title;
    NSString *_modifyText;
    NSString *_carNumber;
}

@property(copy, nonatomic) NSString *carNumber; // @synthesize carNumber=_carNumber;
@property(nonatomic) _Bool canModify; // @synthesize canModify=_canModify;
@property(copy, nonatomic) NSString *modifyText; // @synthesize modifyText=_modifyText;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;

@end

