//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseTableViewCell.h"

#import "UITextFieldDelegate.h"

@class NSString, UILabel, UITextField, UIView;

@interface YMMDriveLicenseCell : YMMBaseTableViewCell <UITextFieldDelegate>
{
    _Bool _canEdit;
    CDUnknownBlockType _contentBlock;
    long long _fieldCellStyle;
    UITextField *_conTextField;
    UILabel *_titleLabel;
    UIView *_bottomLine;
}

+ (id)createReuseCellForTableView:(id)arg1 canEdit:(_Bool)arg2;
@property(nonatomic) _Bool canEdit; // @synthesize canEdit=_canEdit;
@property(retain, nonatomic) UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UITextField *conTextField; // @synthesize conTextField=_conTextField;
@property(nonatomic) long long fieldCellStyle; // @synthesize fieldCellStyle=_fieldCellStyle;
@property(copy, nonatomic) CDUnknownBlockType contentBlock; // @synthesize contentBlock=_contentBlock;
- (void).cxx_destruct;
- (void)dealloc;
- (_Bool)isValidCharacter:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textFieldShouldEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)textFieldValueChange:(id)arg1;
- (void)updateConstraints;
- (void)hideBottomLineView:(_Bool)arg1;
- (void)showTitle:(id)arg1 andContent:(id)arg2 andPlace:(id)arg3;
- (void)addsubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 canEdit:(_Bool)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

