//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseTableViewCell.h"

@class UIButton, UIImageView, UILabel, UIView, YMMEvaluationInfoModel, YMMEvaluationInfoView;

@interface YMMEvaluationCell : YMMBaseTableViewCell
{
    CDUnknownBlockType _showMoreEvaluationBlock;
    UIView *_containerView;
    UILabel *_bottomLabel;
    YMMEvaluationInfoView *_evaluateInfoView;
    UIView *_evaluateTagView;
    UIButton *_showMoreBtn;
    UIImageView *_showMoreIcon;
    YMMEvaluationInfoModel *_infoModel;
}

+ (double)tagsViewHeight:(id)arg1;
+ (double)ymm_heightForCellWithItem:(id)arg1 contentWidth:(double)arg2;
+ (id)ymm_createCellForTableView:(id)arg1;
@property(retain, nonatomic) YMMEvaluationInfoModel *infoModel; // @synthesize infoModel=_infoModel;
@property(retain, nonatomic) UIImageView *showMoreIcon; // @synthesize showMoreIcon=_showMoreIcon;
@property(retain, nonatomic) UIButton *showMoreBtn; // @synthesize showMoreBtn=_showMoreBtn;
@property(retain, nonatomic) UIView *evaluateTagView; // @synthesize evaluateTagView=_evaluateTagView;
@property(retain, nonatomic) YMMEvaluationInfoView *evaluateInfoView; // @synthesize evaluateInfoView=_evaluateInfoView;
@property(retain, nonatomic) UILabel *bottomLabel; // @synthesize bottomLabel=_bottomLabel;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(copy, nonatomic) CDUnknownBlockType showMoreEvaluationBlock; // @synthesize showMoreEvaluationBlock=_showMoreEvaluationBlock;
- (void).cxx_destruct;
- (void)updateConstraints;
- (void)removeTagFromEvaluateTagView;
- (void)addEvaluateTag;
- (id)evaluateTagLableWithTitle:(id)arg1 count:(long long)arg2 evaluateFlag:(long long)arg3;
- (void)showMoreEvaluate;
- (void)ymm_configWithItemModel:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

