//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class NSString;

@interface YMMEmojiAnimationDBModel : YMMCommonModel
{
    long long _configId;
    long long _configStatus;
    NSString *_type;
    long long _startTime;
    long long _endTime;
    NSString *_iconUrl;
    NSString *_audioUrl;
    long long _lastPlayTime;
    long long _playSeconds;
    long long _maxPlayCountEveryday;
    long long _playIntervalMinutes;
}

@property(nonatomic) long long playIntervalMinutes; // @synthesize playIntervalMinutes=_playIntervalMinutes;
@property(nonatomic) long long maxPlayCountEveryday; // @synthesize maxPlayCountEveryday=_maxPlayCountEveryday;
@property(nonatomic) long long playSeconds; // @synthesize playSeconds=_playSeconds;
@property(nonatomic) long long lastPlayTime; // @synthesize lastPlayTime=_lastPlayTime;
@property(copy, nonatomic) NSString *audioUrl; // @synthesize audioUrl=_audioUrl;
@property(copy, nonatomic) NSString *iconUrl; // @synthesize iconUrl=_iconUrl;
@property(nonatomic) long long endTime; // @synthesize endTime=_endTime;
@property(nonatomic) long long startTime; // @synthesize startTime=_startTime;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(nonatomic) long long configStatus; // @synthesize configStatus=_configStatus;
@property(nonatomic) long long configId; // @synthesize configId=_configId;
- (void).cxx_destruct;

@end

