//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LKDBHelper;

@interface YMMFebDBManager : NSObject
{
    LKDBHelper *_db;
}

+ (id)shared;
@property(retain, nonatomic) LKDBHelper *db; // @synthesize db=_db;
- (void).cxx_destruct;
- (id)selectAllForm;
- (id)selectConfigByToken:(id)arg1;
- (void)removeForm:(id)arg1;
- (void)removeAllConfig;
- (void)removeConfigBySceneName:(id)arg1;
- (void)insertConfig:(id)arg1;
- (void)insertForm:(id)arg1;
- (_Bool)createDatabase;
- (id)init;

@end

