//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIView, YMMFebDBManager, YMMFebDataRequestClient;

@interface YMMFebRender : NSObject
{
    UIView *_superView;
    YMMFebDataRequestClient *_requestClient;
    double _offsetY;
    id <YMMFedMaskViewProtocol> _showingMaskView;
    CDUnknownBlockType _stateCallback;
    YMMFebDBManager *_dbManager;
}

@property(retain, nonatomic) YMMFebDBManager *dbManager; // @synthesize dbManager=_dbManager;
@property(copy, nonatomic) CDUnknownBlockType stateCallback; // @synthesize stateCallback=_stateCallback;
@property(retain, nonatomic) id <YMMFedMaskViewProtocol> showingMaskView; // @synthesize showingMaskView=_showingMaskView;
@property(nonatomic) double offsetY; // @synthesize offsetY=_offsetY;
@property(retain, nonatomic) YMMFebDataRequestClient *requestClient; // @synthesize requestClient=_requestClient;
@property(retain, nonatomic) UIView *superView; // @synthesize superView=_superView;
- (void).cxx_destruct;
- (void)showErrorTips;
- (void)showSuccessTips;
- (void)saveLastTaskId:(id)arg1;
- (void)clearLastTaskId;
- (void)dismiss;
- (void)showConfirmListAlert:(id)arg1;
- (id)showConfirmAlert:(id)arg1;
- (id)showFormAlert:(id)arg1;
- (id)showViewByConfig:(id)arg1 superView:(id)arg2 offsetY:(double)arg3 callBack:(CDUnknownBlockType)arg4;
- (id)init;

@end

