//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class GTSetColBottomView, GTSetColSearchView, NSString, UITableView, YMMGTSearchDriverModel;

@interface YMMGTSetCollectionViewController : YMMBaseViewController <UITableViewDelegate, UITableViewDataSource>
{
    CDUnknownBlockType _setCollectionConfirmBlock;
    YMMGTSearchDriverModel *_driverModel;
    GTSetColSearchView *_topSearchView;
    UITableView *_tableView;
    GTSetColBottomView *_bottomConfirmView;
    YMMGTSearchDriverModel *_resultDriverModel;
}

@property(retain, nonatomic) YMMGTSearchDriverModel *resultDriverModel; // @synthesize resultDriverModel=_resultDriverModel;
@property(retain, nonatomic) GTSetColBottomView *bottomConfirmView; // @synthesize bottomConfirmView=_bottomConfirmView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) GTSetColSearchView *topSearchView; // @synthesize topSearchView=_topSearchView;
@property(retain, nonatomic) YMMGTSearchDriverModel *driverModel; // @synthesize driverModel=_driverModel;
@property(copy, nonatomic) CDUnknownBlockType setCollectionConfirmBlock; // @synthesize setCollectionConfirmBlock=_setCollectionConfirmBlock;
- (void).cxx_destruct;
- (id)ymm_pageName;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)requestSetCollectDriver;
- (void)requestSearchDriverWithPhoneNumber:(id)arg1;
- (void)relateShipSetAction:(id)arg1;
- (void)reloadData;
- (void)initViews;
- (void)backButtonPressed;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

