//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class NSString;

@interface YMMIMMessageCargoShowSwitchModel : YMMCommonModel
{
    _Bool _avoidDisturbing;
    _Bool _autologin;
    _Bool _pilotUser;
    _Bool _userTag;
    _Bool _cargo;
    NSString *_imPwd;
    unsigned long long _imUsername;
    unsigned long long _userid;
}

@property(nonatomic) _Bool cargo; // @synthesize cargo=_cargo;
@property(nonatomic) _Bool userTag; // @synthesize userTag=_userTag;
@property(nonatomic) _Bool pilotUser; // @synthesize pilotUser=_pilotUser;
@property(nonatomic) _Bool autologin; // @synthesize autologin=_autologin;
@property(nonatomic) _Bool avoidDisturbing; // @synthesize avoidDisturbing=_avoidDisturbing;
@property(nonatomic) unsigned long long userid; // @synthesize userid=_userid;
@property(nonatomic) unsigned long long imUsername; // @synthesize imUsername=_imUsername;
@property(copy, nonatomic) NSString *imPwd; // @synthesize imPwd=_imPwd;
- (void).cxx_destruct;

@end

