//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSError, NSProgress, NSString;

@interface YMMIMDownloadReceipt : NSObject
{
    NSString *_relativePath;
    NSString *_absolutePath;
    NSString *_userId;
    NSString *_conversationId;
    NSString *_filename;
    unsigned long long _state;
    NSString *_url;
    NSString *_speed;
    long long _totalBytesExpectedToWrite;
    NSError *_error;
    CDUnknownBlockType _downloaderProgressBlock;
    CDUnknownBlockType _downloaderCompletedBlock;
    unsigned long long _totalRead;
    NSDate *_date;
    id _downloadOperationCancelToken;
    NSString *_truename;
    NSProgress *_progress;
    long long _totalBytesWritten;
}

@property(nonatomic) long long totalBytesWritten; // @synthesize totalBytesWritten=_totalBytesWritten;
@property(retain, nonatomic) NSProgress *progress; // @synthesize progress=_progress;
@property(copy, nonatomic) NSString *truename; // @synthesize truename=_truename;
@property(retain, nonatomic) id downloadOperationCancelToken; // @synthesize downloadOperationCancelToken=_downloadOperationCancelToken;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(nonatomic) unsigned long long totalRead; // @synthesize totalRead=_totalRead;
@property(readonly, copy, nonatomic) CDUnknownBlockType downloaderCompletedBlock; // @synthesize downloaderCompletedBlock=_downloaderCompletedBlock;
@property(readonly, copy, nonatomic) CDUnknownBlockType downloaderProgressBlock; // @synthesize downloaderProgressBlock=_downloaderProgressBlock;
@property(readonly, nonatomic) NSError *error; // @synthesize error=_error;
@property(readonly, nonatomic) long long totalBytesExpectedToWrite; // @synthesize totalBytesExpectedToWrite=_totalBytesExpectedToWrite;
@property(readonly, copy, nonatomic) NSString *speed; // @synthesize speed=_speed;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(copy, nonatomic) NSString *filename; // @synthesize filename=_filename;
@property(copy, nonatomic) NSString *conversationId; // @synthesize conversationId=_conversationId;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(copy, nonatomic) NSString *absolutePath; // @synthesize absolutePath=_absolutePath;
@property(copy, nonatomic) NSString *relativePath; // @synthesize relativePath=_relativePath;
- (void).cxx_destruct;
- (void)setSpeed:(id)arg1;
- (void)setDownloaderCompletedBlock:(CDUnknownBlockType)arg1;
- (void)setDownloaderProgressBlock:(CDUnknownBlockType)arg1;
- (void)setTotalBytesExpectedToWrite:(long long)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithURLString:(id)arg1 downloadOperationCancelToken:(id)arg2 downloaderProgressBlock:(CDUnknownBlockType)arg3 downloaderCompletedBlock:(CDUnknownBlockType)arg4;
- (id)initWithURL:(id)arg1;

@end

