//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMIMCommonNetworkTask.h"

@class NSArray;

@interface YMMIMConversationFavrateTask : YMMIMCommonNetworkTask
{
    NSArray *_ids;
}

@property(retain, nonatomic) NSArray *ids; // @synthesize ids=_ids;
- (void).cxx_destruct;
- (Class)ymm_responseModelClass;
- (id)ymm_networkAPIPath;

@end

