//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseViewController.h"

#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"

@class NSMutableArray, NSString, UIButton, UILabel, UIPickerView, UIToolbar, UIView;

@interface YMMLogUploadViewController : YMMBaseViewController <UIPickerViewDelegate, UIPickerViewDataSource>
{
    _Bool _isUploading;
    NSMutableArray *_arrLogDates;
    UILabel *_dateLabel;
    UIButton *_uploadBtn;
    UIToolbar *_toolBar;
    UIPickerView *_pickerView;
    UIView *_containerView;
    UIView *_blackBackgroundView;
    UILabel *_uploadingTipLabel;
}

@property(nonatomic) _Bool isUploading; // @synthesize isUploading=_isUploading;
@property(retain, nonatomic) UILabel *uploadingTipLabel; // @synthesize uploadingTipLabel=_uploadingTipLabel;
@property(retain, nonatomic) UIView *blackBackgroundView; // @synthesize blackBackgroundView=_blackBackgroundView;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIPickerView *pickerView; // @synthesize pickerView=_pickerView;
@property(retain, nonatomic) UIToolbar *toolBar; // @synthesize toolBar=_toolBar;
@property(retain, nonatomic) UIButton *uploadBtn; // @synthesize uploadBtn=_uploadBtn;
@property(retain, nonatomic) UILabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(retain, nonatomic) NSMutableArray *arrLogDates; // @synthesize arrLogDates=_arrLogDates;
- (void).cxx_destruct;
- (id)pickerView:(id)arg1 titleForRow:(long long)arg2 forComponent:(long long)arg3;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (void)cancelBtnClicked;
- (void)doneBtnClicked;
- (void)onUploadClicked;
- (void)onSelectDate;
- (id)imageWithColor:(id)arg1 size:(struct CGSize)arg2;
- (_Bool)ymm_supportBackGesture;
- (void)ymm_doBack;
- (void)initView;
- (void)initData;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

