//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonNetworkTask.h"

@class NSString;

@interface YMMLoginTask : YMMCommonNetworkTask
{
    NSString *_code;
    NSString *_telephone;
    NSString *_cmToken;
}

@property(copy, nonatomic) NSString *cmToken; // @synthesize cmToken=_cmToken;
@property(copy, nonatomic) NSString *telephone; // @synthesize telephone=_telephone;
@property(copy, nonatomic) NSString *code; // @synthesize code=_code;
- (void).cxx_destruct;
- (long long)ymm_riskStage;
- (id)init;
- (Class)ymm_responseModelClass;
- (id)ymm_networkAPIPath;

@end

