//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseViewController.h"

#import "UITextFieldDelegate.h"
#import "YMMUserModuleControllerProtocol.h"

@class NSString, UIButton, UIImageView, UILabel, UIScrollView, UITextField, UIView, YMMHelpFooterView, YMMRegisterConfirmAlert, YMMUserModulePresenter;

@interface YMMLoginViewController : YMMBaseViewController <UITextFieldDelegate, YMMUserModuleControllerProtocol>
{
    _Bool _shouldShowCaptchToast;
    UIScrollView *_loginScrollView;
    UIImageView *_iconImageView;
    UILabel *_appVersionLabel;
    UITextField *_telTextField;
    YMMHelpFooterView *_footerView;
    UIButton *_loginButton;
    UIButton *_acceptButton;
    NSString *_telephone;
    NSString *_captcha;
    YMMUserModulePresenter *_presenter;
    UIView *_acceptUserProtocolView;
    double _lastCaptchaSentTimeInterval;
    long long _leftCountDownSeconds;
    UIButton *_shortcutAccountButton;
    YMMRegisterConfirmAlert *_alert;
}

@property(retain, nonatomic) YMMRegisterConfirmAlert *alert; // @synthesize alert=_alert;
@property(retain, nonatomic) UIButton *shortcutAccountButton; // @synthesize shortcutAccountButton=_shortcutAccountButton;
@property(nonatomic) _Bool shouldShowCaptchToast; // @synthesize shouldShowCaptchToast=_shouldShowCaptchToast;
@property(nonatomic) long long leftCountDownSeconds; // @synthesize leftCountDownSeconds=_leftCountDownSeconds;
@property(nonatomic) double lastCaptchaSentTimeInterval; // @synthesize lastCaptchaSentTimeInterval=_lastCaptchaSentTimeInterval;
@property(retain, nonatomic) UIView *acceptUserProtocolView; // @synthesize acceptUserProtocolView=_acceptUserProtocolView;
@property(retain, nonatomic) YMMUserModulePresenter *presenter; // @synthesize presenter=_presenter;
@property(copy, nonatomic) NSString *captcha; // @synthesize captcha=_captcha;
@property(copy, nonatomic) NSString *telephone; // @synthesize telephone=_telephone;
@property(retain, nonatomic) UIButton *acceptButton; // @synthesize acceptButton=_acceptButton;
@property(retain, nonatomic) UIButton *loginButton; // @synthesize loginButton=_loginButton;
@property(retain, nonatomic) YMMHelpFooterView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) UITextField *telTextField; // @synthesize telTextField=_telTextField;
@property(retain, nonatomic) UILabel *appVersionLabel; // @synthesize appVersionLabel=_appVersionLabel;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) UIScrollView *loginScrollView; // @synthesize loginScrollView=_loginScrollView;
- (void).cxx_destruct;
- (void)techLogForUserLogin:(id)arg1 scenario:(id)arg2;
- (void)journalForTap:(id)arg1;
- (void)journalForPageView:(id)arg1;
- (void)registerConfirmAlert;
- (void)pushToNextViewController;
- (void)pushToAuthViewController;
- (void)loginSuccessAction;
- (void)loginFailureAction:(id)arg1;
- (void)voiceCaptchaFailureAction:(id)arg1;
- (void)voiceCaptchaSuccessAction;
- (void)textCaptchaFailureAction:(id)arg1;
- (void)textCaptchaSuccessAction;
- (void)changeBtnClickEnable;
- (void)stopCountDown;
- (void)startCountDown:(long long)arg1;
- (void)stopLoading;
- (void)startLoading:(id)arg1;
- (void)startLoading;
- (_Bool)isValidNumber:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)textFieldChanged:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (id)customerServiceTelephone;
- (void)touchContact;
- (void)clickedRegisterButtonAction:(id)arg1;
- (void)clickedupdateTelephoneButtonAction:(id)arg1;
- (void)keyboardDismiss;
- (void)loginFaliureAlert;
- (void)clickedLoginButtonAction:(id)arg1;
- (void)touchHelp;
- (void)goToVisitorMainVC;
- (void)navBackIcon;
- (void)dissmissCurrentVC;
- (void)openWeb:(id)arg1;
- (void)ymm_doBack;
- (void)showShortcutAccountView:(id)arg1;
- (double)bottomGap;
- (double)updateButtonVgap;
- (double)loginVgap;
- (double)loginHeight;
- (double)telphoneViewHeight;
- (double)appVersion_telVgap;
- (double)image_appVersionVgap;
- (double)imageWidth;
- (double)topGap;
- (void)updateViewConstraints;
- (_Bool)ymm_supportBackGesture;
- (id)ymm_pageName;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

