//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface YMMMyCargoViewModel : NSObject
{
    long long _unicomCard;
    NSMutableDictionary *_sendMsgDic;
}

+ (long long)sendMsgTimeForCargoId:(id)arg1;
+ (id)cargoKeyForCargoId:(id)arg1;
+ (void)refreshCargoSecond:(long long)arg1;
@property(retain, nonatomic) NSMutableDictionary *sendMsgDic; // @synthesize sendMsgDic=_sendMsgDic;
@property(nonatomic) long long unicomCard; // @synthesize unicomCard=_unicomCard;
- (void).cxx_destruct;
- (void)saveCargoMessageForCargoId:(id)arg1 CargoMessage:(id)arg2;
- (id)cargoMessageForCargoId:(id)arg1 CargoMessage:(id)arg2;
- (void)showSendMsgAlertViewForDriverNumber:(long long)arg1 CargoId:(id)arg2 CargoMessage:(id)arg3 CallBack:(CDUnknownBlockType)arg4;
- (id)showSendMessageLoadingAlert;
- (void)sendMsgForCargoId:(id)arg1 CargoTitle:(id)arg2 CargoDetail:(id)arg3 Content:(id)arg4 DriverAry:(id)arg5 CallBack:(CDUnknownBlockType)arg6;
- (void)sendMsgLimitCallBack:(CDUnknownBlockType)arg1;
- (void)callRecommendDriverId:(id)arg1 CallBack:(CDUnknownBlockType)arg2;
- (id)driverIdAryForDriverModelAry:(id)arg1;
- (void)recommendDriverForCargoModel:(id)arg1 CallBack:(CDUnknownBlockType)arg2;
- (void)callDriverReportForCargoId:(id)arg1 UserId:(id)arg2;
- (void)cleanRefreshCargo;
- (void)saveRrfreshCargoId:(id)arg1;
- (_Bool)isMinRefreshSecond:(id)arg1;
- (_Bool)isWithinFiveMin:(id)arg1;
- (id)refreshCargoFilePath;
- (id)refreshCargoArray;
- (id)getRefreshCargoDate:(id)arg1;
- (id)cargoRefreshTimeForCargoId:(id)arg1;
- (_Bool)checkRefreshTimeForCargoId:(id)arg1;
- (void)deleteCargoForCargoId:(id)arg1 reasonValue:(id)arg2 selectedInsurance:(id)arg3 carNo:(id)arg4 callback:(CDUnknownBlockType)arg5;
- (void)deleteCargoForCargoId:(id)arg1 ReasonValue:(id)arg2 CallBack:(CDUnknownBlockType)arg3;
- (void)deleteCargoReasonCallBack:(CDUnknownBlockType)arg1;
- (void)deleteCargoForCargoId:(id)arg1 LoadingInView:(id)arg2 CallBack:(CDUnknownBlockType)arg3;
- (void)refreshCargoForCargoId:(id)arg1 CallBack:(CDUnknownBlockType)arg2;

@end

