//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class YMMMyCargoQuoteModel;

@interface YMMMyCargoQuoteQueryModel : YMMCommonModel
{
    YMMMyCargoQuoteModel *_consignorBargainOrderItem;
}

+ (Class)ymm_classForCollectionPropertyName:(id)arg1;
@property(retain, nonatomic) YMMMyCargoQuoteModel *consignorBargainOrderItem; // @synthesize consignorBargainOrderItem=_consignorBargainOrderItem;
- (void).cxx_destruct;

@end

