//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GTMainNoticeDelegate.h"

@class CTCallCenter, NSDate, NSMutableArray, NSString;

@interface YMMMainNoticeLogic : NSObject <GTMainNoticeDelegate>
{
    NSDate *lastDate;
    CTCallCenter *callCenter;
    _Bool _needPhoneMonitor;
    _Bool _applicationIsForground;
    id <YMMMainNoticeLogicDelegate> _delegate;
    NSMutableArray *_mainNoticeDataArray;
}

@property(nonatomic) _Bool applicationIsForground; // @synthesize applicationIsForground=_applicationIsForground;
@property(retain, nonatomic) NSMutableArray *mainNoticeDataArray; // @synthesize mainNoticeDataArray=_mainNoticeDataArray;
@property(nonatomic) _Bool needPhoneMonitor; // @synthesize needPhoneMonitor=_needPhoneMonitor;
@property(nonatomic) __weak id <YMMMainNoticeLogicDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)p_callCallBack;
- (void)p_applicationGoToBackground;
- (void)p_applicationEnterForground;
- (void)p_addReuqestInQueue;
- (void)addJournalForTapNotice:(id)arg1 UtmCampaign:(id)arg2;
- (void)mainNoticeDidClickLink:(id)arg1;
- (void)showNoticeView:(id)arg1;
- (void)receiveNoticeData:(id)arg1;
- (void)p_requestForMainNotice;
- (id)getMainNoticeItemInQueue;
- (void)addNoticeItemInQueue:(id)arg1;
- (void)addMainNoticeTaskInQueueWhenAppAct;
- (void)addMainNoticeTaskInQueueWhenBizAct;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

