//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseModel.h"

@class NSString;

@interface YMMMemberIconItemModel : YMMBaseModel
{
    NSString *_iconName;
    NSString *_iconPic;
    NSString *_iconUrl;
    NSString *_elementId;
}

@property(copy, nonatomic) NSString *elementId; // @synthesize elementId=_elementId;
@property(copy, nonatomic) NSString *iconUrl; // @synthesize iconUrl=_iconUrl;
@property(copy, nonatomic) NSString *iconPic; // @synthesize iconPic=_iconPic;
@property(copy, nonatomic) NSString *iconName; // @synthesize iconName=_iconName;
- (void).cxx_destruct;

@end

