//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMIMSinkProtocol.h"

@class EaseMessageModel, NSDictionary, NSError;

@protocol YMMMsgReceiveProtocol <YMMIMSinkProtocol>
- (void)didReceiveChatServerState:(long long)arg1;
- (void)chatDidReceiveCMDMessage:(EaseMessageModel *)arg1;
- (void)addAlertMessage:(EaseMessageModel *)arg1;
- (void)didReceiveResendMessageResponse:(EaseMessageModel *)arg1 andError:(NSError *)arg2 result:(NSDictionary *)arg3;
- (void)didReceiveSendMessageResponse:(EaseMessageModel *)arg1 andError:(NSError *)arg2 result:(NSDictionary *)arg3;
@end

