//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMPopupMaskView.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString, UIButton, UITableView;

@interface YMMMyCargoQuoteAlertView : YMMPopupMaskView <UITableViewDelegate, UITableViewDataSource>
{
    UITableView *_tableView;
    UIButton *_closeBtn;
    long long _type;
    NSString *_telephone;
}

@property(retain, nonatomic) NSString *telephone; // @synthesize telephone=_telephone;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) UIButton *closeBtn; // @synthesize closeBtn=_closeBtn;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (double)heightOfButton;
- (double)heightOfFlexibleWidth;
- (double)heightOfFlexibleHeight;
- (void)closeAlertView;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)show;
- (void)ymm_configWithType:(long long)arg1 Telephone:(id)arg2;
- (void)ymm_loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

