//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@interface YMMMyQuoteCargoModel : YMMCommonModel
{
    long long _biddingCargo;
    long long _badeForCargo;
    long long _amountOfBiddingByTrucker;
    long long _lowestBiddingCharge;
    long long _currentUserBadeCharge;
}

@property(nonatomic) long long currentUserBadeCharge; // @synthesize currentUserBadeCharge=_currentUserBadeCharge;
@property(nonatomic) long long lowestBiddingCharge; // @synthesize lowestBiddingCharge=_lowestBiddingCharge;
@property(nonatomic) long long amountOfBiddingByTrucker; // @synthesize amountOfBiddingByTrucker=_amountOfBiddingByTrucker;
@property(nonatomic) long long badeForCargo; // @synthesize badeForCargo=_badeForCargo;
@property(nonatomic) long long biddingCargo; // @synthesize biddingCargo=_biddingCargo;

@end

