//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseTableViewCell.h"

@class NSString, UIButton, UIImageView, UILabel, YMMMyCargoDetailModel;

@interface YMMMyCargoDetailRouteCell : YMMBaseTableViewCell
{
    CDUnknownBlockType _gotoMapDetailBlock;
    UILabel *_lineLb;
    UILabel *_updateTime;
    UILabel *_tipLb;
    UILabel *_miliLb;
    UIButton *_mapBt;
    NSString *_miles;
    UILabel *_localInvisibleTipLb;
    UILabel *_leftLocalCityLineLb;
    UILabel *_rightLocalCityLineLb;
    UIImageView *_cargoInsurImgView;
    UILabel *_oneBuyTextLabel;
    UIImageView *_oneBuyView;
    YMMMyCargoDetailModel *_detailModel;
}

+ (id)createCellForTableView:(id)arg1;
+ (id)cellIdentifiler;
+ (double)ymm_heightForCellWithItem:(id)arg1 contentWidth:(double)arg2;
@property(retain, nonatomic) YMMMyCargoDetailModel *detailModel; // @synthesize detailModel=_detailModel;
@property(retain, nonatomic) UIImageView *oneBuyView; // @synthesize oneBuyView=_oneBuyView;
@property(retain, nonatomic) UILabel *oneBuyTextLabel; // @synthesize oneBuyTextLabel=_oneBuyTextLabel;
@property(retain, nonatomic) UIImageView *cargoInsurImgView; // @synthesize cargoInsurImgView=_cargoInsurImgView;
@property(retain, nonatomic) UILabel *rightLocalCityLineLb; // @synthesize rightLocalCityLineLb=_rightLocalCityLineLb;
@property(retain, nonatomic) UILabel *leftLocalCityLineLb; // @synthesize leftLocalCityLineLb=_leftLocalCityLineLb;
@property(retain, nonatomic) UILabel *localInvisibleTipLb; // @synthesize localInvisibleTipLb=_localInvisibleTipLb;
@property(copy, nonatomic) NSString *miles; // @synthesize miles=_miles;
@property(retain, nonatomic) UIButton *mapBt; // @synthesize mapBt=_mapBt;
@property(retain, nonatomic) UILabel *miliLb; // @synthesize miliLb=_miliLb;
@property(retain, nonatomic) UILabel *tipLb; // @synthesize tipLb=_tipLb;
@property(retain, nonatomic) UILabel *updateTime; // @synthesize updateTime=_updateTime;
@property(retain, nonatomic) UILabel *lineLb; // @synthesize lineLb=_lineLb;
@property(copy, nonatomic) CDUnknownBlockType gotoMapDetailBlock; // @synthesize gotoMapDetailBlock=_gotoMapDetailBlock;
- (void).cxx_destruct;
- (void)requestForMiles:(id)arg1;
- (void)gotoMapDetail;
- (void)updateConstraints;
- (void)addSubViews;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)ymm_configWithItemModel:(id)arg1;
- (void)ymm_configWithItemModel:(id)arg1 miles:(id)arg2;

@end

