//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class NSAttributedString, NSNumber, NSString;

@interface YMMMessageModuleItemModel : YMMCommonModel
{
    long long _moduleType;
    NSString *_moduleTypeName;
    NSString *_lastMessage;
    long long _lastMessageSendTime;
    long long _unreadCount;
    NSNumber *_imMessageId;
    NSNumber *_fromUserId;
    NSString *_userName;
    NSString *_avatar;
    NSNumber *_imUsername;
    NSString *_userTelephone;
    NSString *_cargoInfo;
    NSAttributedString *_messageAStr;
}

@property(copy, nonatomic) NSAttributedString *messageAStr; // @synthesize messageAStr=_messageAStr;
@property(copy, nonatomic) NSString *cargoInfo; // @synthesize cargoInfo=_cargoInfo;
@property(retain, nonatomic) NSString *userTelephone; // @synthesize userTelephone=_userTelephone;
@property(retain, nonatomic) NSNumber *imUsername; // @synthesize imUsername=_imUsername;
@property(copy, nonatomic) NSString *avatar; // @synthesize avatar=_avatar;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(retain, nonatomic) NSNumber *fromUserId; // @synthesize fromUserId=_fromUserId;
@property(retain, nonatomic) NSNumber *imMessageId; // @synthesize imMessageId=_imMessageId;
@property(nonatomic) long long unreadCount; // @synthesize unreadCount=_unreadCount;
@property(nonatomic) long long lastMessageSendTime; // @synthesize lastMessageSendTime=_lastMessageSendTime;
@property(copy, nonatomic) NSString *lastMessage; // @synthesize lastMessage=_lastMessage;
@property(copy, nonatomic) NSString *moduleTypeName; // @synthesize moduleTypeName=_moduleTypeName;
@property(nonatomic) long long moduleType; // @synthesize moduleType=_moduleType;
- (void).cxx_destruct;
- (id)avatarURL;
- (id)lastMessageSendTimeDescription;

@end

