//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, YMMDeliveryAddressModel, YMMMineModuleNetWorkService;

@interface YMMMorePresenter : NSObject
{
    _Bool _needLoad;
    NSArray *_items;
    YMMDeliveryAddressModel *_addressModel;
    id <YMMBaseProfileInfoProtocol> _profile;
    id <YMMMineModuleControllerProtocol> _protocolView;
    YMMMineModuleNetWorkService *_service;
    id <YMMCustomerServiceProtocol> _customerService;
}

@property(retain, nonatomic) id <YMMCustomerServiceProtocol> customerService; // @synthesize customerService=_customerService;
@property(retain, nonatomic) YMMMineModuleNetWorkService *service; // @synthesize service=_service;
@property(nonatomic) __weak id <YMMMineModuleControllerProtocol> protocolView; // @synthesize protocolView=_protocolView;
@property(retain, nonatomic) id <YMMBaseProfileInfoProtocol> profile; // @synthesize profile=_profile;
@property(retain, nonatomic) YMMDeliveryAddressModel *addressModel; // @synthesize addressModel=_addressModel;
@property(copy, nonatomic) NSArray *items; // @synthesize items=_items;
@property(nonatomic) _Bool needLoad; // @synthesize needLoad=_needLoad;
- (void).cxx_destruct;
- (id)itemCodes;
- (id)addressCodeKey;
- (id)filterParams;
- (void)configUserDetailData:(id)arg1;
- (void)configUserProfile:(id)arg1;
- (void)requestMoreUserDetail:(CDUnknownBlockType)arg1;
- (void)contactUs;
- (void)requestIMDisturbingStatus:(_Bool)arg1;
- (void)requestMoreInfoAction:(_Bool)arg1;
- (void)requestMoreUserDetailAction;
@property(readonly, nonatomic) _Bool isIMAvoidSyatus;
@property(readonly, nonatomic) _Bool isIMOpen;
@property(readonly, nonatomic) _Bool isOpenFlag;
- (void)configProtocolView:(id)arg1;

@end

