//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class NSNumber, NSString, YMMOrderIMInitModel;

@interface YMMOrderContractInfoViewModel : YMMCommonModel
{
    _Bool _isHaveTitle;
    _Bool _isShowIMButton;
    NSString *_phoneString;
    YMMOrderIMInitModel *_imModel;
    long long _entranceType;
    long long _unreadMsgCount;
    long long _roleType;
    NSNumber *_userId;
}

@property(retain, nonatomic) NSNumber *userId; // @synthesize userId=_userId;
@property(nonatomic) long long roleType; // @synthesize roleType=_roleType;
@property(nonatomic) long long unreadMsgCount; // @synthesize unreadMsgCount=_unreadMsgCount;
@property(nonatomic) _Bool isShowIMButton; // @synthesize isShowIMButton=_isShowIMButton;
@property(nonatomic) long long entranceType; // @synthesize entranceType=_entranceType;
@property(retain, nonatomic) YMMOrderIMInitModel *imModel; // @synthesize imModel=_imModel;
@property(copy, nonatomic) NSString *phoneString; // @synthesize phoneString=_phoneString;
@property(nonatomic) _Bool isHaveTitle; // @synthesize isHaveTitle=_isHaveTitle;
- (void).cxx_destruct;

@end

