//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class NSArray, NSString;

@interface YMMOrderOtherInfoModel : YMMCommonModel
{
    NSString *_moduleTitle;
    NSArray *_infos;
}

+ (Class)ymm_classForCollectionPropertyName:(id)arg1;
@property(retain, nonatomic) NSArray *infos; // @synthesize infos=_infos;
@property(retain, nonatomic) NSString *moduleTitle; // @synthesize moduleTitle=_moduleTitle;
- (void).cxx_destruct;

@end

