//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseTableViewCell.h"

#import "YMMOrderUserInfoSubViewDelegate.h"

@class NSString, YMMOrderCompanyMessageView, YMMOrderUserInfoCellModel, YMMOrderUserInfoSubView, YMMOrderUserInfoSubViewModel;

@interface YMMOrderUserInfoCell : YMMBaseTableViewCell <YMMOrderUserInfoSubViewDelegate>
{
    id <YMMOrderUserInfoCellDelegate> _userInfoCellDelegate;
    YMMOrderCompanyMessageView *_companyInfoView;
    YMMOrderUserInfoSubView *_userInfoView;
    YMMOrderUserInfoSubViewModel *_subViewModel;
    YMMOrderUserInfoCellModel *_cellModel;
}

+ (double)ymm_heightForCellWithItem:(id)arg1 contentWidth:(double)arg2;
+ (id)cellWithTableView:(id)arg1;
@property(retain, nonatomic) YMMOrderUserInfoCellModel *cellModel; // @synthesize cellModel=_cellModel;
@property(retain, nonatomic) YMMOrderUserInfoSubViewModel *subViewModel; // @synthesize subViewModel=_subViewModel;
@property(retain, nonatomic) YMMOrderUserInfoSubView *userInfoView; // @synthesize userInfoView=_userInfoView;
@property(retain, nonatomic) YMMOrderCompanyMessageView *companyInfoView; // @synthesize companyInfoView=_companyInfoView;
@property(nonatomic) __weak id <YMMOrderUserInfoCellDelegate> userInfoCellDelegate; // @synthesize userInfoCellDelegate=_userInfoCellDelegate;
- (void).cxx_destruct;
- (void)addUserInfoSubContractsClickJournal:(id)arg1;
- (void)initUI;
- (void)ymm_configWithItemModel:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

