//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class NSNumber, NSString;

@interface YMMOrderIMInitModel : YMMCommonModel
{
    _Bool _imEnable;
    NSString *_name;
    NSString *_pictureStr;
    NSNumber *_userId;
    long long _depositStaus;
    NSString *_routeMessage;
    NSString *_goodsInfo;
    double _earnestAmount;
    NSString *_depositStatus;
    NSString *_depositAmount;
    NSString *_orderId;
    NSString *_orderDetailScheme;
    NSNumber *_imUsername;
    NSString *_imDisableReason;
}

@property(copy, nonatomic) NSString *imDisableReason; // @synthesize imDisableReason=_imDisableReason;
@property(nonatomic) _Bool imEnable; // @synthesize imEnable=_imEnable;
@property(retain, nonatomic) NSNumber *imUsername; // @synthesize imUsername=_imUsername;
@property(copy, nonatomic) NSString *orderDetailScheme; // @synthesize orderDetailScheme=_orderDetailScheme;
@property(copy, nonatomic) NSString *orderId; // @synthesize orderId=_orderId;
@property(retain, nonatomic) NSString *depositAmount; // @synthesize depositAmount=_depositAmount;
@property(retain, nonatomic) NSString *depositStatus; // @synthesize depositStatus=_depositStatus;
@property(nonatomic) double earnestAmount; // @synthesize earnestAmount=_earnestAmount;
@property(copy, nonatomic) NSString *goodsInfo; // @synthesize goodsInfo=_goodsInfo;
@property(copy, nonatomic) NSString *routeMessage; // @synthesize routeMessage=_routeMessage;
@property(nonatomic) long long depositStaus; // @synthesize depositStaus=_depositStaus;
@property(retain, nonatomic) NSNumber *userId; // @synthesize userId=_userId;
@property(copy, nonatomic) NSString *pictureStr; // @synthesize pictureStr=_pictureStr;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;

@end

