//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface YMMOrderListContactViewModel : NSObject
{
    long long _viewType;
    NSString *_leftProImage;
    NSString *_leftNameStr;
    NSString *_leftMessageStr;
    NSString *_rightProImage;
    NSString *_rightNameStr;
    NSString *_rightMessageStr;
}

@property(retain, nonatomic) NSString *rightMessageStr; // @synthesize rightMessageStr=_rightMessageStr;
@property(retain, nonatomic) NSString *rightNameStr; // @synthesize rightNameStr=_rightNameStr;
@property(retain, nonatomic) NSString *rightProImage; // @synthesize rightProImage=_rightProImage;
@property(retain, nonatomic) NSString *leftMessageStr; // @synthesize leftMessageStr=_leftMessageStr;
@property(retain, nonatomic) NSString *leftNameStr; // @synthesize leftNameStr=_leftNameStr;
@property(retain, nonatomic) NSString *leftProImage; // @synthesize leftProImage=_leftProImage;
@property(nonatomic) long long viewType; // @synthesize viewType=_viewType;
- (void).cxx_destruct;

@end

