//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class NSString;

@interface YMMOrderUniversalPlainInfoModel : YMMCommonModel
{
    NSString *_elementId;
    NSString *_moduleTitle;
    NSString *_moduleDetailText;
    NSString *_buttonText;
    NSString *_buttonURLScheme;
}

@property(retain, nonatomic) NSString *buttonURLScheme; // @synthesize buttonURLScheme=_buttonURLScheme;
@property(retain, nonatomic) NSString *buttonText; // @synthesize buttonText=_buttonText;
@property(retain, nonatomic) NSString *moduleDetailText; // @synthesize moduleDetailText=_moduleDetailText;
@property(retain, nonatomic) NSString *moduleTitle; // @synthesize moduleTitle=_moduleTitle;
@property(retain, nonatomic) NSString *elementId; // @synthesize elementId=_elementId;
- (void).cxx_destruct;

@end

