//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMPublishTableViewCell.h"

@class UILabel, YMMPublishInputView, YMMPublishInputViewModel;

@interface YMMPublishWeightAndCapacityCell : YMMPublishTableViewCell
{
    CDUnknownBlockType _weightCallback;
    CDUnknownBlockType _capacityCallback;
    UILabel *_titleLabel;
    YMMPublishInputView *_weightView;
    YMMPublishInputViewModel *_weightViewModel;
    YMMPublishInputView *_capacityView;
    YMMPublishInputViewModel *_capacityViewModel;
}

+ (double)ymm_heightForCellWithItem:(id)arg1 contentWidth:(double)arg2;
+ (id)createReuseCellForTableView:(id)arg1 withCellIdentifier:(id)arg2;
@property(retain, nonatomic) YMMPublishInputViewModel *capacityViewModel; // @synthesize capacityViewModel=_capacityViewModel;
@property(retain, nonatomic) YMMPublishInputView *capacityView; // @synthesize capacityView=_capacityView;
@property(retain, nonatomic) YMMPublishInputViewModel *weightViewModel; // @synthesize weightViewModel=_weightViewModel;
@property(retain, nonatomic) YMMPublishInputView *weightView; // @synthesize weightView=_weightView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(copy, nonatomic) CDUnknownBlockType capacityCallback; // @synthesize capacityCallback=_capacityCallback;
@property(copy, nonatomic) CDUnknownBlockType weightCallback; // @synthesize weightCallback=_weightCallback;
- (void).cxx_destruct;
- (void)ymm_configWithItemModel:(id)arg1;
- (void)capacityViewTap;
- (void)weightViewTap;
- (void)initConstraints;
- (void)initUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

