//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMPopupMaskView.h"

#import "UIGestureRecognizerDelegate.h"
#import "UITextFieldDelegate.h"

@class NSMutableArray, NSNumber, NSString, UIButton, UILabel, YMMCargoDetailViewModel, YMMQuoteIntervalModel, YMMQuoteTextField, YMMQuteCommitModel;

@interface YMMQuoteMaskView : YMMPopupMaskView <UITextFieldDelegate, UIGestureRecognizerDelegate>
{
    _Bool _hasJournal;
    _Bool _needUnitField;
    NSString *_refrePageName;
    CDUnknownBlockType _callback;
    CDUnknownBlockType _changeCallback;
    CDUnknownBlockType _cancelCallback;
    UILabel *_tipTitleLabel;
    UILabel *_tipDesTitleLable;
    YMMQuoteTextField *_remarkTextView;
    YMMQuoteTextField *_remarkWeightTextView;
    UILabel *_errorNoticeLabel;
    UILabel *_amountNoticeLabel;
    UILabel *_timeNoticeLabel;
    UIButton *_cancelButton;
    UIButton *_confirmButton;
    YMMCargoDetailViewModel *_viewModel;
    YMMQuoteIntervalModel *_priceInterval;
    NSMutableArray *_priceJournalArray;
    NSNumber *_bargainId;
    NSNumber *_cargoId;
    NSString *_totalPrice;
    YMMQuteCommitModel *_commitModel;
    double _alertOriginY;
}

@property(nonatomic) double alertOriginY; // @synthesize alertOriginY=_alertOriginY;
@property(retain, nonatomic) YMMQuteCommitModel *commitModel; // @synthesize commitModel=_commitModel;
@property(copy, nonatomic) NSString *totalPrice; // @synthesize totalPrice=_totalPrice;
@property(nonatomic) _Bool needUnitField; // @synthesize needUnitField=_needUnitField;
@property(nonatomic) _Bool hasJournal; // @synthesize hasJournal=_hasJournal;
@property(retain, nonatomic) NSNumber *cargoId; // @synthesize cargoId=_cargoId;
@property(retain, nonatomic) NSNumber *bargainId; // @synthesize bargainId=_bargainId;
@property(retain, nonatomic) NSMutableArray *priceJournalArray; // @synthesize priceJournalArray=_priceJournalArray;
@property(retain, nonatomic) YMMQuoteIntervalModel *priceInterval; // @synthesize priceInterval=_priceInterval;
@property(retain, nonatomic) YMMCargoDetailViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) UIButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UILabel *timeNoticeLabel; // @synthesize timeNoticeLabel=_timeNoticeLabel;
@property(retain, nonatomic) UILabel *amountNoticeLabel; // @synthesize amountNoticeLabel=_amountNoticeLabel;
@property(retain, nonatomic) UILabel *errorNoticeLabel; // @synthesize errorNoticeLabel=_errorNoticeLabel;
@property(retain, nonatomic) YMMQuoteTextField *remarkWeightTextView; // @synthesize remarkWeightTextView=_remarkWeightTextView;
@property(retain, nonatomic) YMMQuoteTextField *remarkTextView; // @synthesize remarkTextView=_remarkTextView;
@property(retain, nonatomic) UILabel *tipDesTitleLable; // @synthesize tipDesTitleLable=_tipDesTitleLable;
@property(retain, nonatomic) UILabel *tipTitleLabel; // @synthesize tipTitleLabel=_tipTitleLabel;
@property(copy, nonatomic) CDUnknownBlockType cancelCallback; // @synthesize cancelCallback=_cancelCallback;
@property(copy, nonatomic) CDUnknownBlockType changeCallback; // @synthesize changeCallback=_changeCallback;
@property(copy, nonatomic) CDUnknownBlockType callback; // @synthesize callback=_callback;
@property(copy, nonatomic) NSString *refrePageName; // @synthesize refrePageName=_refrePageName;
- (void).cxx_destruct;
- (void)quoteResultJournal:(_Bool)arg1 quoteSuccess:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldValueChanged:(id)arg1;
- (void)setAmountNoticeText:(id)arg1;
- (id)filterText:(id)arg1;
- (void)setJournalBusiness:(id)arg1;
- (void)reloadConfigView;
- (void)ymm_doDismiss;
- (void)configCommitQuoteParams;
- (void)changeQuote;
- (void)changeQuoteCargo:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)createQuote;
- (void)confirmQute:(id)arg1;
- (void)dismiss;
- (void)show;
- (void)showWithBargainId:(id)arg1 cargoId:(id)arg2 changeQuote:(id)arg3;
- (void)showWithCargoId:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)setConfirmButtonEnableWithText:(id)arg1;
- (void)updateViewConstraints;
- (void)layoutSubviews;
- (void)setViewConstraints;
- (void)initControls;
- (void)initContentView;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)addObservers;
- (_Bool)checkQuteUnitPriceAvailable:(id)arg1;
- (_Bool)checkQuteUnitCountAvailable:(id)arg1;
- (_Bool)checkQutePriceAvalibel:(id)arg1;
- (void)getPriceInterval:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (void)custom_Cancel;
- (void)custom_Cancel:(CDUnknownBlockType)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(copy, nonatomic) NSString *pageName;
@property(readonly) Class superclass;

@end

