//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel;

@interface YMMRedeemTableViewCell : UITableViewCell
{
    CDUnknownBlockType _redeemBlock;
    UILabel *_redeemLab;
}

@property(retain, nonatomic) UILabel *redeemLab; // @synthesize redeemLab=_redeemLab;
@property(copy, nonatomic) CDUnknownBlockType redeemBlock; // @synthesize redeemBlock=_redeemBlock;
- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

