//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonModel.h"

@class NSArray;

@interface YMMRNVersionModel : YMMCommonModel
{
    _Bool _fullUpdate;
    NSArray *_updateList;
}

+ (Class)ymm_classForCollectionPropertyName:(id)arg1;
@property(nonatomic) _Bool fullUpdate; // @synthesize fullUpdate=_fullUpdate;
@property(retain, nonatomic) NSArray *updateList; // @synthesize updateList=_updateList;
- (void).cxx_destruct;

@end

