//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MBBaseModuleViewModel.h"

@class NSString;

@interface YMMResultPageActionViewModel : MBBaseModuleViewModel
{
    NSString *_leftBtnTxt;
    NSString *_leftBtnActionUrl;
    NSString *_rightBtnTxt;
    NSString *_rightBtnActionUrl;
}

@property(retain, nonatomic) NSString *rightBtnActionUrl; // @synthesize rightBtnActionUrl=_rightBtnActionUrl;
@property(retain, nonatomic) NSString *rightBtnTxt; // @synthesize rightBtnTxt=_rightBtnTxt;
@property(retain, nonatomic) NSString *leftBtnActionUrl; // @synthesize leftBtnActionUrl=_leftBtnActionUrl;
@property(retain, nonatomic) NSString *leftBtnTxt; // @synthesize leftBtnTxt=_leftBtnTxt;
- (void).cxx_destruct;

@end

