//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YMMReactNativePerformance : NSObject
{
    long long _rnEnvInitCount;
    unsigned long long _startMemory;
    long long _timeStamp;
    unsigned long long _endMemory;
    unsigned long long _memoryLeft;
}

+ (id)shared;
@property(nonatomic) unsigned long long memoryLeft; // @synthesize memoryLeft=_memoryLeft;
@property(nonatomic) unsigned long long endMemory; // @synthesize endMemory=_endMemory;
@property(nonatomic) long long timeStamp; // @synthesize timeStamp=_timeStamp;
@property(nonatomic) unsigned long long startMemory; // @synthesize startMemory=_startMemory;
@property(nonatomic) long long rnEnvInitCount; // @synthesize rnEnvInitCount=_rnEnvInitCount;
- (unsigned long long)freeDiskSpace;
- (unsigned long long)getResidentMemory;

@end

