//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCargoBaseViewModel.h"

@interface YMMSubscriptEditViewModel : YMMCargoBaseViewModel
{
}

- (id)trunkLengthDescription:(id)arg1;
- (id)cityCodesString:(id)arg1;
- (id)trunkLengthUpperString:(id)arg1;
- (id)trunkLengthString:(id)arg1;
- (id)trunkTypeString:(id)arg1;
- (void)getNearbyCitys:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)updateSubscription:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)addSubscription:(id)arg1 callback:(CDUnknownBlockType)arg2;

@end

