//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIImage;

@interface YMMShareInfo : NSObject
{
    NSString *_strTitle;
    NSString *_strWebLink;
    NSString *_strDesc;
    UIImage *_shareImage;
    NSString *_strImgUrl;
    unsigned long long _shareType;
    unsigned long long _shareChannel;
    NSString *_cargoId;
}

@property(copy, nonatomic) NSString *cargoId; // @synthesize cargoId=_cargoId;
@property(nonatomic) unsigned long long shareChannel; // @synthesize shareChannel=_shareChannel;
@property(nonatomic) unsigned long long shareType; // @synthesize shareType=_shareType;
@property(copy, nonatomic) NSString *strImgUrl; // @synthesize strImgUrl=_strImgUrl;
@property(retain, nonatomic) UIImage *shareImage; // @synthesize shareImage=_shareImage;
@property(copy, nonatomic) NSString *strDesc; // @synthesize strDesc=_strDesc;
@property(copy, nonatomic) NSString *strWebLink; // @synthesize strWebLink=_strWebLink;
@property(copy, nonatomic) NSString *strTitle; // @synthesize strTitle=_strTitle;
- (void).cxx_destruct;

@end

