//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray;

@interface YMMSecurityOrderProcessView : UIView
{
    NSArray *_imagesArr;
    NSArray *_titlesArr;
    UIView *_stepsView;
}

@property(retain, nonatomic) UIView *stepsView; // @synthesize stepsView=_stepsView;
- (void).cxx_destruct;
- (void)setupViews;
- (id)initWithTitles:(id)arg1 andIconNames:(id)arg2;

@end

