//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "YMMManagerService.h"

@class NSString;

@interface YMMStartupMgr : NSObject <YMMManagerService>
{
}

- (void)lazyInitManagers;
- (void)delayInitManagers;
- (void)syncInitManagers;
- (void)onManagerInit;
- (_Bool)isManagerPersistent;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

