//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseTableViewCell.h"

@class UIImageView, UILabel;

@interface YMMShareCardFooterCell : YMMBaseTableViewCell
{
    UIImageView *_qrcodeImage;
    UIImageView *_fingerImage;
    UIImageView *_logoImage;
    UILabel *_titleLabel;
}

+ (double)ymm_heightForCellWithItem:(id)arg1 contentWidth:(double)arg2;
+ (id)createReuseFooterCellForTableView:(id)arg1;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *logoImage; // @synthesize logoImage=_logoImage;
@property(retain, nonatomic) UIImageView *fingerImage; // @synthesize fingerImage=_fingerImage;
@property(retain, nonatomic) UIImageView *qrcodeImage; // @synthesize qrcodeImage=_qrcodeImage;
- (void).cxx_destruct;
- (void)ymm_configWithItemModel:(id)arg1;
- (void)updateConstraints;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

