//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonNetworkTask.h"

@class NSString;

@interface YMMUploadScreenImageToQATask : YMMCommonNetworkTask
{
    NSString *_fileName;
    NSString *_deviceId;
}

@property(copy, nonatomic) NSString *deviceId; // @synthesize deviceId=_deviceId;
@property(copy, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
- (void).cxx_destruct;
- (_Bool)ymm_needEncryption;
- (_Bool)ymm_needActionResponse;
- (id)ymm_networkAPIFullPath;

@end

