//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, YMMAuthBaseNetWorkService, YMMAuthorizePopupNetWorkService, YMMCheckCertifyStatusModel, YMMCopilotManager, YMMCopilotNetWorkService, YMMCustomerSceneEntranceModel, YMMPopupCheckModel, YMMUserAuditInfoModel, YMMUserAuditStatusModel;

@interface YMMUserAuditManager : NSObject
{
    _Bool _auditStep;
    _Bool _isRequestingSceneId2;
    YMMUserAuditInfoModel *_auditInfo;
    YMMUserAuditInfoModel *_userInputInfo;
    YMMCopilotManager *_copilotManager;
    YMMPopupCheckModel *_popUpModel;
    NSString *_sceneName;
    NSArray *_allEntranceModel;
    YMMCustomerSceneEntranceModel *_currentEntrance;
    YMMAuthBaseNetWorkService *_authService;
    YMMCopilotNetWorkService *_copilotService;
    YMMAuthorizePopupNetWorkService *_authPopUpService;
    YMMUserAuditStatusModel *_auditStatusModel;
    long long _retryCount;
    id <YMMUserAuditProtocol> _hcbAuthStatus;
    id <YMMUserAuditCommonProtocol> _config;
    YMMCheckCertifyStatusModel *_applaunchCertifyStatusModel;
    YMMCheckCertifyStatusModel *_certifyStatusModel;
}

+ (id)sharedYMMUserAuditManager;
+ (id)allocWithZone:(struct _NSZone *)arg1;
@property(nonatomic, getter=isRequestingSceneId2) _Bool isRequestingSceneId2; // @synthesize isRequestingSceneId2=_isRequestingSceneId2;
@property(retain, nonatomic) YMMCheckCertifyStatusModel *certifyStatusModel; // @synthesize certifyStatusModel=_certifyStatusModel;
@property(retain, nonatomic) YMMCheckCertifyStatusModel *applaunchCertifyStatusModel; // @synthesize applaunchCertifyStatusModel=_applaunchCertifyStatusModel;
@property(retain, nonatomic) id <YMMUserAuditCommonProtocol> config; // @synthesize config=_config;
@property(retain, nonatomic) id <YMMUserAuditProtocol> hcbAuthStatus; // @synthesize hcbAuthStatus=_hcbAuthStatus;
@property(nonatomic) long long retryCount; // @synthesize retryCount=_retryCount;
@property(retain, nonatomic) YMMUserAuditStatusModel *auditStatusModel; // @synthesize auditStatusModel=_auditStatusModel;
@property(retain, nonatomic) YMMAuthorizePopupNetWorkService *authPopUpService; // @synthesize authPopUpService=_authPopUpService;
@property(retain, nonatomic) YMMCopilotNetWorkService *copilotService; // @synthesize copilotService=_copilotService;
@property(retain, nonatomic) YMMAuthBaseNetWorkService *authService; // @synthesize authService=_authService;
@property(retain, nonatomic) YMMCustomerSceneEntranceModel *currentEntrance; // @synthesize currentEntrance=_currentEntrance;
@property(copy, nonatomic) NSArray *allEntranceModel; // @synthesize allEntranceModel=_allEntranceModel;
@property(copy, nonatomic) NSString *sceneName; // @synthesize sceneName=_sceneName;
@property(retain, nonatomic) YMMPopupCheckModel *popUpModel; // @synthesize popUpModel=_popUpModel;
@property(nonatomic) _Bool auditStep; // @synthesize auditStep=_auditStep;
@property(retain, nonatomic) YMMCopilotManager *copilotManager; // @synthesize copilotManager=_copilotManager;
@property(retain, nonatomic) YMMUserAuditInfoModel *userInputInfo; // @synthesize userInputInfo=_userInputInfo;
@property(retain, nonatomic) YMMUserAuditInfoModel *auditInfo; // @synthesize auditInfo=_auditInfo;
- (void).cxx_destruct;
- (void)addTapJournalWithPageName:(id)arg1 elementId:(id)arg2 launchParams:(id)arg3 authType:(id)arg4 content:(id)arg5;
- (void)addViewJournalWithPageName:(id)arg1 elementId:(id)arg2 launchParams:(id)arg3 authType:(id)arg4 content:(id)arg5;
- (void)techLogForAuthRequestDict:(id)arg1 scenario:(id)arg2;
- (void)networkTaskForAuthorizePopupConfirm:(CDUnknownBlockType)arg1;
- (void)networkTaskForAuthorizePopupCancel:(CDUnknownBlockType)arg1;
- (void)networkTaskForAuthorizePopupCheck:(CDUnknownBlockType)arg1;
- (void)contactUsByScene:(id)arg1;
- (_Bool)openCustomerService;
- (id)entranceModelByScene:(id)arg1;
- (void)requestAllCustomerServiceSence:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)requestAllCustomerServiceAllSence:(CDUnknownBlockType)arg1;
- (id)cacheUserInfoKey:(id)arg1;
- (void)cleanCacheUserInfoByKey:(id)arg1;
- (id)userInfoFromCacheByKey:(id)arg1;
- (void)saveUserInfoToCache:(id)arg1 keyName:(id)arg2;
- (void)cleanCacheCustomerServiceData;
- (id)customerSceneList;
- (void)saveCustomerServiceDataToCache:(id)arg1;
- (void)cleanCacheUserInputInfo;
- (id)userInputInfoCache;
- (void)saveCacheUserInputInfo;
- (_Bool)authStatusUnCommited;
- (id)telephone;
- (void)saveTelephone:(id)arg1;
- (void)cleanAuthenticateResultFromCache;
- (id)authenticateResultFromCache;
- (void)saveAuthenticateResultToCache:(id)arg1;
- (void)queryDriverAuthStatus:(CDUnknownBlockType)arg1;
- (void)queryDriverAuthInfo:(CDUnknownBlockType)arg1;
- (void)queryShipperAuthInfoAndStatus:(CDUnknownBlockType)arg1;
- (void)setAuthConfig;
- (void)requestUserAuthResultAction;
- (void)gotoAuditInfoForShipperSimpleAuth;
- (void)gotoAuditInfoWithTarget:(id)arg1;
- (void)auditFailureCommitInfo;
- (void)loadUserCache;
- (_Bool)canShowFromConfigurationManager;
- (void)addNotification;
- (void)cleanCacheInfoForLogout;
- (void)syncHCBUserAuthStatusToYMM;
- (void)showNetworkErrorAlert;
- (void)didClickConfirmButtonWithAuthorizedAlertView:(id)arg1;
- (void)showAuthorizationAlertViewIfNeedWithSceneID:(long long)arg1 isSimpleAlert:(_Bool)arg2;
- (void)showAlertIfRealNameNotPassAndNeedAlertWithSceneID:(long long)arg1;
- (_Bool)isRealNameAuthorized;
- (_Bool)isRealNameAuthorizedWhenAppLaunch;
- (_Bool)isAllAuthorityAlert;
- (_Bool)isAllAuthorityNoAlert;
- (void)userUnAuthStatusAlert:(id)arg1 actionBtntitle:(id)arg2;
- (void)shipperUnAuthStatusAlert;
- (void)showUnAuthedAlert;
- (_Bool)isAllAuthority;
- (void)userAuditState:(id)arg1;
- (void)logoutResetCertifyStatus;
- (void)requestChcekCertifyStautsWithSceneID:(long long)arg1;
- (void)requestCheckCertifyStatusWithCheckRealName;
- (void)requestCheckCertifyStatusWithAppLaunch;
- (void)requestChcekCertifyStautsWithAllSceneByForce;
- (void)queryUserAuthInfoAndStatus:(CDUnknownBlockType)arg1;
- (void)userAuthResult:(CDUnknownBlockType)arg1;
- (void)queryUserAuthStatus:(CDUnknownBlockType)arg1;
- (void)queryUserAuthInfo:(CDUnknownBlockType)arg1;
- (void)userAuthInfo:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)init;

@end

