//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMAuthBaseNetWorkService.h"

@interface YMMUserAuditNetWorkService : YMMAuthBaseNetWorkService
{
}

- (void)netWorkTaskForTruckBrands:(CDUnknownBlockType)arg1;
- (void)netWorkTaskForDriverAuthInfo:(CDUnknownBlockType)arg1;
- (void)netWorkTaskForShipperAuthInfo:(CDUnknownBlockType)arg1;
- (void)netWorkTaskForDriverCommitAuthInfo:(id)arg1 requestCallBack:(CDUnknownBlockType)arg2;
- (void)netWorkTaskForCommitShipperCompanyInfo:(id)arg1 requestCallBack:(CDUnknownBlockType)arg2;
- (void)netWorkTaskForNewShipperCommitAuthInfo:(id)arg1 requestCallBack:(CDUnknownBlockType)arg2;
- (void)netWorkTaskForShipperCommitAuthInfo:(id)arg1 requestCallBack:(CDUnknownBlockType)arg2;

@end

