//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMCommonNetworkTask.h"

@class NSNumber, NSString;

@interface YMMUpdateCommonLinesTask : YMMCommonNetworkTask
{
    NSNumber *_userId;
    NSString *_commonLines;
}

@property(copy, nonatomic) NSString *commonLines; // @synthesize commonLines=_commonLines;
@property(retain, nonatomic) NSNumber *userId; // @synthesize userId=_userId;
- (void).cxx_destruct;
- (Class)ymm_responseModelClass;
- (id)ymm_networkAPIPath;

@end

