//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseModel.h"

#import "YMMViewInfoProtocol.h"

@class NSMutableArray, NSString;

@interface YMMViewTreeNodeModel : YMMBaseModel <YMMViewInfoProtocol>
{
    double originX;
    double originY;
    double width;
    double height;
    NSString *elementId;
    NSString *_className;
    long long _enableClick;
    NSMutableArray *_subNodes;
}

@property(retain, nonatomic) NSMutableArray *subNodes; // @synthesize subNodes=_subNodes;
@property(nonatomic) long long enableClick; // @synthesize enableClick=_enableClick;
@property(copy, nonatomic) NSString *className; // @synthesize className=_className;
@property(copy, nonatomic) NSString *elementId; // @synthesize elementId;
@property(nonatomic) double height; // @synthesize height;
@property(nonatomic) double width; // @synthesize width;
@property(nonatomic) double originY; // @synthesize originY;
@property(nonatomic) double originX; // @synthesize originX;
- (void).cxx_destruct;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

