//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class YMMWindow;

@interface YMMWindowManager : NSObject
{
    _Bool _isShow;
    YMMWindow *_window;
}

+ (id)sharedYMMWindowManager;
+ (id)allocWithZone:(struct _NSZone *)arg1;
@property(nonatomic) _Bool isShow; // @synthesize isShow=_isShow;
@property(retain, nonatomic) YMMWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)hidden;
- (void)show;
- (id)ymmWindow;

@end

