//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YMMBaseShareViewModel.h"

@interface YMMWeChatShareViewModel : YMMBaseShareViewModel
{
    int _currentScene;
}

+ (id)requstStringWithRequstCode:(long long)arg1;
@property(nonatomic) int currentScene; // @synthesize currentScene=_currentScene;
- (void)shareMiniAppToWeChat;
- (void)shareImageToWeChat;
- (void)shareTextToWeChat;
- (void)shareWebpageToWeChat;
- (void)shareAction;

@end

